Repository apache/cloudstack, pull requests merged in 2018-11, with the labels that each got.

#2987 Fix set affinity for user overlay problem (Fixes #2986)
  ui/scripts/ui-custom/affinity.js
Labels: UI, bug

#3010 Fix DirectNetworkGuru canHandle checks for lowercase isolation methods
  server/src/com/cloud/network/guru/DirectNetworkGuru.java
  server/test/com/cloud/network/guru/DirectNetworkGuruTest.java
Labels: bug

#3003 make sure no time skew can interfere with comparison
  utils/src/test/java/com/cloud/utils/DateUtilTest.java
Labels: enhancement

#2839 Enable DPDK support on KVM
  agent/conf/agent.properties
  api/src/main/java/com/cloud/agent/api/to/NicTO.java
  api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/DirectVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VifDriverBase.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPlugNicCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReplugNicCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/OvsVifDriverTest.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: kvm, openvswitch

#2980 [4.11] Fix set initial reservation on public IP ranges
  server/src/com/cloud/configuration/ConfigurationManagerImpl.java
  ui/scripts/system.js
Labels: enhancement

#2896 add exitcode / distribution detection and remove export CGROUP_DAEMON for RHEL7/CentOS7
  python/lib/cloudutils/serviceConfig.py
Labels: enhancement

#2905 Fix delete domain button in the UI to update only after deleteDomain job finishes
  ui/scripts/domains.js
Labels: UI, bug

#3007 Add missing ConfigDrive entries on existing zones after upgrade
  server/src/com/cloud/network/NetworkModelImpl.java
  server/test/com/cloud/network/NetworkModelTest.java
Labels: bug, manual-tests-passing, testing

#2919 vmware: updateVmwareDc API for updating vmware datacenter details
  engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
  engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/VmwareDatacenterService.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/api/command/admin/zone/UpdateVmwareDcCmd.java
  plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/VmwareDatacenterApiUnitTest.java
  plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImplTest.java
  ui/css/cloudstack3.css
  ui/l10n/en.js
  ui/scripts/system.js
Labels: vmware

#3013 Print log on INFO if Host reached Max Guests Limit
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
Labels: enhancement, management-server

#3016 documented host.reserved.mem.mb parameter
  agent/conf/agent.properties
Labels: Documentation, agent, enhancement

#2985 kvm/ceph: When create a new RBD image use modern flags/features for t…
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
Labels: ceph, kvm

#3022 systemvmtemplate: update debian 9.6 iso url and checksum
  tools/appliance/systemvmtemplate/template.json
Labels: systemvm-template-change, virtual-router

#3021 Skip network migration tests for not supported hypervisors instead of failing
  test/integration/smoke/test_migration.py
Labels: testing

#3014 Remove unused StrategyPriority.PLUGIN
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StrategyPriority.java
  engine/storage/src/test/java/org/apache/cloudstack/engine/subsystem/api/storage/StrategyPriorityTest.java
Labels: Cleanup

#3038 surefire: ignore system classloader to make tests run
  pom.xml
Labels: BLOCKER

#3053 ipv6: Advanced Networking Security Groups are supported
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
Labels: advanced-networking, ipv6

#2595 CLOUDSTACK-10199: Support requesting a specific IPv4 address
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
  engine/schema/src/main/java/com/cloud/dc/dao/VlanDao.java
  engine/schema/src/main/java/com/cloud/dc/dao/VlanDaoImpl.java
  server/src/main/java/com/cloud/network/guru/DirectPodBasedNetworkGuru.java
  utils/src/main/java/com/cloud/utils/net/NetUtils.java
Labels: bug

#3042 Allow password enabled for iso (#2745)
  api/src/main/java/org/apache/cloudstack/api/command/user/iso/RegisterIsoCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/iso/UpdateIsoCmd.java
  server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
  server/src/main/java/com/cloud/template/TemplateAdapterBase.java
  test/integration/smoke/test_iso.py
Labels: api

#3062 Fix null pointer exception when using ConfigKey.Scope.ManagementServer
  framework/config/src/main/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImpl.java
  framework/config/src/test/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImplTest.java
Labels: config, enhancement

#2990 Security Group: add secondary ips to the correct ipset based on ip family (4.11)
  scripts/vm/network/security_group.py
Labels: bug, security-group

#3037 kvm: when untagged vxlan is used, use the default guest/public bridge
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
  plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/BridgeVifDriverTest.java
Labels: kvm, networking

#3066 API: move ostypeid from DB id to DB uuid, backports #2528
  api/src/org/apache/cloudstack/api/response/UserVmResponse.java
  server/src/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
Labels: api

#2660 Macaddresses
  utils/src/main/java/com/cloud/utils/net/MacAddress.java
  utils/src/test/java/com/cloud/utils/net/MacAddressTest.java
Labels: networking
