Repository apache/cloudstack, pull requests merged in 2018-10, with the labels that each got.

#2866 systemvm: baremetal-vr: reduce memory usage
  systemvm/debian/opt/cloud/bin/baremetal-vr.py
Labels: bug, virtual-router

#2849 Remove deprecated buildw and wix plugin
  client/pom.xml
  pom.xml
  scripts/installer/windows/Setup_Databases.wxs
  scripts/installer/windows/WixInstallerDialog.wxs
  scripts/installer/windows/acs.wxs
  scripts/installer/windows/acs_license.rtf
  scripts/installer/windows/client.wxs
  scripts/installer/windows/dependencies.wxs
  scripts/installer/windows/en-us.wxl
  scripts/installer/windows/optionstheme.xml
  scripts/installer/windows/optionstheme_en-us.wxl
  scripts/installer/windows/start.bat
  tools/wix-cloudstack-maven-plugin/pom.xml
  tools/wix-cloudstack-maven-plugin/src/main/java/org/apache/cloudstack/wix/HeatMojo.java
Labels: Cleanup

#2875 CertUtils: export private key to pem format correctly
  utils/src/main/java/org/apache/cloudstack/utils/security/CertUtils.java
Labels: security

#2878 Fixed Issue 2868, libvirt resize notify failure
  scripts/storage/qcow2/resizevolume.sh
Labels: bug, kvm, primary-storage

#2879 ca: Fixes #2877 mgmt server cert should have all addrs of default nic
  plugins/ca/root-ca/src/org/apache/cloudstack/ca/provider/RootCAProvider.java
  utils/src/main/java/com/cloud/utils/net/NetUtils.java
  utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Labels: bug

#2884 add date to usage server logs
  usage/conf/log4j-cloud_usage.xml.in
Labels: bug, logging

#2889 Fixes: #2881 Improve Exception message
  api/src/com/cloud/network/Network.java
  plugins/network-elements/nuage-vsp/test/com/cloud/network/element/NuageVspElementTest.java
Labels: bug

#2888 router: Fixes #2719 program VR nics by device id order for VPC
  api/src/com/cloud/network/NetworkProfile.java
  engine/schema/src/com/cloud/vm/dao/NicDao.java
  engine/schema/src/com/cloud/vm/dao/NicDaoImpl.java
  server/src/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
  systemvm/debian/opt/cloud/bin/cs_ip.py
  utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Labels: BLOCKER, bug

#2876 PULL_REQUEST_TEMPLATE: simplify and remove unpopular sections
  PULL_REQUEST_TEMPLATE.md
Labels: Cleanup

#2892 vr: memory and swap optimizations
  plugins/hypervisors/baremetal/src/com/cloud/baremetal/networkservice/BaremetalKickStartServiceImpl.java
  systemvm/debian/etc/sysctl.conf
  systemvm/debian/etc/systemd/journald.conf
  systemvm/debian/etc/systemd/system/baremetal-vr.service
  systemvm/debian/etc/systemd/system/cloud-postinit.service
  systemvm/debian/opt/cloud/bin/setup/postinit.sh
Labels: virtual-router

#2903 Set http level to INFO as default
  agent/conf/log4j-cloud.xml.in
Labels: config, logging

#2897 Allow enable the Java remote Debug for CloudStack Agent
  packaging/systemd/cloudstack-agent.default
  packaging/systemd/cloudstack-agent.service
Labels: enhancement, systemd

#2904 agent: Fixes #2899 on shutdown don't allow server reconnection
  agent/src/com/cloud/agent/Agent.java
Labels: agent, kvm

#2900 network: Allow ability to disable rolling restart feature
  engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/com/cloud/network/vpc/VpcManagerImpl.java
Labels: networking

#2912 kvm: Use libvirtd as service name for libvirt for Debian (#2909)
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPostCertificateRenewalCommandWrapper.java
Labels: bug

#2907 client: mgmt server listen default to 0.0.0.0
  client/conf/server.properties.in
  client/src/org/apache/cloudstack/ServerDaemon.java
Labels: bug, management-server

#2916 systemvm: Ensure cloud service reboots after failure
  systemvm/debian/etc/systemd/system/cloud-postinit.service
  systemvm/debian/etc/systemd/system/cloud.service
Labels: Critical, ssvm

#2915 packaging: install plugins at /usr/share/cloudstack-management/lib
  packaging/centos63/cloud.spec
  packaging/centos7/cloud.spec
Labels: packaging

#2926 network: on rolling restart force stop old routers
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/com/cloud/network/vpc/VpcManagerImpl.java
Labels: virtual-router

#2923 Improved perfomance on creating VM (KVM)
  scripts/vm/network/vnet/modifyvlan.sh
Labels: kvm

#2927 server: fix unwanted txn commit warning messages
  server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
Labels: logging

#2979 vr: defer was broken in VR because of json name change
  systemvm/debian/opt/cloud/bin/update_config.py
Labels: bug, virtual-router

#2984 kvm: reset KVM host on heartbeat failure
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/KVMHABase.java
  scripts/vm/hypervisor/kvm/kvmheartbeat.sh
Labels: BLOCKER, Critical, kvm
