Repository apache/cloudstack, pull requests merged in 2018-08, with the labels that each got.

#2781 hvm checkbox visibility
  ui/scripts/templates.js
Labels: UI, bug

#2792 Fix issue when multiple cidrs with different sizes are assigned on a VR
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
Labels: bug, virtual-router

#2791 router: Fixes #2789 fix proper mark based packet routing across interfaces
  server/src/com/cloud/api/ApiResponseHelper.java
  systemvm/debian/opt/cloud/bin/cloud-nic.sh
  systemvm/debian/opt/cloud/bin/cs/CsNetfilter.py
  systemvm/debian/opt/cloud/bin/cs/CsRoute.py
  systemvm/debian/opt/cloud/bin/cs/CsRule.py
  systemvm/debian/opt/cloud/bin/ipassoc.sh
  systemvm/debian/opt/cloud/bin/update_config.py
  test/integration/smoke/test_deploy_virtio_scsi_vm.py
  test/integration/smoke/test_vm_life_cycle.py
Labels: Critical, virtual-router

#2782 add ipaddress input field to 'Add network to VM' form
  ui/scripts/instances.js
Labels: UI, enhancement

#2785 change dashboard events cursor to default to prevent user confusion
  ui/css/cloudstack3.css
Labels: UI

#2788 data table header cursor type and title
  ui/css/cloudstack3.css
  ui/scripts/ui/widgets/listView.js
Labels: UI

#2790 add height sizing to detail view so that it renders all detail items
  ui/css/cloudstack3.css
Labels: UI

#2766 kvm: Agent should not check if remaining memory on host is sufficient
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: kvm

#2794 vmware: reboot VR after mac updates
  server/src/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
  systemvm/debian/opt/cloud/bin/setup/router.sh
  ui/scripts/instances.js
  ui/scripts/system.js
Labels: virtual-router

#2776 Issue 2774: Changed the implementation of isVolumeOnManagedStorage(VolumeInfo) to…
  engine/storage/datamotion/src/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
  engine/storage/datamotion/test/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
Labels: managed-storage

#2800 tests: add unit tests for console proxy url
  core/src/test/java/com/cloud/info/ConsoleProxyInfoTest.java
Labels: enhancement

#2796 Fix some log messages that do not match with their function
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
  engine/schema/src/main/java/com/cloud/usage/dao/UsageDaoImpl.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetScalerControlCenterResource.java
  plugins/network-elements/opendaylight/src/main/java/org/apache/cloudstack/network/opendaylight/api/resources/Action.java
  plugins/network-elements/ovs/src/main/java/com/cloud/network/element/OvsElement.java
  plugins/network-elements/ovs/src/main/java/com/cloud/network/guru/OvsGuestNetworkGuru.java
  plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/OvsTunnelManagerImpl.java
  plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
  server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java
  server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/main/java/org/apache/cloudstack/ca/CAManagerImpl.java
Labels: enhancement

#2809 Backport Update DBCP version to 4.11
  developer/pom.xml
  engine/schema/src/com/cloud/upgrade/DatabaseCreator.java
  framework/db/pom.xml
  framework/db/src/com/cloud/utils/db/TransactionLegacy.java
  pom.xml
Labels: Backport

#2807 Remove UserVmDetailsDao duplicate field
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: Cleanup

#2808 Fix the problem at #1740 when it loads all snapshots in the primary storage
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDao.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImplTest.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImpl.java
Labels: enhancement

#2814 display translation labels as html instead of plain text
  ui/index.html
Labels: UI, waiting-for-reviewer, waiting-for-smoketest-results

#2798 Fix Div overlay problem when PopUp modal with error message is closed
  ui/scripts/ui/dialog.js
Labels: UI, bug

#2813 Remove class snapshot data factory test
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/VMSnapshotStrategyTest.java
  engine/storage/snapshot/src/test/java/src/SnapshotDataFactoryTest.java
Labels: Cleanup

#2091 CLOUDSTACK-8609: [VMware] VM is not accessible after migration across clusters
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: bug, vmware, waiting-for-reviewer

#2826 Add user information on the Event-View in the UI
  ui/scripts/events.js
Labels: UI, enhancement

#2832 Bigger partiton table for SVM & ambigous redirect bugfix
  tools/appliance/shar_cloud_scripts.sh
  tools/appliance/systemvmtemplate/http/preseed.cfg
  tools/appliance/systemvmtemplate/template.json
Labels: BLOCKER
