Repository apache/cloudstack, pull requests merged in 2018-12, with the labels that each got.

#3076 security: increase keystore setup/import timeout
  agent/src/com/cloud/agent/Agent.java
  core/src/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
Labels: kvm, security

#3005 Discover tags field on superclass of API responses
  plugins/api/discovery/src/org/apache/cloudstack/api/response/ApiDiscoveryResponse.java
  plugins/api/discovery/src/org/apache/cloudstack/api/response/ApiResponseResponse.java
  plugins/api/discovery/src/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
  plugins/api/discovery/test/org/apache/cloudstack/discovery/ApiDiscoveryTest.java
Labels: enhancement

#3080 kvm: Use 'ip route show default 0.0.0.0/0' to find the default gateway
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: kvm

#3085 server/test: Move test files to right location
  server/src/test/java/com/cloud/hypervisor/KVMGuruTest.java
  server/src/test/java/com/cloud/network/guru/DirectNetworkGuruTest.java
  server/src/test/java/com/cloud/resource/ResourceManagerImplTest.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
  server/src/test/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImplTest.java
  server/src/test/java/org/apache/cloudstack/agent/lb/algorithm/IndirectAgentLBRoundRobinAlgorithmTest.java
  server/src/test/java/org/apache/cloudstack/agent/lb/algorithm/IndirectAgentLBShuffleAlgorithmTest.java
  server/src/test/java/org/apache/cloudstack/agent/lb/algorithm/IndirectAgentLBStaticAlgorithmTest.java
Labels: management-server, unit-test

#3024 travis: fail fast if --with-marvin fails with nose
  tools/travis/before_install.sh
  tools/travis/script.sh
Labels: testing, travis

#2997 Allow KVM VM live migration with ROOT volume on file storage type
  api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
  api/src/main/java/com/cloud/vm/DiskProfile.java
  core/src/main/java/com/cloud/agent/api/MigrateCommand.java
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
  engine/storage/datamotion/src/main/resources/META-INF/cloudstack/storage/spring-engine-storage-datamotion-storage-context.xml
  engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java
  engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/MigrateKVMAsync.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCreateCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
Labels: kvm, local-storage, ready-for-merge

#3102 README: Ho ho ho!
  README.md
Labels: Not a problem

#3098 Add support for keyword in listSSHKeyPairs command search (#2920)
  server/src/com/cloud/server/ManagementServerImpl.java
Labels: UI, api, bug

#3026 Enhance bypass vlan overlap check
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkCmdByAdmin.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  ui/l10n/en.js
  ui/scripts/sharedFunctions.js
Labels: UI, enhancement

#3100 ipv6: Send userdata to Virtual Router if IPv6 is enabled
  server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
  server/src/test/java/com/cloud/network/element/VirtualRouterElementTest.java
Labels: ipv6, virtual-router

#3106 marvin: add missing test data for test_migration smoketest
  test/integration/smoke/test_service_offerings.py
  tools/marvin/marvin/config/test_data.py
Labels: marvin

#3095 Prevent corner case for infinite PrepareForMaintenance
  engine/components-api/src/com/cloud/resource/ResourceManager.java
  server/src/com/cloud/resource/ResourceManagerImpl.java
  server/test/com/cloud/resource/MockResourceManagerImpl.java
  server/test/com/cloud/resource/ResourceManagerImplTest.java
Labels: bug

#3107 Add api arg validator for create project api (#3097)
  api/src/main/java/org/apache/cloudstack/api/command/user/project/CreateProjectCmd.java
Labels: bug
