Repository apache/cloudstack, pull requests merged in 2018-05, with the labels that each got.

#2606 When creating a new account (via domain admin) it is possible to select “root admin” as the role for the new user
  api/src/main/java/org/apache/cloudstack/acl/RoleService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java
  server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
  server/src/test/java/org/apache/cloudstack/acl/RoleManagerImplTest.java
Labels: api, bug

#2608 API: move ostypeid from DB id to DB uuid
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
Labels: api, bug

#2622 CLOUDSTACK-10376: UI: Create VPC Offering does not show ConfigDrive a…
  ui/scripts/configuration.js
Labels: bug

#2612 [migrateVolume API method] Filter disk offerings based on target storage pool selected
  ui/scripts/autoscaler.js
  ui/scripts/configuration.js
  ui/scripts/sharedFunctions.js
  ui/scripts/storage.js
Labels: UI, enhancement

#2628 Create upgrade path from 4.9.3.1 to 4.11.1.0
  engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
Labels: BLOCKER

#2623 fixes #2611
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
Labels: BLOCKER, kvm

#2626 bionic: allow Ubuntu 18.04 to be added as KVM host
  debian/control
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStopCommandWrapper.java
  ui/scripts/system.js
Labels: kvm, packaging, upgrade

#2607 Allow changing disk offering of VMs' root volume during volume migration
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
Labels: enhancement, management-server

#2619 Remove "self-injection" of AccountManagerImpl
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
Labels: Cleanup

#2621 Backports for 4.11 branch
  api/src/com/cloud/configuration/Resource.java
  api/src/com/cloud/exception/UnavailableCommandException.java
  api/src/org/apache/cloudstack/acl/RoleService.java
  api/src/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java
  api/src/org/apache/cloudstack/api/command/admin/acl/RoleCmd.java
  api/src/org/apache/cloudstack/api/response/AccountResponse.java
  api/src/org/apache/cloudstack/api/response/DomainResponse.java
  api/src/org/apache/cloudstack/api/response/ProjectResponse.java
  api/src/org/apache/cloudstack/api/response/ResourceLimitAndCountResponse.java
  core/src/com/cloud/storage/template/IsoProcessor.java
  core/src/com/cloud/storage/template/OVAProcessor.java
  core/src/com/cloud/storage/template/Processor.java
  core/src/com/cloud/storage/template/QCOW2Processor.java
  core/src/com/cloud/storage/template/RawImageProcessor.java
  core/src/com/cloud/storage/template/TARProcessor.java
  core/src/com/cloud/storage/template/VhdProcessor.java
  core/src/com/cloud/storage/template/VmdkProcessor.java
  core/src/org/apache/cloudstack/storage/command/TemplateOrVolumePostUploadCommand.java
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/com/cloud/configuration/dao/ResourceCountDao.java
  engine/schema/src/com/cloud/configuration/dao/ResourceCountDaoImpl.java
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManager.java
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareStorageManager.java
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
  plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareSecondaryStorageResourceHandler.java
  plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageSubsystemCommandHandler.java
  plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
  server/src/com/cloud/api/query/dao/AccountJoinDaoImpl.java
  server/src/com/cloud/api/query/dao/DomainJoinDaoImpl.java
  server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java
  server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
  server/src/com/cloud/storage/StorageManagerImpl.java
  server/src/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/com/cloud/vm/UserVmManagerImpl.java
  server/src/org/apache/cloudstack/acl/RoleManagerImpl.java
  server/test/com/cloud/vm/UserVmManagerImplTest.java
  server/test/com/cloud/vm/UserVmManagerTest.java
  server/test/org/apache/cloudstack/acl/RoleManagerImplTest.java
  services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
  services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
  services/secondary-storage/server/src/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
  services/secondary-storage/server/src/org/apache/cloudstack/storage/template/UploadEntity.java
  test/integration/plugins/solidfire/TestCapacityManagement.py
  ui/scripts/storage.js
  ui/scripts/vpc.js
  utils/src/main/java/com/cloud/utils/DateUtil.java
  utils/src/main/java/com/cloud/utils/script/Script.java
  utils/src/test/java/com/cloud/utils/DateUtilTest.java
Labels: Backport

#2632 listostypes: Fixes #2529 return boolean than string in response
  api/src/org/apache/cloudstack/api/response/GuestOSResponse.java
  server/src/com/cloud/api/ApiResponseHelper.java
Labels: api

#2615 config-drive: support user data on L2 networks
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/orchestration/test/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
  server/src/com/cloud/network/NetworkModelImpl.java
  server/src/com/cloud/network/guru/GuestNetworkGuru.java
  ui/scripts/configuration.js
  ui/scripts/docs.js
Labels: config

#2508 CLOUDSTACK-9114: Reduce VR downtime during network restart
  api/src/com/cloud/network/Network.java
  api/src/com/cloud/network/NetworkProfile.java
  api/src/com/cloud/network/NetworkService.java
  api/src/com/cloud/network/vpc/Vpc.java
  api/src/org/apache/cloudstack/api/ApiConstants.java
  api/src/org/apache/cloudstack/api/command/user/network/RestartNetworkCmd.java
  api/src/org/apache/cloudstack/api/command/user/vpc/RestartVPCCmd.java
  api/src/org/apache/cloudstack/api/response/NetworkResponse.java
  engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/com/cloud/network/dao/NetworkDaoImpl.java
  engine/schema/src/com/cloud/network/dao/NetworkVO.java
  engine/schema/src/com/cloud/network/vpc/VpcVO.java
  server/src/com/cloud/api/ApiResponseHelper.java
  server/src/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
  server/src/com/cloud/network/NetworkServiceImpl.java
  server/src/com/cloud/network/element/VirtualRouterElement.java
  server/src/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/org/cloud/network/router/deployment/RouterDeploymentDefinition.java
  server/src/org/cloud/network/router/deployment/VpcRouterDeploymentDefinition.java
  server/test/com/cloud/vpc/MockNetworkManagerImpl.java
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
  systemvm/debian/opt/cloud/bin/setup/common.sh
  systemvm/debian/opt/cloud/bin/setup/postinit.sh
  systemvm/debian/opt/cloud/templates/keepalived.conf.templ
  ui/scripts/network.js
Labels: systemvm-template-change, upgrade, virtual-router

#2634 CLOUDSTACK-9184: Fixes #2631 VMware dvs portgroup autogrowth
  engine/schema/resources/META-INF/db/schema-41100to41110-cleanup.sql
  plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
  server/src/com/cloud/configuration/Config.java
  vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Labels: BLOCKER

#2635 router: Fixes #2544 run passwd server on dhcpserver IP on rVR
  systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
Labels: BLOCKER

#2646 Don't skip tests while packaging Centos7
  packaging/centos7/cloud.spec
Labels: packaging

#2645 config-drive: use hostname of VM instance of internal VM id
  api/src/com/cloud/network/NetworkModel.java
  engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
  server/src/com/cloud/network/NetworkModelImpl.java
  server/src/com/cloud/network/element/ConfigDriveNetworkElement.java
  server/src/com/cloud/vm/UserVmManagerImpl.java
  server/test/com/cloud/network/MockNetworkModelImpl.java
  server/test/com/cloud/network/element/ConfigDriveNetworkElementTest.java
  server/test/com/cloud/vpc/MockNetworkModelImpl.java
Labels: bug

#2638 agent: Fixes #2633 don't wait for pending tasks on reconnection
  agent/src/com/cloud/agent/Agent.java
Labels: kvm, ssvm

#2651 CLOUDSTACK-10290: Introduce option to have config drives on primary storage
  api/src/com/cloud/network/element/UserDataServiceProvider.java
  client/pom.xml
  core/src/com/cloud/agent/api/HandleConfigDriveIsoCommand.java
  engine/api/src/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/pom.xml
  engine/storage/configdrive/pom.xml
  engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDrive.java
  engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
  engine/storage/configdrive/test/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilderTest.java
  packaging/centos7/cloud.spec
  plugins/hypervisors/kvm/pom.xml
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtHandleConfigDriveCommandWrapper.java
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  server/pom.xml
  server/src/com/cloud/network/element/ConfigDriveNetworkElement.java
  server/src/com/cloud/vm/UserVmManagerImpl.java
  server/test/com/cloud/network/element/ConfigDriveNetworkElementTest.java
  services/secondary-storage/server/pom.xml
  services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Labels: Cleanup, config, kvm, primary-storage, secondary-storage

#2653 Generate MAC address if the MAC in command addNicToVirtualMachine is invalid
  server/src/com/cloud/vm/UserVmManagerImpl.java
  server/test/com/cloud/vm/UserVmManagerImplTest.java
Labels: bug

#2639 [CLOUDSTACK-10276] listVolumes not working when storage UUID is not a UUID
  api/src/org/apache/cloudstack/api/command/admin/volume/ListVolumesCmdByAdmin.java
  api/src/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
  server/src/com/cloud/api/query/QueryManagerImpl.java
Labels: api, bug

#2661 Make uploadSslCert a POST request instead of a GET
  ui/scripts/accounts.js
Labels: api, bug

#2667 CLOUDSTACK-10375: Don't create DefaultNuageVspSharedNetworkOfferingWithSGService
  plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManager.java
  plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManagerImpl.java
Labels: bug

#2663 server: Calculate fresh capacity per VM
  server/src/com/cloud/capacity/CapacityManagerImpl.java
Labels: bug

#2676 Fix two typos (from uanble to unable).
  plugins/hypervisors/hyperv/src/com/cloud/hypervisor/hyperv/resource/HypervDirectConnectResource.java
  vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java
Labels: enhancement

#2673 Fix test_configdrive.py and test_nuage_configdrive
  test/integration/component/test_configdrive.py
  test/integration/plugins/nuagevsp/test_nuage_configdrive.py
Labels: bug
