Repository apache/cloudstack, pull requests merged in 2018-09, with the labels that each got.

#2825 expunge if flag is set
  engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
Labels: bug

#2836 Volume snapshot recurring schedule not showing
  ui/index.html
Labels: BLOCKER, UI, waiting-for-reviewer

#2829 CLOUDSTACK-9473: storage pool capacity check when volume is resized or migrated
  engine/components-api/src/com/cloud/storage/StorageManager.java
  server/src/com/cloud/storage/StorageManagerImpl.java
  server/src/com/cloud/storage/VolumeApiServiceImpl.java
Labels: bug

#2761 Add managed storage pool constraints to MigrateWithVolume API method
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
Labels: bug, managed-storage, primary-storage

#2835 Fix Overlay issue in snapshot view
  ui/scripts/ui-custom/recurringSnapshots.js
Labels: UI, bug

#2773 CLOUDSTACK-10328: Add Secondary IPv6 address through API
  api/src/main/java/com/cloud/network/NetworkModel.java
  api/src/main/java/com/cloud/network/NetworkService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/AddIpToVmNicCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/RemoveIpFromVmNicCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/test/AddIpToVmNicTest.java
  engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java
  engine/schema/src/main/java/com/cloud/vm/dao/NicIpAliasDaoImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/NicSecondaryIpDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/NicSecondaryIpDaoImpl.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/network/Ipv6AddressManager.java
  server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
  server/src/test/java/com/cloud/api/ApiResponseHelperTest.java
  server/src/test/java/com/cloud/network/IpAddressManagerTest.java
  server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java
  server/src/test/java/com/cloud/network/MockNetworkModelImpl.java
  server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
  server/src/test/java/com/cloud/vpc/MockNetworkModelImpl.java
  ui/lib/jquery.validate.additional-methods.js
  ui/scripts/network.js
  utils/src/main/java/com/cloud/utils/net/NetUtils.java
  utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Labels: ipv6, kvm

#2799 systemvmtemplate: new 4.11.2 template and fixes
  engine/schema/resources/META-INF/db/schema-41110to41120-cleanup.sql
  engine/schema/resources/META-INF/db/schema-41110to41120.sql
  engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/com/cloud/upgrade/dao/Upgrade41100to41110.java
  engine/schema/src/com/cloud/upgrade/dao/Upgrade41110to41120.java
  systemvm/debian/opt/cloud/bin/setup/cloud-early-config
  systemvm/debian/opt/cloud/bin/setup/common.sh
  systemvm/debian/opt/cloud/bin/setup/postinit.sh
  systemvm/debian/opt/cloud/bin/setup/router.sh
  systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh
  tools/appliance/systemvmtemplate/scripts/apt_upgrade.sh
Labels: systemvm-template-change

#2840 Fix for Vmware full clones update
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/schema/resources/META-INF/db/schema-41110to41120.sql
  engine/schema/src/com/cloud/vm/UserVmCloneSettingVO.java
Labels: vmware, waiting-for-author

#2846 Fix PowerReportMissing for new VRs
  engine/orchestration/src/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
Labels: bug

#2833 Run diagnostics API UI integration for system VMs and VR
  api/src/main/java/com/cloud/event/EventTypes.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/diagnostics/RunDiagnosticsCmd.java
  server/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImpl.java
  ui/css/cloudstack3.css
  ui/l10n/en.js
  ui/scripts/system.js
Labels: UI

#2828 deb: Remove Ubuntu 14.04 LTS support and update DEB dependencies
  .travis.yml
  debian/cloudstack-agent.install
  debian/cloudstack-management.install
  debian/cloudstack-usage.install
  debian/control
  debian/rules
  packaging/build-deb.sh
  packaging/debian/cloudstack-agent.init
  packaging/debian/cloudstack-usage.init
  packaging/debian/init/cloud-management
Labels: kvm, packaging

#2852 Make networkofferingid required in migrateNetwork
  api/src/org/apache/cloudstack/api/command/admin/network/MigrateNetworkCmd.java
Labels: bug, networking

#2855 systemvm: export $TYPE before patching ssvm/cpvm
  engine/schema/src/com/cloud/upgrade/dao/Upgrade41110to41120.java
  systemvm/debian/opt/cloud/bin/setup/cloud-early-config
  systemvm/debian/opt/cloud/bin/setup/postinit.sh
  tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
Labels: BLOCKER, systemvm-template-change

#2859 agent: Fixes #2858 agent LB not working
  agent/src/com/cloud/agent/Agent.java
Labels: BLOCKER

#2743 CLOUDSTACK-10380: Fix startvm giving another pw after pw reset
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/com/cloud/vm/dao/UserVmDaoImpl.java
  engine/schema/src/org/apache/cloudstack/resourcedetail/ResourceDetailsDao.java
  engine/schema/src/org/apache/cloudstack/resourcedetail/ResourceDetailsDaoBase.java
  server/src/com/cloud/network/element/VirtualRouterElement.java
  server/src/com/cloud/vm/UserVmManagerImpl.java
  test/integration/component/test_configdrive.py
  test/integration/plugins/nuagevsp/nuageTestCase.py
  test/integration/plugins/nuagevsp/nuage_lib.py
  test/integration/plugins/nuagevsp/test_nuage_configdrive.py
  test/integration/plugins/nuagevsp/test_nuage_extra_dhcp.py
  test/integration/plugins/nuagevsp/test_nuage_internal_dns.py
  test/integration/plugins/nuagevsp/test_nuage_network_migration.py
  test/integration/plugins/nuagevsp/test_nuage_password_reset.py
  test/integration/plugins/nuagevsp/test_nuage_source_nat.py
  test/integration/plugins/nuagevsp/test_nuage_static_nat.py
  test/integration/plugins/nuagevsp/test_nuage_vpc_internal_lb.py
  test/integration/plugins/nuagevsp/test_nuage_vpc_network.py
  test/integration/plugins/nuagevsp/test_nuage_vsp_domain_template.py
  test/integration/plugins/nuagevsp/test_nuage_vsp_mngd_subnets.py
  tools/marvin/marvin/lib/base.py
  tools/marvin/marvin/lib/common.py
  tools/marvin/setup.py
Labels: bug
