Repository apache/cloudstack, pull requests merged in 2018-02, with the labels that each got.

#2421 CLOUDSTACK-10243: Do not use wait() on Python subprocess
  systemvm/debian/opt/cloud/bin/cs/CsHelper.py
Labels: virtual-router

#2420 CLOUDSTACK-10247: L2 network not shared on projects
  server/src/com/cloud/network/NetworkModelImpl.java
  server/src/com/cloud/network/NetworkServiceImpl.java
Labels: networking

#2441 CLOUDSTACK-10261: Libvirt metadata: only create one nuage-extension tag
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
Labels: bug, libvirt, networking

#2452 CLOUDSTACK-10285: Fix db upgrade failure for 4.10.0.0 users
  engine/schema/resources/META-INF/db/schema-41000to41100-cleanup.sql
  engine/schema/resources/META-INF/db/schema-41000to41100.sql
  engine/schema/resources/META-INF/db/schema-4930to41000-cleanup.sql
  engine/schema/resources/META-INF/db/schema-4930to41000.sql
Labels: upgrade

#2450 CLOUDSTACK-10282: firewall rules operation should be done with ip6tab…
  systemvm/debian/opt/cloud/bin/setup/postinit.sh
Labels: bug, ipv6, ready-for-merge, virtual-router

#2432 CLOUDSTACK-10294: PEP-8 fixes and enhancements to security_group.py
  scripts/vm/network/security_group.py
Labels: kvm, security-group

#2402 [CLOUDSTACK-10128] Simplify the search for host to execute command
  engine/schema/src/com/cloud/host/dao/HostDao.java
  engine/schema/src/com/cloud/host/dao/HostDaoImpl.java
  engine/schema/src/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
  engine/schema/src/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
  plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java
  plugins/hypervisors/xenserver/test/com/cloud/hypervisor/XenServerGuruTest.java
  requirements.txt
Labels: XenServer, bug, primary-storage

#2456 [CLOUDSTACK-10293] Single view network ACL rules listing
  ui/css/cloudstack3.css
  ui/l10n/ar.js
  ui/l10n/ca.js
  ui/l10n/de_DE.js
  ui/l10n/en.js
  ui/l10n/es.js
  ui/l10n/fr_FR.js
  ui/l10n/hu.js
  ui/l10n/it_IT.js
  ui/l10n/ja_JP.js
  ui/l10n/ko_KR.js
  ui/l10n/nb_NO.js
  ui/l10n/nl_NL.js
  ui/l10n/pl.js
  ui/l10n/pt_BR.js
  ui/l10n/ru_RU.js
  ui/l10n/zh_CN.js
  ui/scripts/ui/widgets/multiEdit.js
  ui/scripts/vpc.js
Labels: UI, enhancement

#2454 CLOUDSTACK-10283: Sudo to setup agent keystore, fail on host add failure
  agent/src/com/cloud/agent/Agent.java
  server/src/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Labels: kvm, security

#2443 [CLOUDSTACK-9338] ACS is not accounting resources of VMs with custom service offering properly
  engine/schema/src/main/java/com/cloud/configuration/dao/ResourceCountDao.java
  engine/schema/src/main/java/com/cloud/configuration/dao/ResourceCountDaoImpl.java
  server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
  test/integration/component/test_updateResourceCount.py
Labels: bug, management-server

#2464 [4.11] CLOUDSTACK-10299: UI: fix error in network listing in project mode
  ui/scripts/network.js
Labels: UI, bug

#2392 dateutil: constistency of tzdate input and output
  utils/src/main/java/com/cloud/utils/DateUtil.java
  utils/src/test/java/com/cloud/utils/DateUtilTest.java
Labels: api, bug
