Repository apache/cloudstack, pull requests merged in 2019-12, with the labels that each got.

#3617 [KVM] Agent LB Fix: Connections from disabled KVM host agents are refused
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentAttache.java
  server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
Labels: component:kvm, type:bug

#3740 Add support for ecdsa and ed25519 public keys.
  utils/src/main/java/com/cloud/utils/ssh/SSHKeysHelper.java
Labels: component:security, type:enhancement

#3745 Save SSH.PublicKey into user_vm_details regardless of password management.
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:security, type:bug

#3474 Enhance VM Statistics to add more detail
  ui/scripts/instances.js
Labels: component:UI, type:enhancement

#3546 [FIX] Rethrow takeVMSnapshot() exception
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
Labels: component:management-server, type:bug

#3615 Handle Ceph/RBD snapshot delete
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategy.java
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategyTest.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
Labels: component:ceph, type:bug

#3746 Fix OS category for some OS-es added in 4.13
  engine/schema/src/main/resources/META-INF/db/schema-41300to41400.sql
Labels: component:database, type:bug

#3738 Load Average for KVM
  api/src/main/java/com/cloud/host/HostStats.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
  core/src/main/java/com/cloud/agent/api/GetHostStatsAnswer.java
  core/src/main/java/com/cloud/agent/api/HostStatsEntry.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetHostStatsCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/CPUStat.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java
  server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Labels: component:api, component:kvm, status:ready-for-merge, type:enhancement

#3737 Add missing HA config keys
  engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
  server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
Labels: component:management-server, status:ready-for-merge, type:enhancement

#3371 Fix virtual template size for managed storage for KVM / refactor cloud-install-sys-tmplt
  debian/control
  packaging/centos7/cloud.spec
  scripts/storage/secondary/cloud-install-sys-tmplt
  scripts/storage/secondary/createtmplt.sh
Labels: component:managed-storage, component:templates, status:ready-for-merge, type:bug

#3425 Better tracking host maintanence and handling of migration jobs
  api/src/main/java/com/cloud/resource/ResourceState.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/host/PrepareForMaintenanceCmd.java
  engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
  engine/components-api/src/main/java/com/cloud/resource/ResourceManager.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/EngineHostVO.java
  engine/schema/src/main/java/com/cloud/host/HostVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41300to41400-cleanup.sql
  server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
  server/src/main/java/com/cloud/ha/dao/HighAvailabilityDao.java
  server/src/main/java/com/cloud/ha/dao/HighAvailabilityDaoImpl.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java
  server/src/test/java/com/cloud/resource/MockResourceManagerImpl.java
  server/src/test/java/com/cloud/resource/ResourceManagerImplTest.java
  test/integration/smoke/test_host_maintenance.py
  ui/scripts/metrics.js
  ui/scripts/system.js
Labels: component:management-server, type:enhancement

#3772 Revert of the "Revert "Fix virtual template size for managed storage for KVM / refactor cloud-install-sys-tmplt""
  debian/control
  packaging/centos7/cloud.spec
  scripts/storage/secondary/cloud-install-sys-tmplt
  scripts/storage/secondary/createtmplt.sh
Labels: component:kvm, component:managed-storage, component:templates

#3765 Honour promiscuous mode from networkOffering
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Labels: component:networking, component:vmware, type:bug

#3767 create template from snapshot regression (partly reverted)
  ui/scripts/sharedFunctions.js
  ui/scripts/storage.js
Labels: component:UI, status:ready-for-merge, type:bug

#3754 Once again allow a VM to be on multiple networks from VPCs
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:networking, component:vpc, status:ready-for-merge, type:bug

#3747 convert protocal names to be found as labels
  ui/scripts/network.js
Labels: component:UI, status:ready-for-merge, type:bug

#3733 filter hosts to query on zone wide storage
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:management-server, status:ready-for-merge, type:bug

#3729 config: add isdynamic flag in configuration response
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/ConfigurationResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  ui/scripts/globalSettings.js
Labels: component:management-server, type:bug

#3755 Added zone check for attach iso
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
Labels: component:api, type:bug

#3775 New feature: Acquire specific public IP for network
  api/src/main/java/com/cloud/network/NetworkService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/address/AssociateIPAddrCmd.java
  engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java
  plugins/network-elements/cisco-vnmc/src/main/java/com/cloud/network/element/CiscoVnmcElement.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
  test/integration/component/test_acquire_specified_public_ip.py
  tools/marvin/marvin/lib/base.py
  ui/scripts/network.js
Labels: component:networking, type:enhancement

#3715 break session only on illegal origin
  api/src/main/java/com/cloud/exception/OriginDeniedException.java
  server/src/main/java/com/cloud/api/ApiServer.java
  utils/src/main/java/com/cloud/utils/SerialVersionUID.java
Labels: component:api, type:bug, type:regression
