Repository apache/cloudstack, pull requests merged in 2019-04, with the labels that each got.

#3249 [CLOUDSTACK-10406] fix bugs that may cause program crash, change mkdir to mkdirs
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
Labels: bug

#3266 packaging: don't skip unit tests while building packages
  packaging/centos7/cloud.spec
Labels: build, packaging

#3254 utils: removed port check for url validation (#2802)
  utils/src/main/java/com/cloud/utils/UriUtils.java
Labels: api, bug, templates

#3257 server: fix for vm snapshot search (#3208)
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  ui/scripts/storage.js
Labels: UI, api, bug

#3269 packaging: systemctl daemon-reload after agent install or upgrade
  packaging/centos7/cloud.spec
Labels: agent, packaging

#3233 ui: don't ignore ''mine" when listing "all" templates in projects
  ui/scripts/templates.js
Labels: UI, bug, ready-for-merge

#3212 storage: publish delete usage event for snapshot deletion
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
Labels: bug, usage-server

#3256 ui: show complete domain for accounts (#2994)
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/AccountResponse.java
  server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java
  ui/scripts/accounts.js
Labels: UI, api

#3225 ui: fix computer diagram css margin that blocks down arrow
  ui/css/cloudstack3.css
Labels: UI

#3173 Mock Scanner, instead of scan the computer running the test.
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVifDriverTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtNetworkElementCommandWrapperTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReplugNicCommandWrapperTest.java
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
Labels: bug

#3183 Improvements after jquery update
  ui/css/cloudstack3.css
  ui/index.html
  ui/lib/jquery-ui/css/jquery-ui.css
  ui/scripts/configuration.js
  ui/scripts/roles.js
  ui/scripts/system.js
  ui/scripts/ui-custom/instanceWizard.js
  ui/scripts/ui/widgets/toolTip.js
  ui/scripts/vpc.js
  ui/scripts/zoneWizard.js
Labels: UI, bug

#3289 Update to latest InfluxDB (2.15), adding support to Batch Mode
  pom.xml
  server/pom.xml
  server/src/main/java/com/cloud/server/StatsCollector.java
Labels: enhancement

#3302 server: sync templates on adding new secondary storage
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: bug
