Repository apache/cloudstack, pull requests merged in 2019-01, with the labels that each got.

#3101 kvm: Set amount of queues for Virtio SCSI driver to vCPU of Instance
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
Labels: kvm, libvirt

#3078 Add influxdb to statscollector
  core/pom.xml
  core/src/main/java/com/cloud/agent/api/HostStatsEntry.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntry.java
  server/pom.xml
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/test/java/com/cloud/server/StatsCollectorTest.java
  utils/src/main/java/org/apache/cloudstack/utils/graphite/GraphiteClient.java
Labels: kvm, new-feature

#3070 kvm: Refactory VXLAN script and add IPv6 support
  scripts/vm/network/vnet/modifyvxlan.sh
Labels: ipv6, kvm, vxlan

#1499 Remove unused "umount" method in NfsSecondaryStorageResource
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Labels: Cleanup

#3124 Delete blank java file 'CopyTemplateToPrimaryStorageAnswer.java'
  api/src/main/java/com/cloud/agent/api/storage/CopyTemplateToPrimaryStorageAnswer.java
Labels: Cleanup

#3115 Fix network GC error that's failing a smoketests on master
  engine/schema/src/main/java/com/cloud/offerings/NetworkOfferingVO.java
Labels: bug, travis

#3128 Extend PR#2535 to enable remote debugging for CentOS63
  packaging/centos63/cloud-management.rc
  packaging/centos63/cloud-usage.rc
  packaging/systemd/cloudstack-management.default
Labels: enhancement

#3129 Fix “test_nic_secondaryip_add_remove” test
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: BLOCKER, bug

#3099 Add resource UUID instead of resource id in resourcedetails api (#2527)
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: api, enhancement

#3113 kvm: Security Group enhancements and refactor old code
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  scripts/vm/network/security_group.py
Labels: ipv6, kvm, security-group

#3069 Update jquery and related libraries
  ui/index.html
  ui/lib/flot/jquery.colorhelpers.js
  ui/lib/flot/jquery.flot.crosshair.js
  ui/lib/flot/jquery.flot.fillbetween.js
  ui/lib/flot/jquery.flot.image.js
  ui/lib/flot/jquery.flot.js
  ui/lib/flot/jquery.flot.navigate.js
  ui/lib/flot/jquery.flot.pie.js
  ui/lib/flot/jquery.flot.resize.js
  ui/lib/flot/jquery.flot.selection.js
  ui/lib/flot/jquery.flot.stack.js
  ui/lib/flot/jquery.flot.symbol.js
  ui/lib/flot/jquery.flot.threshold.js
  ui/lib/jquery-ui/js/jquery-ui.js
  ui/lib/jquery.js
  ui/lib/jquery.validate.additional-methods.js
  ui/lib/jquery.validate.js
  ui/modules/vpc/vpc.js
  ui/scripts/cloudStack.js
  ui/scripts/network.js
  ui/scripts/sharedFunctions.js
  ui/scripts/ui-custom/accountsWizard.js
  ui/scripts/ui-custom/enableStaticNAT.js
  ui/scripts/ui-custom/instanceWizard.js
  ui/scripts/ui-custom/physicalResources.js
  ui/scripts/ui-custom/pluginListing.js
  ui/scripts/ui-custom/projects.js
  ui/scripts/ui-custom/recurringSnapshots.js
  ui/scripts/ui-custom/regions.js
  ui/scripts/ui-custom/uploadVolume.js
  ui/scripts/ui-custom/vpc.js
  ui/scripts/ui-custom/zoneWizard.js
  ui/scripts/ui/core.js
  ui/scripts/ui/dialog.js
  ui/scripts/ui/events.js
  ui/scripts/ui/widgets/cloudBrowser.js
  ui/scripts/ui/widgets/dataTable.js
  ui/scripts/ui/widgets/detailView.js
  ui/scripts/ui/widgets/listView.js
  ui/scripts/ui/widgets/multiEdit.js
  ui/scripts/ui/widgets/notifications.js
  ui/scripts/ui/widgets/toolTip.js
  ui/scripts/ui/widgets/treeView.js
  ui/scripts/vpc.js
  ui/tests/test.widget.listView.js
Labels: UI

#3077 ipv6: Calculate IPv6 address instead of fetching one from a pool
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/network/Ipv6AddressManager.java
  server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java
  server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
  server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java
Labels: advanced-networking, ipv6

#3132 changed column fingerprint from varchar(62) to text #3123
  engine/schema/src/main/resources/META-INF/db/schema-41120to41200.sql
Labels: enhancement

#3136 ipv6: Do not allow Secondary IPv6 addresses to be EUI-64
  server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java
  server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java
  utils/src/main/java/com/cloud/utils/net/NetUtils.java
  utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Labels: enhancement, ipv6

#3125 IP address acquired with associate ip address is marked as source nat
  api/src/main/java/org/apache/cloudstack/api/command/user/address/AssociateIPAddrCmd.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/test/java/com/cloud/network/IpAddressManagerTest.java
  test/integration/component/test_tags.py
  test/integration/smoke/test_network.py
  test/integration/smoke/test_portforwardingrules.py
Labels: enhancement

#2795 kvm: Properly report available memory to Management Server
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetHostStatsCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/MemStat.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
Labels: kvm

#3143 Fix some LGTM alerts
  api/src/main/java/com/cloud/deploy/DeployDestination.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/resource/HypervDirectConnectResource.java
  plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorResource.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/ApiServer.java
Labels: Cleanup, enhancement

#3058 CLOUDSTACK-3049: update dynamic role for an account
  .dockerignore
  api/src/main/java/org/apache/cloudstack/api/command/admin/account/UpdateAccountCmd.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/test/java/com/cloud/user/AccountManagerImplTest.java
  test/integration/smoke/test_accounts.py
  tools/docker/Dockerfile.smokedev
  tools/docker/docker_run_tests.sh
  tools/marvin/marvin/lib/base.py
Labels: enhancement

#3139 packaging: management default file cleanup
  client/conf/java.security.ciphers.in
  packaging/systemd/cloudstack-management.default
Labels: Cleanup, management-server

#3112 network: Offerings do not have to have Security Grouping enabled
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
  server/src/test/java/com/cloud/network/guru/DirectNetworkGuruTest.java
Labels: kvm, security-group, vxlan

#3149 Fix UI bug: Create Network Offering Popup has no fields
  ui/scripts/configuration.js
Labels: BLOCKER, UI, bug
