Repository apache/cloudstack, pull requests merged in 2019-11, with the labels that each got.

#3658 client: fix for jetty session timeout
  client/src/main/java/org/apache/cloudstack/ServerDaemon.java
Labels: component:management-server, type:bug

#3620 Small additional NuageVsp cleanups (#3146)
  test/integration/component/test_configdrive.py
  tools/apidoc/gen_toc.py
  ui/l10n/ar.js
  ui/l10n/ca.js
  ui/l10n/de_DE.js
  ui/l10n/es.js
  ui/l10n/fr_FR.js
  ui/l10n/hu.js
  ui/l10n/it_IT.js
  ui/l10n/ja_JP.js
  ui/l10n/ko_KR.js
  ui/l10n/nb_NO.js
  ui/l10n/nl_NL.js
  ui/l10n/pl.js
  ui/l10n/pt_BR.js
  ui/l10n/ru_RU.js
  ui/l10n/zh_CN.js
  ui/scripts/configuration.js
  ui/scripts/ui-custom/zoneWizard.js
Labels: component:UI, type:Cleanup

#3623 kvm: Use 'ip' instead of 'brctl'
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
  scripts/vm/network/vnet/modifyvlan.sh
Labels: component:kvm, component:networking

#3666 snapshot failure diagnostics unhidden
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
Labels: type:Cleanup, type:enhancement

#3644 IoT/ARM64 support: allow cloudstack-agent on Raspberry Pi 4 (armv8) to use kvm acceleration
  agent/conf/agent.properties
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtCapXMLParser.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Labels: component:kvm, type:new-feature

#3616 Reduce verbosity of Async Job Manager log messages
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
Labels: component:management-server, type:enhancement

#3612 systemvm: for ip route show command don't use the throw command
  systemvm/debian/opt/cloud/bin/cs/CsRoute.py
Labels: component:virtual-router, type:bug

#3668 storage: don't select an SSVM that is removed
  engine/storage/src/main/java/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java
Labels: component:secondary-storage, type:bug

#3605 fix issue #3590 'Revert Ceph/RBD Snapshot'
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapper.java
Labels: component:ceph, component:kvm, type:bug

#3632 add class cleanup method
  test/integration/plugins/test_quota.py
Labels: type:Cleanup, type:bug

#3678 vpc: fix acl rule with protocol number is not applied correctly in vpc vr
  core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/SetNetworkAclConfigItem.java
Labels: component:virtual-router, type:bug

#3650 Add support for vSphere Web SDK 6.7 installation in install-non-oss.sh
  deps/install-non-oss.sh
Labels: component:build, component:vmware, type:Documentation, type:bug

#3630 New BuildRequires for CentOS 7: python-setuptools
  packaging/centos7/cloud.spec
Labels: component:packaging, type:bug

#3653 Fix VR creation issue while creating VM on shared network using PVLAN
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Labels: component:advanced-networking, type:bug

#3636 kvm: fix issue that network rules for secondary IPs are not applied
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: component:kvm, component:networking, type:bug

#3635 server: acquire IPv4 address when add secondary IP to nic if IP is not specified
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: component:networking, type:bug

#3703 increase width of field in UI
  ui/css/cloudstack3.css
Labels: component:UI, type:bug

#3704 utils: use iproute to get default network interface
  debian/control
  packaging/centos7/cloud.spec
  utils/src/main/java/com/cloud/utils/net/NetUtils.java
Labels: component:networking, type:bug

#3640 consoleproxy: Enable console for vms in Stopping/Migrating state
  server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  ui/scripts/instances.js
  ui/scripts/system.js
Labels: component:console-proxy, type:enhancement

#3723 a conditional to prevent creation of a field
  ui/scripts/sharedFunctions.js
  ui/scripts/storage.js
Labels: component:UI, type:bug

#3669 server: Fix resource count of primary storage/volume because of Expunged volumes
  engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
Labels: component:management-server, type:bug
