Repository apache/cloudstack, pull requests merged in 2019-03, with the labels that each got.

#3197 Fix XenServer Security Groups 'vmops' script
  core/src/main/java/com/cloud/agent/api/SecurityGroupRulesCmd.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixMigrateCommandWrapper.java
  plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixMigrateCommandWrapperTest.java
  scripts/vm/hypervisor/xenserver/vmops
  scripts/vm/hypervisor/xenserver/xcposs/vmops
  ui/scripts/network.js
  ui/scripts/sharedFunctions.js
Labels: BLOCKER, XenServer, advanced-networking, bug, security-group

#3210 systemd: Fix -Dpid arg passing to systemd usage service
  packaging/systemd/cloudstack-usage.default
  packaging/systemd/cloudstack-usage.service
  usage/src/com/cloud/usage/UsageServer.java
Labels: BLOCKER, usage-server

#3151 api: rename ListUsageRecords file name to ListUsageRecordsCmd
  api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java
  api/src/main/java/org/apache/cloudstack/usage/UsageService.java
  api/src/test/java/org/apache/cloudstack/api/command/test/UsageCmdTest.java
  server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/usage/UsageServiceImpl.java
Labels: Cleanup

#3158 Allow users of all types to create L2 networks
  server/src/com/cloud/network/NetworkServiceImpl.java
  ui/scripts/network.js
  ui/scripts/sharedFunctions.js
Labels: UI

#3211 ui: remove CA certificate button from UI
  ui/index.html
  ui/scripts/ui-custom/ca.js
Labels: UI

#3165 debian: cleanup commons-daemon no longer needed by agent
  debian/control
Labels: Cleanup

#3160 Add start button for multiple instances in list view
  ui/scripts/instances.js
Labels: UI

#3161 Fix behavior of multiselect in list view
  ui/scripts/ui/widgets/listView.js
Labels: UI, bug

#2869 Fix some Marvin smoke tests
  test/integration/smoke/test_deploy_virtio_scsi_vm.py
  test/integration/smoke/test_hostha_kvm.py
  test/integration/smoke/test_vm_life_cycle.py
  tools/marvin/marvin/lib/base.py
Labels: testing

#3236 schema: add empty DB upgrade path from 4.12.0.0 to 4.13.0.0
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41200to41300.java
  engine/schema/src/main/resources/META-INF/db/schema-41200to41300-cleanup.sql
  engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
Labels: database

#3238 client: don't disable TLSv1, TLSv1.1 by default that breaks VMware env
  client/conf/java.security.ciphers.in
Labels: management-server, security

#3247 Make the API documentation version not *hardcoded* to v4.9.0
  tools/apidoc/build-apidoc.sh
  tools/apidoc/generatecommands.xsl
  tools/apidoc/generatetoc_header.xsl
  tools/apidoc/pom.xml
Labels: Documentation

#3214 ui: use executable template filter for users
  ui/scripts/instances.js
Labels: UI
