Repository apache/cloudstack, pull requests merged in 2019-06, with the labels that each got.

#3368 [WIP DO NOT MERGE] server: fix public IP addresses filtering
  api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: UI, bug

#3346 Fix template size for managed storage / refactor cloud-install-sys-tmplt and createtmplt.sh
  scripts/storage/secondary/cloud-install-sys-tmplt
  scripts/storage/secondary/createtmplt.sh
Labels: bug, managed-storage, templates

#3310 Fix removing static NAT rules with Juniper SRX
  plugins/network-elements/juniper-srx/src/com/cloud/network/resource/JuniperSrxResource.java
Labels: bug

#3351 Have persistent DHCP leases file on VRs and cleanup /etc/hosts on VM deletion
  api/src/com/cloud/network/element/DhcpServiceProvider.java
  core/src/com/cloud/agent/api/routing/DhcpEntryCommand.java
  core/src/com/cloud/agent/resource/virtualnetwork/VRScripts.java
  core/src/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
  core/src/com/cloud/agent/resource/virtualnetwork/facade/DhcpEntryConfigItem.java
  core/src/com/cloud/agent/resource/virtualnetwork/model/VmDhcpConfig.java
  engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  plugins/hypervisors/baremetal/src/com/cloud/baremetal/networkservice/BaremetalDhcpElement.java
  plugins/network-elements/juniper-contrail/src/org/apache/cloudstack/network/contrail/management/ContrailElementImpl.java
  plugins/network-elements/nuage-vsp/src/com/cloud/network/element/NuageVspElement.java
  server/src/com/cloud/network/element/VirtualRouterElement.java
  server/src/com/cloud/network/router/CommandSetupHelper.java
  server/src/com/cloud/network/rules/DhcpEntryRules.java
  server/src/com/cloud/vm/UserVmManagerImpl.java
  server/src/org/apache/cloudstack/network/topology/AdvancedNetworkTopology.java
  server/src/org/apache/cloudstack/network/topology/AdvancedNetworkVisitor.java
  server/src/org/apache/cloudstack/network/topology/BasicNetworkTopology.java
  server/src/org/apache/cloudstack/network/topology/BasicNetworkVisitor.java
  server/src/org/apache/cloudstack/network/topology/NetworkTopology.java
  server/test/com/cloud/vpc/MockNetworkManagerImpl.java
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
  systemvm/debian/opt/cloud/bin/cs_dhcp.py
Labels: bug, dhcp, virtual-router

#2995 KVM: Improvements on upload direct download certificates
  agent/src/com/cloud/agent/Agent.java
  api/src/org/apache/cloudstack/api/command/admin/direct/download/UploadTemplateDirectDownloadCertificateCmd.java
  core/src/org/apache/cloudstack/agent/directdownload/SetupDirectDownloadCertificateCommand.java
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetupDirectDownloadCertificateCommandWrapper.java
  server/src/com/cloud/server/ManagementServerImpl.java
  server/src/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
  server/test/org/apache/cloudstack/direct/download/DirectDownloadManagerImplTest.java
  test/integration/smoke/test_direct_download.py
Labels: component:templates, kvm

#3370 ssvm: apply MTU value on storage/management nic if available
  services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Labels: bug, component:ssvm

#3194 Suspending a VM before snapshot deletion (see PR #3193)
  plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  ui/l10n/en.js
Labels: bug

#3366 Fix rule duplication with static NAT rules
  systemvm/debian/opt/cloud/bin/configure.py
Labels: bug, component:virtual-router

#3373 router: support multi-homed VMs in VPC
  server/src/com/cloud/network/element/VirtualRouterElement.java
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
  systemvm/debian/opt/cloud/bin/cs_dhcp.py
Labels: Severity:BLOCKER, bug, component:virtual-router

#2913 Deactivate ehcache
  client/conf/ehcache.xml.in
  engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml
Labels: type:enhancement

#3367 ui: added missing hypervisor options for upload template
  ui/scripts/templates.js
Labels: component:UI, type:bug, type:enhancement

#3215 [WIP DO NOT MERGE] storage: post process locally uploaded multi-disk ova template
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/TemplateService.java
  engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/datastore/ObjectInDataStoreManagerImpl.java
  server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java
Labels: component:vmware, status:Work-in-Progress

#3075 KVM: Prevent regenerating keystore on provisionCertificate API
  api/src/org/apache/cloudstack/api/command/admin/direct/download/UploadTemplateDirectDownloadCertificateCmd.java
  scripts/util/keystore-cert-import
  scripts/util/keystore-setup
  server/src/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
Labels: component:kvm

#3308 Console Proxy: Ignore META key mask if control was pressed
  systemvm/agent/js/ajaxviewer.js
Labels: component:UI, component:console-proxy, type:bug

#3329 Fix: Migration target has no matching tags
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
Labels: component:primary-storage, type:bug

#3381 schema: add 4.11.2 to 4.11.3 systemvmtemplate upgrade path
  engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/com/cloud/upgrade/dao/Upgrade41110to41120.java
  engine/schema/src/com/cloud/upgrade/dao/Upgrade41120to41130.java
Labels: component:database, component:migration, component:mysql, component:upgrade

#3372 Add to listRouters response the scriptsversion
  server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
Labels: component:api, type:bug

#3398 server: save GUID for KVM cluster
  server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Labels: component:kvm, type:bug

#3394 cloudstack: fix forward merge issues
  engine/storage/configdrive/src/test/java/org/apache/cloudstack/storage/configdrive/ConfigDriveTest.java
  plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessorTest.java
  plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/ldap/ADLdapUserManagerImplTest.java
  plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/ldap/LdapAuthenticatorTest.java
  server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java
Labels: type:Cleanup, type:bug

#3382 ui: fix instance and functionality
  ui/scripts/instances.js
  ui/scripts/ui/dialog.js
  ui/scripts/ui/widgets/listView.js
Labels: component:UI, type:bug

#3395 ui: adaptations
  ui/css/cloudstack3.css
  ui/css/src/scss/cloudstack3.scss
  ui/css/src/scss/components/blocking-overlay.scss
  ui/css/src/scss/components/dashboard.scss
  ui/css/src/scss/components/list-view.scss
  ui/css/src/scss/components/multi-wizzard.scss
  ui/css/src/scss/components/quick-view-tooltip.scss
Labels: component:UI, type:bug

#3390 Add more info for creating volume snapshots
  api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/test/CreateSnapshotCmdTest.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java
  ui/scripts/storage.js
Labels: component:UI, component:api, type:enhancement

#3386 Fix labels broken by translation code
  ui/index.html
Labels: component:UI, type:bug

#3403 ui: Fix quick view tooltip title on multiselect list views
  ui/scripts/ui/widgets/listView.js
Labels: component:UI, type:bug

#3391 ui: fix for disk offering quickview details, actions
  ui/scripts/configuration.js
Labels: component:UI, type:bug

#3405 kvm: fix qemu hook race condition
  agent/bindir/libvirtqemuhook.in
Labels: component:kvm, type:bug

#3407 Fix quick view tooltip loading overlay offset
  ui/css/cloudstack3.css
  ui/css/src/scss/components/quick-view-tooltip.scss
Labels: component:UI, type:bug

#3384 Minor: Add .vscode to .gitignore
  .gitignore
Labels: type:Cleanup

#3242 server: add support for sorting zones in UI/API
  api/src/main/java/com/cloud/dc/DataCenter.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/zone/UpdateZoneCmd.java
  api/src/main/java/org/apache/cloudstack/query/QueryService.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/EngineDataCenterVO.java
  engine/schema/src/main/java/com/cloud/dc/DataCenterVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/vo/DataCenterJoinVO.java
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  ui/scripts/cloudStack.js
  ui/scripts/sharedFunctions.js
  ui/scripts/system.js
Labels: component:UI, component:api

#3234 api: Set network name as part of the network usage response
  api/src/main/java/org/apache/cloudstack/api/response/UsageRecordResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: component:api, component:usage-server

#3344 server: return usage description with resource names and UUIDs
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/ResponseGenerator.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java
  api/src/main/java/org/apache/cloudstack/usage/UsageTypes.java
  framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaTypes.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: component:usage-server

#3219 server: publish volume resize event for volumes
  engine/schema/src/main/java/com/cloud/event/UsageEventVO.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/storage/listener/VolumeStateListener.java
  usage/src/main/java/com/cloud/usage/parser/VolumeUsageParser.java
Labels: component:usage-server

#3414 Increase z-index for install-wizard step
  ui/css/cloudstack3.css
  ui/css/src/scss/components/install-wizzard.scss
Labels: component:UI, type:bug, type:regression

#3415 Fix interval descrption
  server/src/main/java/com/cloud/configuration/Config.java
Labels: type:Documentation

#3413 vmware: add support for VMware 6.7
  engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
  pom.xml
Labels: component:vmware

#3365 KVM: DPDK live migrations
  api/src/main/java/com/cloud/agent/api/to/DpdkTO.java
  api/src/main/java/com/cloud/agent/api/to/NicTO.java
  core/src/main/java/com/cloud/agent/api/MigrateCommand.java
  core/src/main/java/com/cloud/agent/api/PrepareForMigrationAnswer.java
  core/src/main/java/com/cloud/agent/api/StopCommand.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/dpdk/DpdkDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/dpdk/DpdkDriverImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStopCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/dpdk/DpdkDriverTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
  server/src/main/java/com/cloud/hypervisor/KVMGuru.java
  server/src/main/java/com/cloud/hypervisor/kvm/dpdk/DPDKHelperImpl.java
  server/src/main/java/com/cloud/hypervisor/kvm/dpdk/DpdkHelper.java
  server/src/main/java/com/cloud/hypervisor/kvm/dpdk/DpdkHelperImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/resources/META-INF/cloudstack/core/spring-server-core-misc-context.xml
  server/src/test/java/com/cloud/hypervisor/KVMGuruTest.java
  server/src/test/java/com/cloud/hypervisor/kvm/dpdk/DPDKHelperImplTest.java
  server/src/test/java/com/cloud/hypervisor/kvm/dpdk/DpdkHelperImplTest.java
Labels: component:dpdk, component:kvm, component:migration, component:openvswitch

#3406 Add new way to create a volume snapshot from instance quick view tooltip
  ui/css/cloudstack3.css
  ui/css/src/scss/components/action-icons.scss
  ui/l10n/de_DE.js
  ui/l10n/en.js
  ui/scripts/docs.js
  ui/scripts/instances.js
Labels: component:UI, type:new-feature

#3423 api: Fix API argument documentation to list supported protocols
  api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/CreateLoadBalancerRuleCmd.java
Labels: type:Documentation

#3268 Support sort_key for vpc_offerings table
  api/src/main/java/com/cloud/network/vpc/VpcProvisioningService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/UpdateVPCOfferingCmd.java
  engine/schema/src/main/java/com/cloud/network/vpc/VpcOfferingVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
Labels: component:UI, component:api

#3418 server: fix potential NPE while ldap authentication
  plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
  plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapAuthenticator.java
  server/src/main/java/com/cloud/user/AccountManager.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
Labels: component:LDAP, type:bug

#3126 Improve System VM startup and memory usage
  systemvm/debian/etc/apache2/conf-enabled/mods-enabled/mpm_event.conf
  systemvm/debian/etc/cron.daily/clear_cache
  systemvm/debian/etc/cron.hourly/clear_cache
  systemvm/debian/etc/sysctl.conf
  systemvm/debian/etc/vmware-tools/tools.conf
  systemvm/debian/lib/systemd/system/baremetal-vr.service
  systemvm/debian/lib/systemd/system/cloud.service
  systemvm/debian/lib/systemd/system/hyperv-daemons.hv-fcopy-daemon.service
  systemvm/debian/lib/systemd/system/hyperv-daemons.hv-kvp-daemon.service
  systemvm/debian/lib/systemd/system/hyperv-daemons.hv-vss-daemon.service
  systemvm/debian/lib/systemd/system/open-vm-tools.service
  systemvm/debian/lib/systemd/system/xe-daemon.service
  systemvm/debian/opt/cloud/bin/setup/bootstrap.sh
  systemvm/debian/opt/cloud/bin/setup/consoleproxy.sh
  systemvm/debian/opt/cloud/bin/setup/postinit.sh
  systemvm/debian/opt/cloud/bin/setup/secstorage.sh
  tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
Labels: systemvm-template-change

#3422 Fix hostname is localhost in some VRs
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
Labels: component:virtual-router, type:bug

#3420 ssvm: use secstorage.ssl.cert.domain as hostname if it does not start with '*' when upload a template or volume from local
  utils/src/main/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtil.java
Labels: component:secondary-storage, type:bug

#3419 console-proxy: fix potential NPE condition
  core/src/main/java/com/cloud/info/ConsoleProxyInfo.java
Labels: Severity:Critical, component:console-proxy

#3424 KVM Volumes: Limit migration of volumes within the same storage pool.
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:kvm, type:bug

#3259 server: export granular volume bytes and iops metrics
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixGetVmDiskStatsCommandWrapper.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/VmMetricsResponse.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/VolumeMetricsResponse.java
  server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/scripts/metrics.js
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
Labels: component:primary-storage, component:vmware

#3429 Update config file with tables that users can see
  ui/config.js
Labels: component:UI, type:Cleanup

#3427 engine/schema: add guest-os support and mappings for XenServer 7.6
  engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
Labels: component:XenServer

#3431 Readd custom css
  ui/css/custom.css
  ui/css/src/scss/cloudstack3.scss
  ui/css/src/scss/custom.scss
  ui/css/src/scss/custom/custom.scss
  ui/index.html
Labels: component:UI, type:bug

#3441 Bug fix for distinting between string and map type tags in forms
  ui/scripts/ui/dialog.js
Labels: component:UI

#3438 ui: fix LB protocol bug
  ui/l10n/en.js
  ui/scripts/network.js
Labels: component:UI, type:bug

#3436 debian: install `file` as cloudstack-management dependency
  debian/control
Labels: component:packaging

#3421 RvR: VPC redundant vrs run on same hypervisor
  server/src/com/cloud/network/router/NetworkHelperImpl.java
Labels: component:vpc, type:bug
