Repository apache/cloudstack, pull requests merged in 2020-02, with the labels that each got.

#3863 Start all (instead of Disconnected) Site-to-Site VPN connections when VPC VR starts
  server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
  server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManager.java
  server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
  server/src/test/java/com/cloud/vpc/MockVpcVirtualNetworkApplianceManager.java
Labels: component:virtual-router, type:bug

#3861 test: check more connectivity in test_privategw_acl.py
  test/integration/smoke/test_privategw_acl.py
Labels: component:unit-test, component:vpc, type:enhancement

#3867 Usage event to store zone id while uploading template and volume
  server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java
Labels: component:management-server, component:templates, type:bug

#3851 vpc: set traffic type of private gateway IP to Public to fix keepalived misconfiguration
  engine/schema/src/main/java/com/cloud/network/vpc/dao/VpcGatewayDao.java
  engine/schema/src/main/java/com/cloud/network/vpc/dao/VpcGatewayDaoImpl.java
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
Labels: component:virtual-router, component:vpc, type:bug

#3857 vr: add missing rule for port forwarding rule in vpc
  systemvm/debian/opt/cloud/bin/configure.py
Labels: component:networking, component:virtual-router

#3865 Fixed default text missing from network selection on instance wizard
  ui/scripts/ui-custom/instanceWizard.js
Labels: component:UI, type:bug

#3854 Install python-dnspython or python-dns to fix issue with cloudstack-setup-management
  debian/control
  packaging/centos7/cloud.spec
Labels: component:packaging, type:bug

#3844 ISSUE-3838: Wrong SSVM behavior causes redownloading for all the templates
  server/src/main/java/org/apache/cloudstack/storage/NfsMountManagerImpl.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
Labels: component:ssvm, type:bug

#3805 UI: Display drop down list for VPN customer gateway selection
  ui/scripts/network.js
Labels: component:UI, type:enhancement

#3732 [Vmware] Enable PVLAN support on L2 networks
  api/src/main/java/com/cloud/network/Network.java
  api/src/main/java/com/cloud/network/NetworkProfile.java
  api/src/main/java/com/cloud/offering/NetworkOffering.java
  api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkDao.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
  server/src/main/java/com/cloud/network/guru/GuestNetworkGuru.java
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/network/CreatePrivateNetworkTest.java
  server/src/test/java/com/cloud/network/NetworkServiceImplTest.java
  server/src/test/java/com/cloud/network/dao/NetworkDaoTest.java
  server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
  server/src/test/java/com/cloud/vpc/dao/MockNetworkDaoImpl.java
  test/integration/smoke/test_network.py
  tools/marvin/marvin/lib/base.py
  ui/l10n/en.js
  ui/scripts/sharedFunctions.js
  utils/src/main/java/com/cloud/utils/UriUtils.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Labels: component:advanced-networking, component:networking, status:Work-in-Progress

#3876 server: use host record related to a ssvm/cpvm
  api/src/main/java/org/apache/cloudstack/api/response/SystemVmResponse.java
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: type:bug

#3877 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  client/pom.xml
  plugins/network-elements/juniper-contrail/pom.xml
Labels: component:build, component:security, type:bug

#3873 Fixed root volume resize from ui
  ui/scripts/storage.js
Labels: component:UI, type:bug

#3871 Fixed duplicate id error when creating VM work jobs
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
Labels: component:management-server, type:bug

#3880 simulator: fix travis failure after merging volume destroy/recover
  plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockStorageManagerImpl.java
  test/integration/smoke/test_vm_life_cycle.py
Labels: component:travis, type:bug

#3864 Ignore site to site vpn status check on internallbvm
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Labels: component:virtual-router, type:bug

#3882 remove duplicate index region
  engine/schema/src/main/resources/META-INF/db/schema-41300to41400-cleanup.sql
Labels: component:database, type:bug

#3884 kvm: fix exception in volume stats after storage migration
  server/src/main/java/com/cloud/server/StatsCollector.java
Labels: component:primary-storage, type:bug

#3739 Add new command to update security group name
  .travis.yml
  api/src/main/java/com/cloud/event/EventTypes.java
  api/src/main/java/com/cloud/network/security/SecurityGroupService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/UpdateSecurityGroupCmd.java
  engine/schema/src/main/java/com/cloud/network/security/SecurityGroupVO.java
  server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  test/integration/smoke/test_update_security_group.py
  ui/scripts/network.js
Labels: component:security-group, type:enhancement

#3879 kvm: Enable virtio drivers based on guest os display name
  server/src/main/java/com/cloud/hypervisor/KVMGuru.java
Labels: Severity:BLOCKER, component:kvm

#3491 KVM: Propagating changes on host parameters to the agents
  engine/components-api/src/main/java/com/cloud/agent/AgentManager.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  framework/agent-lb/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLB.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetHostParamsCommandWrapper.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
  server/src/test/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImplTest.java
  server/src/test/resources/createNetworkOffering.xml
Labels: component:kvm, type:enhancement

#3639 Multiple networks support for vms in advanced zone with security group (and kvm support)
  core/src/main/java/com/cloud/agent/api/RebootCommand.java
  core/src/main/java/com/cloud/agent/api/SecurityGroupRulesCmd.java
  engine/components-api/src/main/java/com/cloud/network/security/SecurityGroupManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/NicDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/NicDaoImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtNetworkRulesVmSecondaryIpCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPlugNicCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRebootCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSecurityGroupRulesCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUnPlugNicCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  scripts/vm/network/security_group.py
  server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
  server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl2.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  test/integration/component/test_multiple_nic_support.py
  tools/marvin/marvin/lib/utils.py
  ui/scripts/instanceWizard.js
  ui/scripts/instances.js
  ui/scripts/network.js
  ui/scripts/ui-custom/instanceWizard.js
Labels: component:kvm, component:security-group, status:ready-for-merge, type:new-feature

#3905 Fix network rules issue if default egress policy is Allow
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Labels: component:networking, type:bug

#3899 vpc: add bypassvlanoverlapcheck parameter when create private gateway
  api/src/main/java/com/cloud/network/NetworkService.java
  api/src/main/java/com/cloud/network/vpc/VpcService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreatePrivateGatewayCmd.java
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkDao.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/test/java/com/cloud/network/CreatePrivateNetworkTest.java
  server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
  server/src/test/java/com/cloud/vpc/dao/MockNetworkDaoImpl.java
  test/integration/smoke/test_privategw_acl.py
  tools/marvin/marvin/lib/base.py
  ui/scripts/vpc.js
Labels: component:vpc, type:bug, type:enhancement

#3731 Enable Direct Download for System VMs
  agent/src/main/java/com/cloud/agent/direct/download/HttpDirectTemplateDownloader.java
  agent/src/main/java/com/cloud/agent/direct/download/HttpsDirectTemplateDownloader.java
  agent/src/main/java/com/cloud/agent/direct/download/MetalinkDirectTemplateDownloader.java
  api/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManager.java
  core/src/main/java/org/apache/cloudstack/agent/directdownload/DirectDownloadCommand.java
  core/src/main/java/org/apache/cloudstack/agent/directdownload/HttpDirectDownloadCommand.java
  core/src/main/java/org/apache/cloudstack/agent/directdownload/HttpsDirectDownloadCommand.java
  core/src/main/java/org/apache/cloudstack/agent/directdownload/MetalinkDirectDownloadCommand.java
  core/src/main/java/org/apache/cloudstack/agent/directdownload/NfsDirectDownloadCommand.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateZoneDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateZoneDaoImpl.java
  engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
  server/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
  server/src/test/resources/createNetworkOffering.xml
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
Labels: component:agent, type:enhancement

#3894 api: Fix count and item issues returned by list APIs
  api/src/main/java/com/cloud/projects/Project.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/cluster/ListClustersCmd.java
  engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
  engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDao.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java
  framework/db/src/main/java/com/cloud/utils/db/GenericDao.java
  framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListClustersMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListHostsMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListStoragePoolsMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVolumesMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListZonesMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsService.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/InfrastructureResponse.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/test/java/com/cloud/user/MockUsageEventDao.java
  ui/scripts/system.js
Labels: component:api, type:bug

#3903 VR: Send VM password to all Running VRs in network/vpc
  server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
Labels: component:vpc, type:bug

#3904 Avoid duplicate alerts when router state changes
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Labels: component:vpc, type:enhancement

#3913 Fix dhcp infinite lease time
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
Labels: component:virtual-router, type:bug

#3916 server: fix issue while list ssh keypairs by keyword
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: component:management-server, type:bug

#3907 Allow port 80/8080 accessible only from guest network
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
Labels: component:virtual-router, type:bug

#3898 vrouter: reload keepalived instead of restart and fix password server issues when add/remove vpc tier
  systemvm/debian/opt/cloud/bin/configure.py
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
  systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
Labels: component:vpc, type:bug

#3847 VR: Fix Redundant VRouter guest network on wrong interface
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
  systemvm/debian/etc/sysctl.conf
  test/integration/component/test_multiple_subnets_in_isolated_network.py
  test/integration/component/test_multiple_subnets_in_isolated_network_rvr.py
  test/integration/component/test_multiple_subnets_in_vpc.py
  test/integration/component/test_multiple_subnets_in_vpc_rvr.py
  tools/marvin/marvin/lib/base.py
  tools/marvin/marvin/lib/utils.py
Labels: component:networking, type:bug
