Repository apache/cloudstack, pull requests merged in 2020-10, with the labels that each got.

#4354 createaccountcmd: Improving account param description
  api/src/main/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmd.java
Labels: component:api, type:Documentation

#4321 VMware: match hardware version for worker VM when taking a snapshot
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware, type:bug

#4271 hypervisor: Add Citrix Hypervisor 8x product name support
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServerUtilitiesHelper.java
Labels: Severity:Critical, type:enhancement

#4397 List VMs by Security Group & HA
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: component:api

#4373 Handles creation /var/run/cloud folder for creation of lock file while modifyvxlan.sh script is run
  scripts/vm/network/vnet/modifyvxlan.sh
Labels: component:vxlan, type:bug

#4382 debian/control: add uuid-runtime to cloudstack-common, ufw/apparmor to cloudstack-agent
  debian/control
Labels: component:packaging, type:Cleanup

#4404 scalekubernetesclustercmd: Making id a required field [NPE Fix]
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/ScaleKubernetesClusterCmd.java
Labels: type:bug

#4348 vmware: use hotPlugMemoryIncrementSize only for valid value
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Labels: type:bug

#4228 Dont add host back after agent service restart
  agent/src/main/java/com/cloud/agent/Agent.java
  core/src/main/java/com/cloud/agent/api/ShutdownCommand.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Labels: component:agent, type:bug

#4251 Handle with VM snapshot events
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
  usage/src/test/java/com/cloud/usage/UsageManagerImplTest.java
Labels: component:usage-server, status:Work-in-Progress, type:bug, type:enhancement

#4194 enable update tags on disk offerings
  api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java
  engine/schema/src/main/java/com/cloud/storage/DiskOfferingVO.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/test/java/com/cloud/configuration/ConfigurationManagerTest.java
  ui/scripts/configuration.js
Labels: component:UI, component:api, type:enhancement

#4395 support for data migration of incremental snaps on xen
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/DataMigrationUtility.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/StorageOrchestrator.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreVO.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/TemplateDataStoreVO.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/VolumeDataStoreVO.java
  engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/SecondaryStorageServiceImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/PremiumSecondaryStorageManagerImpl.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Labels: Severity:Critical

#4387 Fix JsonSyntaxException when creating API command response #4355
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
  framework/jobs/src/test/java/org/apache/cloudstack/framework/jobs/AsyncJobManagerTest.java
Labels: type:bug

#3946 server: add global configuration for default router service offering
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManager.java
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
  server/src/main/java/org/cloud/network/router/deployment/RouterDeploymentDefinition.java
  server/src/main/java/org/cloud/network/router/deployment/VpcRouterDeploymentDefinition.java
Labels: component:virtual-router, type:new-feature

#4412 Validating type parameter and including all types
  api/src/main/java/com/cloud/network/Network.java
  api/src/main/java/org/apache/cloudstack/api/command/user/network/ListNetworksCmd.java
Labels: type:enhancement

#4411 Display Kubernetes cluster name instead of uuid
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
Labels: type:bug

#4193 Fix usage record count
  api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: Severity:Minor, type:bug

#4360 server: Update use_bytes of storage pools
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/StoragePoolVO.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: component:api, type:enhancement

#4413 systemvm: fix proc.find in CsProcess.py
  systemvm/debian/opt/cloud/bin/cs/CsApp.py
  systemvm/debian/opt/cloud/bin/cs/CsProcess.py
Labels: component:virtual-router, type:bug

#4409 Enhance UpdateDiskOfferingCmd
  api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/test/java/com/cloud/configuration/ConfigurationManagerTest.java
Labels: component:api, type:enhancement

#2206 [CLOUDSTACK-10020] Changes to make marvin work with projects and VPCs
  tools/marvin/marvin/lib/base.py
Labels: status:testing

#4375 Fixing count for findHostsForMigration
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: Severity:Minor, component:api, type:bug

#4415 CKS : More log changes from uuid to name
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStopWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtil.java
Labels: component:cks, type:enhancement

#4420 Including instance details in KubernetesClusterResponse
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java
  test/integration/smoke/test_kubernetes_clusters.py
Labels: component:api, type:enhancement

#4427 packaging/deb: Include cloudstack-guest-tool into cloudstack-agent DEB package
  debian/cloudstack-agent.install
Labels: component:packaging, distro:ubuntu

#4367 Remove cpu core from op_host_capacity when host is deleted
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Labels: type:bug

#4414 Adding public ip to listKubernetesClusterResponse
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java
Labels: type:enhancement

#4417 Modify alter view to drop/create view
  engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql
Labels: type:Cleanup, type:bug

#4363 Ability to put a server in Down state to maintenance
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Labels: component:compute, type:enhancement

#3945 server: update template to another template type
  api/src/main/java/org/apache/cloudstack/api/command/user/template/UpdateTemplateCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/TemplateResponse.java
  server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  ui/scripts/templates.js
Labels: component:management-server, systemvm-template-change, type:new-feature

#4144 Fix Usage failed to get pid
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
Labels: component:usage-server, docker, type:bug

#4432 Unable to create snapshot from vm snapshot
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java
Labels: type:bug

#4426 DB: fix wrong category id of guest os 'Other PV Virtio-SCSI (64-bit)'
  engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql
Labels: type:bug

#4359 Failed to update host password if username/password is not saved in db
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: component:api, type:bug

#4429 FIX s2svpn connection stuck on Pending state
  server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
Labels: type:bug

#4177 Prevent deploying IPv6 network if Zone has no IPv6 DNS configured
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/test/java/com/cloud/network/NetworkModelTest.java
Labels: component:ipv6, component:virtual-router, type:bug, type:enhancement

#4435 server: fix format error with memorywithoverprovisioning in list hosts response
  server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Labels: Severity:Trivial, component:api, type:bug

#4388 fix NPE in volumes statistics
  server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/vm/UserVmManager.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug

#4341 Allow to configure root disk size via Service Offering (diskoffering of type Service).
  api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/ResizeVolumeCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/ServiceOfferingResponse.java
  engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql
  server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/ServiceOfferingJoinVO.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
  ui/scripts/configuration.js
  ui/scripts/docs.js
Labels: component:primary-storage, type:enhancement, type:new-feature
