Repository apache/cloudstack, pull requests merged in 2020-12, with the labels that each got.

#4499 Adding cpuallocated percentage and value to host and hostsformigrationresponse
  api/src/main/java/org/apache/cloudstack/api/response/HostForMigrationResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
  server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Labels: type:enhancement

#4501 Disallowing udp for lb rules for haproxy
  server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
Labels: type:bug

#4510 Adding zone name to physicalnetworkresponse
  api/src/main/java/org/apache/cloudstack/api/response/PhysicalNetworkResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: type:enhancement

#4515 Update log output for FirstFitPlanner
  server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
Labels: Severity:Trivial, component:documentation, component:logging, type:bug

#4521 change debug to warn for unknown exceptions
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
Labels: Severity:Trivial, component:logging, type:improvement

#4525 xenserver: check and eject patch vbd for systemvms
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixReadyCommandWrapper.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixSetupCommandWrapper.java
Labels: Severity:Critical, component:XenServer

#4527 kvm: set cpu topology only if cpucore per socket is set
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: Severity:Critical, type:regression

#4530 extract volume: Fix NPE when Volume exists on secondary store but doesn't have a download URL
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: type:bug

#4511 listphysicalnetworks: Honouring keyword parameter
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: complexity:trivial, type:bug

#4516 Fix hypervisor type cast to string
  engine/storage/integration-test/src/test/java/org/apache/cloudstack/storage/test/VolumeServiceTest.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: Severity:BLOCKER

#4522 template: Ensuring template is cross zone if type changed to system
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
Labels: Severity:Major, type:improvement

#4529 vr: Ensuring dnsmasq.leases file is populated
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
Labels: Severity:Major, component:virtual-router, type:bug

#4540 Bug/unmanaged ingest exceptions #4539
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: Severity:Major, component:vmware, type:bug

#4555 VMware: Fix template upload from local
  api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
  core/src/main/java/org/apache/cloudstack/storage/command/UploadStatusAnswer.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java
  server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java
  server/src/main/java/com/cloud/template/TemplateAdapterBase.java
  server/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelper.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadEntity.java
Labels: Severity:BLOCKER

#4553 Fix for mapping guest OS type read from OVF to existing guest OS in C…
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java
Labels: Severity:BLOCKER

#4554 README: that time of the year! 🎄
  README.md
Labels: component:documentation
