Repository apache/cloudstack, pull requests merged in 2020-09, with the labels that each got.

#4020 server: move UpdateDefaultNic to vm work job queue
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkUpdateDefaultNic.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:networking, type:bug

#4279 Avoid Null pointer at DomainChecker and enhance AssignVMCmd
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/AssignVMCmd.java
  server/src/main/java/com/cloud/acl/DomainChecker.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:api, type:bug

#4291 Manage influxDB Batches avoiding OutOfMemory Exception
  pom.xml
  server/src/main/java/com/cloud/server/StatsCollector.java
Labels: Severity:Critical, type:bug

#4301 Ubuntu 20.04: restart libvirtd instead of libvirt-bin
  python/lib/cloudutils/serviceConfig.py
Labels: component:kvm, type:bug

#4306 Ubuntu 20.04: Fix issue while build package on ubuntu 20.04
  debian/control
Labels: component:packaging, type:bug

#4297 Incorrect md5sums for systemVM templates results in failure to download templates to other image stores
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41310to41400.java
Labels: component:templates, type:bug

#4315 Adding acl name to listNetworkAcl, listNetwork, listPrivateGateway, listVpcs responses
  api/src/main/java/org/apache/cloudstack/api/response/NetworkACLItemResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/PrivateGatewayResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: component:api, component:primate

#4326 ui: call logout before login to clear old sessionkey cookies
  ui/scripts/cloudStack.js
Labels: Severity:Critical, component:UI, component:primate

#4294 Create template from detached data-disks on VMWare
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
Labels: component:templates, component:vmware, type:bug

#4239 Disabling managing firewall - cloudstack-setup-management
  client/bindir/cloud-setup-management.in
  python/lib/cloudutils/serviceConfig.py
  python/lib/cloudutils/syscfg.py
Labels: component:management-server, type:enhancement

#4303 Ubuntu 20.04: Fix systemvm cannot start up
  scripts/vm/network/security_group.py
Labels: component:csvm, component:ssvm, type:bug

#4336 vmware: while plugging in nics get existing sorted nic devices
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:virtual-router, component:vmware

#4190 Broadcast URI not set to vxlan, but vlan (Fix #3040)
  api/src/main/java/com/cloud/network/Networks.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
Labels: component:networking, type:bug

#4340 Changing test_pvlan vlan id to prevent conflict with smoke tests env config
  test/integration/smoke/test_pvlan.py
Labels: component:networking, type:Cleanup

#4345 Binding listening socket to all address for remote debug
  packaging/systemd/cloudstack-agent.default
  packaging/systemd/cloudstack-management.default
Labels: component:build, type:enhancement

#4338 server: check guest os preference of last host when start a vm
  server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
Labels: component:management-server, type:bug

#4269 cks: assorted fixes, test refactoring
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/admin/kubernetes/version/AddKubernetesSupportedVersionCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/admin/kubernetes/version/DeleteKubernetesSupportedVersionCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/CreateKubernetesClusterCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/DeleteKubernetesClusterCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/ScaleKubernetesClusterCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/StartKubernetesClusterCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/StopKubernetesClusterCmd.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/UpgradeKubernetesClusterCmd.java
  scripts/util/create-kubernetes-binaries-iso.sh
  test/integration/smoke/test_kubernetes_clusters.py
  test/integration/smoke/test_kubernetes_supported_versions.py
  tools/marvin/marvin/config/test_data.py
Labels: Severity:Critical

#4352 Retry redfish requests
  plugins/outofbandmanagement-drivers/redfish/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/redfish/RedfishOutOfBandManagementDriver.java
  utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishClient.java
  utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
Labels: component:management-server, type:enhancement
