Repository apache/cloudstack, pull requests merged in 2020-01, with the labels that each got.

#3721 network: cleanup dhcp/dns entries while remove a nic from vm
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Labels: component:networking, type:bug

#3793 ui: fix for truncated name for project accounts
  ui/css/cloudstack3.css
Labels: component:UI, type:bug

#3313 Simulator: Better VR Redundant Status Behaviour
  plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockVmManagerImpl.java
Labels: component:virtual-router, type:enhancement

#3536 Extract systemvm.iso using bsdtar
  debian/control
  packaging/centos7/cloud.spec
  scripts/vm/systemvm/injectkeys.sh
Labels: component:networking, type:enhancement

#3743 only update powerstate if sure it is the latest
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Labels: component:management-server, type:bug

#3778 Endless settings on templates and instances
  ui/scripts/instances.js
  ui/scripts/templates.js
Labels: component:UI, type:bug

#3736 Add protocol number support for security group rules
  api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/AuthorizeSecurityGroupIngressCmd.java
  scripts/vm/network/security_group.py
  server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
  test/integration/component/test_protocol_number_security_group.py
  ui/scripts/network.js
Labels: component:security-group, type:enhancement

#3510 Allow additional configuration metadata to VMs
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/hypervisor/xenserver/ExtraConfigurationUtility.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
  test/integration/smoke/test_deploy_vm_extra_config_data.py
Labels: type:enhancement, type:new-feature

#3800 Revert "Extract systemvm.iso using bsdtar (#3536)"
  debian/control
  packaging/centos7/cloud.spec
  scripts/vm/systemvm/injectkeys.sh
Labels: component:virtual-router, type:bug

#3659 Fix typo: the past tense of shutdown is shutdown, not shutdowned
  api/src/main/java/com/cloud/vm/VirtualMachine.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/main/resources/META-INF/db/schema-41300to41400.sql
  plugins/network-elements/juniper-contrail/src/main/java/org/apache/cloudstack/network/contrail/model/VirtualMachineModel.java
  server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  ui/scripts/instances.js
  ui/scripts/metrics.js
Labels: component:UI, type:enhancement

#3776 Add missing HA config keys
  engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
  server/src/main/java/com/cloud/test/DatabaseConfig.java
Labels: component:management-server, status:ready-for-merge, type:bug, type:enhancement

#3795 Agent lb on svm
  server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
Labels: component:csvm, component:ssvm, type:bug

#3814 Add missing HA config keys (#3776)
  engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
  server/src/main/java/com/cloud/test/DatabaseConfig.java
Labels: component:management-server, type:bug, type:enhancement

#3806 python/c++ formatting in java corrected
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
Labels: component:logging, type:bug

#3799 Update message when keys are NOT being injected
  scripts/vm/systemvm/injectkeys.sh
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
Labels: component:management-server, type:bug, type:enhancement

#3822 set TCP as default protocol in lb list
  ui/scripts/network.js
Labels: component:UI, type:enhancement

#3759 server: fix resource count error when upgrade a vm
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:management-server, type:bug

#3825 fixed inconsistency of IP on VR when VR is destroyed and recrea…
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
Labels: component:virtual-router, type:bug

#3821 Incorrect param name caused global setting test to fail
  test/integration/smoke/test_global_settings.py
Labels: status:testing

#3477 RvR: Set up metadata/password/dhcp server on gateway IP instead of guest IP in RVR
  systemvm/debian/etc/apache2/vhost.template
  systemvm/debian/opt/cloud/bin/configure.py
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
  systemvm/debian/opt/cloud/bin/cs/CsApp.py
  systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
  systemvm/debian/opt/cloud/bin/cs/CsFile.py
  systemvm/debian/opt/cloud/bin/cs/CsHelper.py
  systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
  systemvm/debian/opt/cloud/bin/passwd_server_ip.py
  systemvm/debian/opt/cloud/bin/setup/secstorage.sh
Labels: component:virtual-router, type:bug

#3727 server: Capacity check should take vms in Migrating state into calculation
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
Labels: component:management-server, type:bug

#3728 server: double check host capacity when start/migrate a vm
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
Labels: component:management-server, type:bug

#3758 server: Fix NPE while update displayvm on vm with dynamic service offering
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:management-server, type:bug

#3761 [FIX] [BACKPORT] [4.13] Rethrow takeVMSnapshot() exception
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
Labels: component:management-server, type:bug

#3813 kvm-local-pool-trailing-slash
  engine/schema/src/main/resources/META-INF/db/schema-41300to41400-cleanup.sql
Labels: component:database, component:kvm, type:enhancement

#3835 Update Docker README file
  tools/docker/README.md
Labels: docker, type:Cleanup, type:Documentation

#3845 travis: use https based maven repo mirror
  tools/travis/before_install.sh
Labels: Severity:BLOCKER

#3846 Fix for "Impossible to edit domain settings in UI"
  ui/css/cloudstack3.css
Labels: component:UI, type:bug

#3726 vrouter: reload haproxy when cfg file is updated
  systemvm/debian/opt/cloud/bin/cs/CsLoadBalancer.py
Labels: component:virtual-router, type:bug

#3848 vr: fix vr in unknown state (more)
  systemvm/debian/opt/cloud/bin/cs/CsHelper.py
  systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
Labels: component:virtual-router, type:bug

#3834 Fix: The metrics view API response is not super-set of resources response keys
  api/src/main/java/org/apache/cloudstack/api/response/ClusterResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/ZoneResponse.java
  server/src/main/java/com/cloud/api/query/dao/DataCenterJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Labels: component:api, type:bug

#3840 Fix listing management server by parameters
  api/src/main/java/org/apache/cloudstack/api/command/admin/management/ListMgmtsCmd.java
  api/src/main/java/org/apache/cloudstack/management/ManagementServerHost.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: component:api, component:management-server, type:bug

#3803 Bug fix : set restart_required to 0 after restarting network
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Labels: component:networking, type:bug

#3760 New feature: Resource count (CPU/RAM) take only running vms into calculation
  api/src/main/java/com/cloud/vm/UserVmService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/StartVMCmd.java
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/UserVmDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
  server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
  server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManager.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  test/integration/component/test_resource_count_running_vms.py
  tools/marvin/marvin/codes.py
  tools/marvin/marvin/lib/common.py
Labels: component:management-server, type:new-feature

#3604 Fix Policy Based Routing for private gateway static routes
  systemvm/debian/opt/cloud/bin/configure.py
Labels: component:virtual-router, type:bug

#3819 Clean up inactive iscsi sessions when VMs get moved due to crashes
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiStorageCleanupMonitor.java
Labels: component:kvm, component:managed-storage, type:bug, type:enhancement

#3383 template: copy md5 mismatch
  engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
  server/src/main/java/com/cloud/storage/download/DownloadMonitorImpl.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
  utils/src/main/java/org/apache/cloudstack/utils/security/ChecksumValue.java
Labels: component:management-server, component:templates, type:bug

#3855 kvm: Fix router migration issue when router has control/public nics onother physical network than guest
  agent/bindir/libvirtqemuhook.in
Labels: component:kvm, component:virtual-router, type:bug

#3832 ui bug fix: cannot assign vms to internal lb in VPC
  ui/scripts/ui/widgets/listView.js
Labels: component:UI, type:bug

#3791 server: fix checking disk offering access for snapshot volume
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:local-storage, type:bug

#3818 Display numeric value in exception instead of variable name
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
Labels: component:management-server, type:bug

#3807 Enhancement: Allow creating network with duplicate name
  .travis.yml
  engine/schema/src/main/java/com/cloud/network/dao/NetworkDao.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/test/java/com/cloud/vpc/dao/MockNetworkDaoImpl.java
  test/integration/smoke/test_create_network.py
Labels: component:networking, type:enhancement

#3836 Bug fix: De-associate IP address if enabling static nat fails
  server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java
Labels: component:vpc, type:bug
