Repository apache/cloudstack, pull requests merged in 2020-04, with the labels that each got.

#4005 Fixed create template from snapshot never returning
  ui/scripts/sharedFunctions.js
Labels: type:bug

#3988 Add support for zulu-11 in cloudstack 4.14
  debian/control
Labels: component:packaging, type:enhancement

#3999 Update schema-41310to41400.sql
  engine/schema/src/main/resources/META-INF/db/schema-41310to41400.sql
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java
Labels: component:database, type:enhancement

#3984 Remove rolling-maintenance service from debian rules
  debian/rules
Labels: component:packaging, type:bug

#4002 server: Search zone-wide storage pool when allocation algothrim is firstfitleastconsumed
  engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDao.java
  engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDaoImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
  server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
Labels: component:management-server, type:bug

#4014 Improvement on build time and new quality profile
  pom.xml
Labels: component:build, type:improvement

#4025 server: Cannot list affinity group if there are hosts dedicated to domain
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: type:bug

#3969 Snapshot deletion issues
  engine/storage/integration-test/src/test/resources/fakeDriverTestContext.xml
  engine/storage/integration-test/src/test/resources/storageContext.xml
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java
  engine/storage/snapshot/src/main/resources/META-INF/cloudstack/storage/spring-engine-storage-snapshot-storage-context.xml
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
Labels: Severity:BLOCKER

#4023 FIX: prevent empty sshkey name.
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: component:api, type:bug, type:enhancement

#4043 Volume migration
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
Labels: Severity:BLOCKER

#4042 Fixed guest vlan range going missing when using zone wizard
  ui/scripts/zoneWizard.js
Labels: component:UI, type:bug
