Repository apache/cloudstack, pull requests merged in 2021-11, with the labels that each got.

#5646 usage: updateNewMaxId after sanity check
  usage/src/main/java/com/cloud/usage/UsageSanityChecker.java
Labels: type:bug, component:usage-server

#5642 upgrade/systemvm: add template zone entries
  engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
Labels: type:bug, Severity:BLOCKER, status:needs-testing

#5645 Marvin: change some vlans in test_data.py
  tools/marvin/marvin/config/test_data.py
Labels: type:bug, component:marvin

#5661 linstor-volume-plugin: Only create diskless assignments on nodes
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
Labels: Severity:BLOCKER

#5659 api,server,engine/schema: admin listvm api clusterid
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ListVMsCmdByAdmin.java
  engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
Labels: Severity:Critical, type:regression

#5665 Revert "parallel nic adding"
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/dao/VmWorkJobDao.java
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/dao/VmWorkJobDaoImpl.java
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobVO.java
  framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/VmWorkJobVO.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:regression

#5693 UI: Fixes incorrect auto-select in Add network to VM
  ui/src/views/compute/InstanceTab.vue
Labels: component:UI

#4966 Refactor few process of VirtualMachineManagerImpl and improve logs
  api/src/main/java/com/cloud/vm/NicProfile.java
  engine/components-api/src/main/java/com/cloud/vm/VmWork.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkAddVmToNetwork.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkMigrate.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkMigrateAway.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkMigrateForScale.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkMigrateWithStorage.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkReboot.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkReconfigure.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkRemoveNicFromVm.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkRemoveVmFromNetwork.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkRestore.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkStart.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkStop.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkStorageMigration.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkUpdateDefaultNic.java
  engine/schema/src/main/java/com/cloud/storage/VMTemplateVO.java
  framework/ipc/src/main/java/com/cloud/agent/manager/Commands.java
Labels: type:enhancement, type:cleanup

#5145 ui: changes in migrate vm storage and migrate volume form
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  ui/public/locales/en.json
  ui/src/components/view/InstanceVolumesStoragePoolSelectListView.vue
  ui/src/components/view/StoragePoolSelectView.vue
  ui/src/components/view/VolumeStoragePoolSelectForm.vue
  ui/src/main.js
  ui/src/utils/plugins.js
  ui/src/views/compute/MigrateVMStorage.vue
  ui/src/views/compute/MigrateWizard.vue
  ui/src/views/storage/MigrateVolume.vue
  ui/tests/common/index.js
Labels: component:UI
