Repository apache/cloudstack, pull requests merged in 2021-12, with the labels that each got.

#5720 Removed redundant call for VM snapshot chain size, in VMware.
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
Labels: component:vmware

#5740 Fix wrong logger class in *Cmd.java
  api/src/main/java/org/apache/cloudstack/api/BaseUpdateTemplateOrIsoCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/address/ReleasePodIpCmdByAdmin.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/cluster/ListClustersCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/router/ListVirtualRouterElementsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/storage/CreateSecondaryStagingStoreCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/ScaleSystemVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/UpgradeSystemVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListTrafficMonitorsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/user/GetUserKeysCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/user/MoveUserCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/MigrateVirtualMachineWithVolumeCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/account/DeleteAccountFromProjectCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/account/DeleteUserFromProjectCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/guest/ListGuestOsCategoriesCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/guest/ListGuestOsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/ListSslCertsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/nat/DisableStaticNatCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/nat/EnableStaticNatCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/network/DeleteNetworkCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/region/ha/gslb/UpdateGlobalLoadBalancerRuleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/resource/ListHypervisorsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/AuthorizeSecurityGroupEgressCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/ArchiveSnapshotCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/ssh/DeleteSSHKeyPairCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVmNicIpCmd.java
  engine/schema/src/main/java/com/cloud/usage/dao/UsageNetworkDaoImpl.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/ScaleKubernetesClusterCmd.java
  plugins/network-elements/juniper-srx/src/main/java/com/cloud/api/commands/ListExternalFirewallsCmd.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/api/commands/DeleteNetscalerControlCenterCmd.java
  plugins/network-elements/stratosphere-ssp/src/main/java/org/apache/cloudstack/api/commands/DeleteSspCmd.java
  server/src/main/java/com/cloud/api/ApiServlet.java
  server/src/main/java/com/cloud/api/auth/DefaultLogoutAPIAuthenticatorCmd.java
  server/src/main/java/com/cloud/storage/download/DownloadState.java
  server/src/main/java/com/cloud/storage/upload/UploadState.java
  test/src-not-used/main/java/com/cloud/test/stress/StressTestDirectAttach.java
  test/src-not-used/main/java/com/cloud/test/utils/SignEC2.java
Labels: component:logging

#5746 check security group in basic zones during deploy
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:security-group, component:basic-network

#5735 [VMware] Improve volume file search on the datastore while computing the VM snapshot chain size.
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
Labels: component:vmware

#5734 UI - Fixes the next button not working when adding more physical networks
  ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
Labels: component:UI

#5738 internal ref replaced by uuid
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: type:bug, component:usage-server, Severity:Minor, complexity:trivial

#5745 conditional broadcastUri
  ui/src/config/section/network.js
  ui/src/role/index.js
  ui/src/views/compute/KubernetesServiceTab.vue
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateNetwork.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
  ui/src/views/network/UpdateNetwork.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/offering/UpdateOfferingAccess.vue
Labels: component:UI

#5680 [Veeam] Fix full backup VM restore exception
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  server/src/test/java/com/cloud/hypervisor/KVMGuruTest.java
Labels: component:backup

#4276 Update listVirtualMachines API documentation with 'projectid=-1' to list all VMs in projects.
  api/src/main/java/org/apache/cloudstack/api/BaseListDomainResourcesCmd.java
  api/src/main/java/org/apache/cloudstack/api/BaseListProjectAndAccountResourcesCmd.java
Labels: component:api, component:documentation, complexity:trivial

#5763 Increase the length for parameters that expect a list of domain IDs.
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdateNetworkOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateServiceOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/UpdateVPCOfferingCmd.java
Labels: type:bug, Severity:Trivial, complexity:trivial

#5779 UI: fix create Isolated/L2 network form
  ui/src/role/index.js
Labels: component:UI

#5762 Enhance log message in FirstFitPlanner
  server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
Labels: type:enhancement, component:logging, Severity:Minor

#5353 Improve VMWare logs
  core/src/main/java/com/cloud/storage/resource/StorageSubsystemCommandHandlerBase.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareHostService.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareSecondaryStorageResourceHandler.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware, component:logging

#5791 Allow force reboot VM from user account, to start VM on the same host.
  server/src/main/java/com/cloud/vm/UserVmManager.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: Severity:Major

#5562 cleanup of unused code and cleanup of cleanup procedure
  test/integration/smoke/test_router_dhcphosts.py
Labels: component:integration-test

#5804 UI: show SSH keys step in VM deployment only if user can 'listSSHKeyPairs'
  ui/src/views/compute/DeployVM.vue
Labels: component:UI

#5757 network: update ip in lb/pf/dnat tables when update vm nic ip
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vm/UserVmManagerTest.java
Labels: component:networking

#5690 UI - Fixes cannot add new port forwarding rules after auto select VM next time
  ui/src/views/network/PortForwarding.vue
Labels: component:UI

#5802 kvm: don't always force scsi controller for aarch64 VMs
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: type:bug, component:ceph

#5798 ui: show tags only for supported resources
  ui/src/components/view/InfoCard.vue
Labels: component:UI

#5796 Fix UI issue 5777 Root disk size is not shown as 'Disk Size' on VM deployment.
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:UI

#5789 Randomize managed volume copy host
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: status:needs-testing

#5752 [VMware] Fix service offerings listing on appliances deployment options
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  ui/src/views/compute/wizard/ComputeOfferingSelection.vue
Labels: type:bug, component:vmware

#5684 (ccc2021 hackathon ) kvm: add hosts using cloudstack ssh private key
  server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/test/java/com/cloud/resource/ResourceManagerImplTest.java
  ui/public/locales/en.json
  ui/src/views/infra/HostAdd.vue
  utils/src/main/java/com/cloud/utils/ssh/SSHCmdHelper.java
Labels: hackathon

#5628 UI: Add footer text option for login screen
  ui/public/config.json
  ui/src/layouts/UserLayout.vue
Labels: component:UI

#5625 [UI] Change permission to access console proxy button
  ui/src/components/widgets/Console.vue
Labels: status:needs-testing

#5809 ui: fix add network offering for vpc
  ui/src/components/CheckBoxSelectPair.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
Labels: component:UI

#5714 UI: Automatically refill tariff label information after editing.
  ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
Labels: component:UI
