Repository apache/cloudstack, pull requests merged in 2021-06, with the labels that each got.

#5061 Fix string format error
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: Severity:Minor, type:bug

#5057 Create fcd folder on local storage in VMware vSphere
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageLayoutHelper.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DatastoreMO.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HostMO.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Labels: Severity:BLOCKER, component:vmware

#5053 xenserver: attempt eject and destroying patch VBD separately
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
Labels: Severity:Critical

#5081 ui: Fix error when no ipv6 address
  ui/src/components/view/DetailsTab.vue
Labels: Severity:Trivial, component:UI, type:bug

#5085 Root disk size should be listed in GB at listServiceOffering
  server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java
  ui/src/components/view/DetailsTab.vue
Labels: complexity:trivial, component:api

#5076 [Vmware] Fix lsilogcsas controller for deploy-as-is
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DiskControllerType.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/ScsiDiskControllerType.java
Labels: component:vmware

#5097 Update chain info of the volumes after migrate operations
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: component:vmware

#5101 Enhance docs for changeServiceForVM & scaleVirtualMachine
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ScaleVMCmdByAdmin.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/UpgradeVMCmdByAdmin.java
Labels: component:api, component:documentation

#5078 vxlan: arp does not work between hosts as multicast group is communicated over physical nic instead of linux bridge
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
Labels: type:regression

#5037 Updated PowerFlex/ScaleIO gateway client with some improvements.
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  plugins/storage/volume/scaleio/pom.xml
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClient.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientConnectionPool.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImpl.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java
  plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImplTest.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:primary-storage, type:enhancement

#5113 allow big contents from error output in marvin tests
  tools/travis/xunit-reader.py
Labels: complexity:trivial

#4819 Remove meaningless password regeneration on resetSSHKeyForVirtualMachine
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
Labels: type:cleanup, type:enhancement

#5080 ui: Show default nic/network in infocard
  ui/src/components/view/InfoCard.vue
  ui/src/views/compute/DeployVM.vue
Labels: component:UI, type:enhancement

#4572 fix of detach volume while OS is in boot state
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  test/integration/smoke/test_volumes.py
Labels: Severity:Major, complexity:trivial, component:kvm

#5150 UI fix deployVm with rootdisk size wrongly converted
  ui/src/views/compute/DeployVM.vue
Labels: component:UI

#5137 UI: SystemVM - Enabling Quickview for newly resource
  ui/src/components/view/QuickView.vue
Labels: component:UI

#5123 ui: fix missing component in SearchView
  ui/src/components/view/SearchView.vue
Labels: component:UI

#5004 Follow consistent vo table name convention
  engine/schema/src/main/java/com/cloud/dc/DomainVlanMapVO.java
  engine/schema/src/main/java/com/cloud/gpu/HostGpuGroupsVO.java
  engine/schema/src/main/java/com/cloud/gpu/VGPUTypesVO.java
  engine/schema/src/main/java/com/cloud/network/LBHealthCheckPolicyVO.java
  engine/schema/src/main/java/com/cloud/network/UserIpv6AddressVO.java
  engine/schema/src/main/java/com/cloud/network/VpnUserVO.java
  engine/schema/src/main/java/com/cloud/network/as/AutoScalePolicyConditionMapVO.java
  engine/schema/src/main/java/com/cloud/network/as/AutoScaleVmGroupPolicyMapVO.java
  engine/schema/src/main/java/com/cloud/network/as/AutoScaleVmGroupVmMapVO.java
  engine/schema/src/main/java/com/cloud/network/dao/FirewallRulesCidrsVO.java
  engine/schema/src/main/java/com/cloud/network/dao/FirewallRulesDestCidrsVO.java
  engine/schema/src/main/java/com/cloud/network/dao/IPAddressVO.java
  engine/schema/src/main/java/com/cloud/network/dao/InlineLoadBalancerNicMapVO.java
  engine/schema/src/main/java/com/cloud/network/dao/LBStickinessPolicyVO.java
  engine/schema/src/main/java/com/cloud/network/dao/LoadBalancerVMMapVO.java
  engine/schema/src/main/java/com/cloud/network/dao/LoadBalancerVO.java
  engine/schema/src/main/java/com/cloud/network/dao/NetworkRuleConfigVO.java
  engine/schema/src/main/java/com/cloud/network/dao/RemoteAccessVpnVO.java
  engine/schema/src/main/java/com/cloud/network/dao/Site2SiteCustomerGatewayVO.java
  engine/schema/src/main/java/com/cloud/network/dao/Site2SiteVpnConnectionVO.java
  engine/schema/src/main/java/com/cloud/network/dao/Site2SiteVpnGatewayVO.java
  engine/schema/src/main/java/com/cloud/network/element/OvsProviderVO.java
  engine/schema/src/main/java/com/cloud/network/element/VirtualRouterProviderVO.java
  engine/schema/src/main/java/com/cloud/network/rules/PortForwardingRuleVO.java
  engine/schema/src/main/java/com/cloud/network/security/SecurityGroupRuleVO.java
  engine/schema/src/main/java/com/cloud/network/security/SecurityGroupRulesVO.java
  engine/schema/src/main/java/com/cloud/network/security/SecurityGroupVMMapVO.java
  engine/schema/src/main/java/com/cloud/network/security/SecurityGroupVO.java
  engine/schema/src/main/java/com/cloud/vm/InstanceGroupVMMapVO.java
  engine/schema/src/main/java/org/apache/cloudstack/affinity/AffinityGroupVMMapVO.java
  engine/schema/src/main/java/org/apache/cloudstack/affinity/AffinityGroupVO.java
  engine/schema/src/main/java/org/apache/cloudstack/lb/ApplicationLoadBalancerRuleVO.java
  engine/schema/src/main/java/org/apache/cloudstack/region/gslb/GlobalLoadBalancerLbRuleMapVO.java
  engine/schema/src/main/java/org/apache/cloudstack/region/gslb/GlobalLoadBalancerRuleVO.java
  plugins/network-elements/elastic-loadbalancer/src/main/java/com/cloud/network/ElasticLbVmMapVO.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/network/NetScalerServicePackageVO.java
  plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/dao/OvsTunnelInterfaceVO.java
  plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/dao/OvsTunnelNetworkVO.java
  server/src/main/java/com/cloud/api/query/vo/AsyncJobJoinVO.java
  server/src/main/java/com/cloud/api/query/vo/DomainJoinVO.java
Labels: type:cleanup

#5002 db: Cleanup obsolete tables
  engine/components-api/src/main/java/com/cloud/template/TemplateManager.java
  engine/schema/src/main/java/com/cloud/storage/VMTemplateHostVO.java
  engine/schema/src/main/java/com/cloud/storage/VolumeHostVO.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateHostDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateHostDaoImpl.java
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplatePoolDaoImpl.java
  engine/schema/src/main/java/com/cloud/storage/dao/VolumeHostDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/VolumeHostDaoImpl.java
  engine/schema/src/main/java/com/cloud/usage/ExternalPublicIpStatisticsVO.java
  engine/schema/src/main/java/com/cloud/usage/dao/ExternalPublicIpStatisticsDao.java
  engine/schema/src/main/java/com/cloud/usage/dao/ExternalPublicIpStatisticsDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/region/RegionSyncVO.java
  engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml
  engine/schema/src/main/resources/META-INF/db/schema-41510to41600.sql
  engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/store/TemplateObject.java
  engine/storage/integration-test/src/test/java/org/apache/cloudstack/storage/test/ChildTestConfiguration.java
  plugins/hypervisors/simulator/src/main/java/com/cloud/resource/SimulatorDiscoverer.java
  plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/IntegrationTestConfiguration.java
  server/src/main/java/com/cloud/agent/manager/allocator/impl/UserConcentratedAllocator.java
  server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/main/java/com/cloud/storage/download/DownloadListener.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  server/src/test/async-job-component.xml
  server/src/test/java/com/cloud/vpc/VpcTestConfiguration.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManager.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
  test/metadata/func/templates_sync.xml
Labels: component:database, type:cleanup

#5079 vxlan: Fix failure to delete vxlan
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
Labels: component:networking

#5128 tests: Skip test_persistent_networks if kvm and ovs
  test/integration/smoke/test_persistent_network.py
Labels: component:integration-test
