Repository apache/cloudstack, pull requests merged in 2021-02, with the labels that each got.

#4602 server: keep networks order and ips while move a vm with multiple networks
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
Labels: Severity:Minor, type:bug

#4591 server: select root disk based on user input during vm import
  server/src/main/java/org/apache/cloudstack/vm/VmImportManagerImpl.java
Labels: component:vmware, type:bug

#4601 server: Get vm network/disk statistics and update database per host
  server/src/main/java/com/cloud/server/StatsCollector.java
Labels: component:database, type:bug, type:cleanup, type:improvement

#4655 test: fix checksums for test template
  test/integration/smoke/test_templates.py
Labels: type:cleanup

#4653 Update cloud-setup-databases.in - help message fix
  setup/bindir/cloud-setup-databases.in
Labels: type:cleanup

#4650 test: hardware required for changeserviceoffering
  test/integration/component/test_mm_domain_limits.py
Labels: type:cleanup

#4627 VR: fix expunging vm will remove dhcp entries of another vm in VR
  systemvm/debian/opt/cloud/bin/cs_dhcp.py
Labels: Severity:Critical, type:bug

#4651 marvin: fix test failures when changing service offering of a VM
  test/integration/smoke/test_service_offerings.py
  test/integration/smoke/test_vm_snapshots.py
Labels: type:cleanup

#4385 vmware: vm migration improvements
  api/src/main/java/com/cloud/hypervisor/HypervisorGuru.java
  api/src/main/java/com/cloud/vm/UserVmService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/MigrateSystemVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/MigrateVirtualMachineWithVolumeCmd.java
  core/src/main/java/com/cloud/agent/api/MigrateVmToPoolCommand.java
  core/src/main/java/com/cloud/agent/api/storage/MigrateVolumeCommand.java
  core/src/main/java/org/apache/cloudstack/storage/to/VolumeObjectTO.java
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VmWorkStorageMigration.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
  engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDao.java
  engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  test/integration/component/test_interpod_migration.py
  ui/public/locales/en.json
  ui/src/config/section/compute.js
  ui/src/config/section/infra/ilbvms.js
  ui/src/config/section/infra/routers.js
  ui/src/config/section/infra/systemVms.js
  ui/src/views/compute/MigrateVMStorage.vue
  ui/src/views/compute/MigrateWizard.vue
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DatastoreMO.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
Labels: component:api, component:migration, component:vmware, type:enhancement

#4665 ui: fix tags selection for add disk offering
  ui/src/views/offering/AddDiskOffering.vue
Labels: component:UI

#4445 Cleanup domain details when domain is deleted
  server/src/main/java/com/cloud/user/DomainManagerImpl.java
  server/src/test/java/com/cloud/user/DomainManagerImplTest.java
Labels: type:bug, type:cleanup

#4648 Fix typo on FirstFitAllocator
  server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
Labels: complexity:trivial

#4564 Network Offering: Allow enabling network and vpc offering during creation
  api/src/main/java/com/cloud/network/vpc/VpcProvisioningService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreateVPCOfferingCmd.java
  engine/components-api/src/main/java/com/cloud/configuration/ConfigurationManager.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  plugins/network-elements/juniper-contrail/src/main/java/org/apache/cloudstack/network/contrail/management/ContrailManagerImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java
  server/src/test/java/org/apache/cloudstack/networkoffering/CreateNetworkOfferingTest.java
Labels: type:enhancement

#4609 API discovery: Prevent overwrite of API parameters in cases where API names are same
  plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
Labels: Severity:Minor, complexity:simpel, component:api, type:bug

#4451 loop optimisation in bash
  systemvm/debian/opt/cloud/bin/vr_cfg.sh
Labels: Severity:Minor, component:virtual-router, type:cleanup

#4686 Display creation date for domain and account
  ui/src/config/section/account.js
  ui/src/config/section/domain.js
Labels: component:UI, type:enhancement

#4396 Show network name in exception message
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: Severity:Trivial, type:bug

#4667 Display account name only if its not null
  ui/src/views/infra/network/IpRangesTabPublic.vue
Labels: Severity:Trivial, complexity:trivial, component:UI

#4709 updated maven download link
  INSTALL.md
Labels: Severity:Trivial, component:documentation

#4471 Packaging: new timestamp format and add output dir option
  packaging/build-deb.sh
Labels: component:build, component:packaging

#4562 Prevent KVM from performing volume migrations of running instances
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:kvm

#4604 api: add zone, vm name params in listVmSnapshot response
  api/src/main/java/org/apache/cloudstack/api/response/VMSnapshotResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: component:UI, component:api

#4683 ui: fix systevmtype for create service offering form
  ui/src/views/offering/AddComputeOffering.vue
Labels: component:UI, type:bug

#4688 format of checksum files convenient for automated checking
  tools/build/build_asf.sh
Labels: component:packaging, type:enhancement

#4684 cks: fix CNI release url returning 404
  scripts/util/create-kubernetes-binaries-iso.sh
Labels: component:cks, type:bug

#4615 Secondary storage: Allow store deletion after successful data migration
  server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
  server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
Labels: component:secondary-storage, type:bug

#4583 Externalize TLS version on Quota's mailing
  framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java
  framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaConfig.java
  plugins/database/quota/src/main/java/org/apache/cloudstack/quota/QuotaServiceImpl.java
Labels: Severity:Minor, complexity:simpel, type:enhancement

#4728 UI: add component was missing
  ui/src/core/lazy_lib/components_use.js
Labels: component:UI, type:bug

#4716 ui: Add guest IP ranges
  ui/src/config/section/network.js
  ui/src/views/infra/network/IpRangesTabGuest.vue
  ui/src/views/infra/network/TrafficTypesTab.vue
  ui/src/views/network/CreateVlanIpRange.vue
  ui/src/views/network/GuestIpRanges.vue
Labels: component:UI

#4663 ui: fix add Vmware cluster
  ui/src/views/infra/ClusterAdd.vue
Labels: component:UI

#4047 Look for active templates for VR deployment
  engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java
Labels: NEEDS-GO-NO_GO-URGENTLY, component:templates, component:virtual-router, type:bug

#4032 Suspending the VM prior to deleting snapshots to avoid corruption, th…
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  ui/legacy/l10n/ar.js
  ui/legacy/l10n/ca.js
  ui/legacy/l10n/de_DE.js
  ui/legacy/l10n/en.js
  ui/legacy/l10n/es.js
  ui/legacy/l10n/fr_FR.js
  ui/legacy/l10n/hu.js
  ui/legacy/l10n/it_IT.js
  ui/legacy/l10n/ja_JP.js
  ui/legacy/l10n/ko_KR.js
  ui/legacy/l10n/nb_NO.js
  ui/legacy/l10n/nl_NL.js
  ui/legacy/l10n/pl.js
  ui/legacy/l10n/pt_BR.js
  ui/legacy/l10n/ru_RU.js
  ui/legacy/l10n/zh_CN.js
  ui/legacy/scripts/storage.js
Labels: component:kvm, component:primary-storage, type:bug

#4693 server: fix finding pools for volume migration
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StoragePoolAllocator.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/GarbageCollectingStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/LocalStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/UseLocalForRootAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
  plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: component:migration, type:bug
