Repository apache/cloudstack, pull requests merged in 2021-09, with the labels that each got.

#4852 Allow host cert renewals even if client auth strictness is false
  plugins/ca/root-ca/src/main/java/org/apache/cloudstack/ca/provider/RootCACustomTrustManager.java
  plugins/ca/root-ca/src/main/java/org/apache/cloudstack/ca/provider/RootCAProvider.java
  plugins/ca/root-ca/src/test/java/org/apache/cloudstack/ca/provider/RootCACustomTrustManagerTest.java
  plugins/ca/root-ca/src/test/java/org/apache/cloudstack/ca/provider/RootCAProviderTest.java
Labels: status:needs-testing

#5379 api: List details of template download state for stores corresponding to a zone
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/TemplateDataStoreDao.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
Labels: type:bug

#5403 Add 4.15.2 schema and upgrade path
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41510to41520.java
  engine/schema/src/main/resources/META-INF/db/schema-41510to41520-cleanup.sql
  engine/schema/src/main/resources/META-INF/db/schema-41510to41520.sql
Labels: component:upgrade, component:database

#5333 vmware: delete snapshot disk after backup to secondary storage
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: Severity:Critical

#5339 server: check server capacity when start/deploy a vm
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: status:needs-testing

#5259 usage: create backup usage record for vmId-offeringId pair
  usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java
Labels: type:bug, status:needs-testing

#5387 api, ui: fix NPE with deployVirtualMachine when null boottype
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  ui/src/views/compute/DeployVM.vue
Labels: type:bug

#5402 UI: Add router links to notifications and show error description
  ui/src/components/header/HeaderNotice.vue
  ui/src/utils/plugins.js
  ui/src/views/AutogenView.vue
  ui/src/views/compute/StartVirtualMachine.vue
Labels: component:UI

#5390 server: fix reset sshkey is broken in master/4.16
  server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
Labels: Severity:BLOCKER

#5396 cleanup: kvm-storage - fix misleading error log
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
Labels: Severity:Trivial

#5401 marvin: fix exception logging
  tools/marvin/marvin/cloudstackException.py
Labels: type:cleanup, component:marvin

#3975 Issue #3974 Deploying mysql-ha jar file into its own path...
  packaging/centos7/cloud.spec
  packaging/centos8/cloud.spec
  packaging/systemd/cloudstack-management.default
Labels: type:bug, component:usage-server, status:needs-testing

#5067 Keep volume policies after migrating it to another primary storage
  api/src/main/java/com/cloud/server/TaggedResourceService.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VolumeService.java
  engine/schema/src/main/java/com/cloud/storage/VolumeVO.java
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
  engine/storage/volume/pom.xml
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/VolumeObjectTest.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/VolumeServiceTest.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/test/ConfiguratorTest.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/test/Server.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/test/Server1.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/test/TestConfiguration.java
  engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/test/TestInProcessAsync.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java
  server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java
  server/src/test/java/com/cloud/tags/TaggedResourceManagerImplTest.java
  utils/pom.xml
  utils/src/main/java/org/apache/cloudstack/utils/reflectiontostringbuilderutils/ReflectionToStringBuilderUtils.java
  utils/src/test/java/org/apache/cloudstack/utils/reflectiontostringbuilderutils/ReflectionToStringBuilderUtilsTest.java
Labels: type:enhancement, component:migration, status:needs-testing

#5416 travis: Fix failing test due to change in test name
  .travis.yml
Labels: component:travis

#5358 Fix potential NullPointerException in findStoragePool (VolumeOrchestrator)
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
Labels: type:bug

#5398 Prevent double counting storage pools
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: type:bug, Severity:Minor

#5431 Hide settings button if not on development mode
  ui/src/components/page/GlobalLayout.vue
Labels: component:UI

#5432 api, ui: return default ui pagesize as part of capability response
  api/src/main/java/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  ui/src/store/modules/user.js
Labels: Severity:BLOCKER, component:UI

#5438 ui: Send deployvm api call as post
  ui/src/views/compute/DeployVM.vue
Labels: component:UI

#5441 utils: remove duplicate commons-lang3 dependency
  utils/pom.xml
Labels: component:build, Severity:Minor

#5423 ui: select newly created network in deploy vm
  ui/src/views/compute/wizard/NetworkSelection.vue
Labels: type:enhancement, component:UI

#5439 ui: Fix Scale VM failure - missing args when custom compute offering is selected
  ui/src/views/compute/ScaleVM.vue
Labels: type:bug, component:UI

#5417 server: skip max guest limit check for KVM host
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
Labels: type:enhancement, component:kvm

#4741 VM has wrong network statistics with multiple nics in shared networks
  engine/schema/src/main/java/com/cloud/usage/dao/UsageNetworkDaoImpl.java
  engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
  usage/src/main/java/com/cloud/usage/parser/NetworkUsageParser.java
Labels: component:usage-server, Severity:Minor

#5425 api: Update DNS on changing VM name
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/locales/en.json
  ui/src/config/section/compute.js
  ui/src/views/compute/EditVM.vue
Labels: type:enhancement, component:api

#5424 Updated pod response, grouped the parameters: "startip, endip, vlanid, forsystemvms" as ip range response and added to ipranges parameter.
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/IpRangeResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/PodResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  ui/src/views/infra/network/IpRangesTabManagement.vue
Labels: component:api, status:needs-testing

#5388 kvm: honor migrate.wait and abort vm migration job
  agent/conf/agent.properties
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Labels: component:kvm

#5448 [Vmware] Fix for ovf templates with prefix
  api/src/main/java/com/cloud/agent/api/storage/OVFHelper.java
  core/src/main/java/com/cloud/storage/template/OVAProcessor.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java
  engine/storage/src/test/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImplTest.java
Labels: type:bug, component:vmware, component:templates

#5420 server: allow listing custom offerings for a running VM
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: type:bug

#5369 kvm: Add check if host meets the minimum requirements
  python/lib/cloudutils/serviceConfig.py
  python/lib/cloudutils/syscfg.py
Labels: status:needs-testing

#5453 Updated the event message with proper json format for cmd info and job result
  server/src/main/java/com/cloud/api/ApiSerializerHelper.java
  server/src/main/java/com/cloud/api/ApiServer.java
Labels: type:bug, Severity:Minor

#5460 Display ACL id for the private gateway
  ui/src/components/view/InfoCard.vue
Labels: component:UI

#5449 [Vmware] Add missing condition to cleanup nics if there are commands to send
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Labels: component:vmware, type:cleanup

#5465 ui: Move resource icon to first column for VM list view
  ui/src/components/view/ListView.vue
Labels: component:UI

#4634 Display vlan ip range for specified domainid
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: type:bug

#5464 server: fix list public ip returns duplicated records
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: type:bug, Severity:Minor

#5411 Add New API endpoint: UpdateVlanIpRange
  api/src/main/java/com/cloud/configuration/ConfigurationService.java
  api/src/main/java/com/cloud/event/EventTypes.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/UpdateVlanIpRangeCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/admin/vlan/UpdateVlanIpRangeCmdTest.java
  engine/schema/src/main/java/com/cloud/dc/VlanVO.java
  engine/schema/src/main/java/com/cloud/network/dao/IPAddressDao.java
  engine/schema/src/main/java/com/cloud/network/dao/IPAddressDaoImpl.java
  engine/schema/src/main/java/com/cloud/network/dao/UserIpv6AddressDao.java
  engine/schema/src/main/java/com/cloud/network/dao/UserIpv6AddressDaoImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/test/IPRangeConfig.java
  server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java
  ui/public/locales/en.json
  ui/src/views/infra/network/IpRangesTabPublic.vue
Labels: component:api, status:needs-testing

#5476 UI: Fixes issue during logout as user / domain admin
  ui/src/views/dashboard/UsageDashboard.vue
Labels: type:bug, component:UI

#5459 server: Add support to encrypt https.keystore.password in server.properties
  client/conf/server.properties.in
  client/src/main/java/org/apache/cloudstack/ServerDaemon.java
  utils/src/main/java/com/cloud/utils/crypt/EncryptionSecretKeyChecker.java
  utils/src/main/java/com/cloud/utils/db/DbProperties.java
  utils/src/main/java/com/cloud/utils/server/ServerProperties.java
  utils/src/test/java/com/cloud/utils/crypto/EncryptionSecretKeyCheckerTest.java
Labels: type:enhancement, component:management-server

#5474 change logging during upgrade
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade410to420.java
Labels: Severity:Trivial, complexity:trivial

#5468 api: Fix list templates when no secondary stores present
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImpl.java
Labels: type:bug, component:api

#5472 UI - Fixes search error in selectbox
  ui/src/components/header/ProjectMenu.vue
  ui/src/components/view/SearchView.vue
  ui/src/views/AutogenView.vue
  ui/src/views/compute/AssignInstance.vue
  ui/src/views/compute/CreateKubernetesCluster.vue
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/InstanceTab.vue
  ui/src/views/compute/wizard/NetworkSelection.vue
  ui/src/views/dashboard/CapacityDashboard.vue
  ui/src/views/iam/AddAccount.vue
  ui/src/views/iam/AddUser.vue
  ui/src/views/image/AddKubernetesSupportedVersion.vue
  ui/src/views/image/IsoZones.vue
  ui/src/views/image/RegisterOrUploadIso.vue
  ui/src/views/image/RegisterOrUploadTemplate.vue
  ui/src/views/image/TemplateZones.vue
  ui/src/views/image/UpdateTemplateIsoPermissions.vue
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/infra/AddSecondaryStorage.vue
  ui/src/views/infra/ClusterAdd.vue
  ui/src/views/infra/HostAdd.vue
  ui/src/views/infra/PodAdd.vue
  ui/src/views/infra/network/DedicatedVLANTab.vue
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
  ui/src/views/network/CreateVpc.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/offering/ImportBackupOffering.vue
  ui/src/views/offering/UpdateOfferingAccess.vue
  ui/src/views/storage/CreateVolume.vue
  ui/src/views/storage/UploadLocalVolume.vue
  ui/src/views/tools/ImportUnmanagedInstance.vue
  ui/src/views/tools/ManageInstances.vue
Labels: type:bug, component:UI

#5458 New API endpoint to update pod management network IP range
  api/src/main/java/com/cloud/configuration/ConfigurationService.java
  api/src/main/java/com/cloud/event/EventTypes.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdatePodManagementNetworkIpRangeCmd.java
  engine/schema/src/main/java/com/cloud/dc/dao/DataCenterIpAddressDao.java
  engine/schema/src/main/java/com/cloud/dc/dao/DataCenterIpAddressDaoImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java
Labels: type:enhancement, component:management-server

#4890 Universal sshkey and password manager script
  setup/bindir/cloud-set-guest-sshkey-password-userdata-configdrive.in
Labels: type:enhancement, component:virtual-router, type:config, Severity:Minor

#5454 [UI] Fixes: edit tariff quota and allow user driven backups parameter in Import Backup Offering
  ui/src/views/AutogenView.vue
  ui/src/views/offering/ImportBackupOffering.vue
  ui/src/views/plugins/quota/EditTariffValueWizard.vue
  ui/src/views/plugins/quota/QuotaTariff.vue
Labels: component:UI

#5481 ui: fix create account/user with saml
  ui/src/views/iam/AddAccount.vue
  ui/src/views/iam/AddUser.vue
  ui/src/views/iam/ConfigureSamlSsoAuth.vue
Labels: type:bug, component:saml, Severity:Critical

#5488 ui: Add support to filter role permissions
  ui/src/views/iam/RolePermissionTab.vue
Labels: type:enhancement, component:UI

#5486 travis: fix test/integration/component/test_public_ip.py
  test/integration/component/test_public_ip.py
Labels: component:travis

#5496 ui: recommend adv zone to new users and show basic zone as bottom option
  ui/public/locales/en.json
  ui/src/views/infra/zone/ZoneWizardZoneTypeStep.vue
Labels: component:UI

#3804 Display capability info in listNetwork response
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: type:enhancement, component:virtual-router, status:needs-testing

#5490 UI: Fix VM state column
  ui/src/components/view/ListView.vue
Labels: component:UI

#5480 Refactor GroupByExtension to improve test logic
  framework/db/src/test/java/com/cloud/utils/db/GroupByTest.java
Labels: type:enhancement, type:cleanup

#5428 resource limit: Fix resource limit check on VM start
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
Labels: type:bug

#5455 Improve Veeam Plugin logs
  plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
  plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
Labels: type:enhancement, component:backup

#5503 test_vpc_redundant.py: reduce sleep time from 1 hour to 21 mins
  test/integration/smoke/test_vpc_redundant.py
Labels: type:improvement, component:marvin

#4617 Provide option to force delete the project
  api/src/main/java/com/cloud/projects/ProjectService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/project/DeleteProjectCmd.java
  server/src/main/java/com/cloud/projects/ProjectManagerImpl.java
  server/src/test/java/com/cloud/projects/MockProjectManagerImpl.java
  tools/marvin/marvin/lib/base.py
  ui/src/config/section/project.js
Labels: type:enhancement, component:projects

#5469 server: add vm boot details for start vm api
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug, status:needs-testing

#5520 Allow users (User account Role) to delete / archive events
  ui/src/config/section/event.js
Labels: component:UI

#5522 merge main
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: component:UI

#5526 UI - Fixes modal width by device screen
  ui/src/components/view/ListView.vue
  ui/src/components/view/QuickView.vue
  ui/src/views/AutogenView.vue
  ui/src/views/plugins/quota/EditTariffValueWizard.vue
  ui/src/views/plugins/quota/QuotaTariff.vue
  ui/tests/common/index.js
  ui/tests/mock/mockStore.js
  ui/tests/unit/views/AutogenView.spec.js
  ui/tests/unit/views/compute/MigrateWizard.spec.js
Labels: component:UI

#5504 Fix permission issue during Diagnostic service garbage collection
  server/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImpl.java
Labels: type:bug

#5510 Fix export snapshot and template to secondary storage to export only required disk
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware, Severity:Critical
