Repository apache/cloudstack, pull requests merged in 2021-07, with the labels that each got.

#5106 tests: Fix test failures for Local storage and Basic zones
  test/integration/smoke/test_direct_download.py
  test/integration/smoke/test_domain_network_offerings.py
  test/integration/smoke/test_domain_vpc_offerings.py
  test/integration/smoke/test_primary_storage.py
  test/integration/smoke/test_vm_life_cycle.py
Labels: component:integration-test

#4843 ui: deployvm - Add option to stay on page
  ui/public/locales/en.json
  ui/src/views/compute/DeployVM.vue
Labels: component:UI

#5125 volume: Fix deletion of Uploaded volumes
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: type:bug

#5142 Fix NPE during removal of VM from Network
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
Labels: type:bug

#5154 Fix NPE when no recipients configured for sending alerts
  server/src/main/java/com/cloud/alert/AlertManagerImpl.java
Labels: type:bug, type:regression

#5176 [UI] secondary storage - Display text and change the badge color of the Read-only column
  ui/public/locales/en.json
  ui/src/components/view/ListView.vue
  ui/src/components/widgets/Status.vue
  ui/src/config/section/infra/secondaryStorages.js
  ui/src/views/AutogenView.vue
Labels: component:UI

#5167 UI - zone wizard - fix undefined property when setting RBD primary storage
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: component:UI

#5165 Prevent starting a VM in destroyed state (or any state but Stopped)
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Labels: status:ready-for-merge

#4037 Document cidrlist parameter deprecation
  api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreatePortForwardingRuleCmd.java
Labels: component:api, type:bug

#4575 Enhance log messages with host name
  engine/orchestration/src/main/java/com/cloud/agent/manager/ClusteredAgentManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/schema/src/main/java/com/cloud/dc/ClusterVO.java
  engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
  server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/main/java/com/cloud/resource/RollingMaintenanceManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
  server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
Labels: component:logging, type:enhancement

#5182 ui: Fix traversal to domain details via domain router-link of a resource
  ui/src/components/view/InfoCard.vue
Labels: component:UI

#5064 ui: refactor get api params in forms
  ui/src/main.js
  ui/src/utils/plugins.js
  ui/src/views/compute/CreateKubernetesCluster.vue
  ui/src/views/compute/CreateSSHKeyPair.vue
  ui/src/views/compute/CreateSnapshotWizard.vue
  ui/src/views/compute/DestroyVM.vue
  ui/src/views/compute/EditVM.vue
  ui/src/views/compute/ScaleKubernetesCluster.vue
  ui/src/views/compute/StartVirtualMachine.vue
  ui/src/views/compute/UpgradeKubernetesCluster.vue
  ui/src/views/iam/AddAccount.vue
  ui/src/views/iam/AddUser.vue
  ui/src/views/iam/ChangeUserPassword.vue
  ui/src/views/iam/CreateRole.vue
  ui/src/views/iam/EditUser.vue
  ui/src/views/iam/ImportRole.vue
  ui/src/views/image/AddKubernetesSupportedVersion.vue
  ui/src/views/image/IsoZones.vue
  ui/src/views/image/RegisterOrUploadIso.vue
  ui/src/views/image/RegisterOrUploadTemplate.vue
  ui/src/views/image/TemplateZones.vue
  ui/src/views/image/UpdateKubernetesSupportedVersion.vue
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/infra/InfraSummary.vue
  ui/src/views/infra/network/EditTrafficLabel.vue
  ui/src/views/infra/routers/RouterHealthCheck.vue
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
  ui/src/views/network/CreateVlanIpRange.vue
  ui/src/views/network/CreateVpc.vue
  ui/src/views/network/CreateVpnCustomerGateway.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/offering/ImportBackupOffering.vue
  ui/src/views/project/AddAccountOrUserToProject.vue
  ui/src/views/project/InvitationTokenTemplate.vue
  ui/src/views/project/InvitationsTemplate.vue
  ui/src/views/storage/AttachVolume.vue
  ui/src/views/storage/CreateVolume.vue
  ui/src/views/storage/TakeSnapshot.vue
  ui/src/views/storage/UploadLocalVolume.vue
  ui/tests/common/index.js
Labels: component:UI, type:cleanup

#5136 apiserver : Ensure required parameters are not empty
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/BaseRolePermissionCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/CreateRoleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ImportRoleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/CreateProjectRoleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/CreateProjectRolePermissionCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/ProjectRoleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/UpdateProjectRolePermissionCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/diagnostics/RunDiagnosticsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/ha/ConfigureHAForHostCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/ha/ListHostHAProvidersCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/network/DeleteManagementNetworkIpRangeCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/IssueOutOfBandManagementPowerActionCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/project/CreateProjectCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/resource/ListDetailOptionsCmd.java
  server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
Labels: Severity:Minor, type:bug

#5178 [UI] zone wizard: change edit traffic type form of VMware
  ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
Labels: component:UI

#5197 UI: fix NIC table on instance view
  ui/src/core/lazy_lib/components_use.js
Labels: component:UI

#5199 UI: deploy VM - FIX missing custom iops field
  ui/public/locales/en.json
  ui/src/config/section/offering.js
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/wizard/ComputeSelection.vue
  ui/src/views/compute/wizard/DiskOfferingSelection.vue
  ui/src/views/compute/wizard/DiskSizeSelection.vue
  ui/src/views/storage/CreateVolume.vue
Labels: component:UI

#5030 refactor: migrate vm with storage
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDao.java
  engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
  server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:cleanup

#5073 systemvmtemplate: use latest LTS kernel from buster-ports
  tools/appliance/systemvmtemplate/http/preseed.cfg
  tools/appliance/systemvmtemplate/scripts/apt_upgrade.sh
  tools/appliance/systemvmtemplate/scripts/configure_grub.sh
  tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh
  tools/appliance/systemvmtemplate/template.json
Labels: Severity:BLOCKER, systemvm-template-change

#5012 KVM NFS disk IO driver supporting IO_URING
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: component:kvm, type:enhancement

#5193 kvm: pre-add 32 PCI controller for hot-plug issue on ARM64/aarch64
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
Labels: component:kvm, platform:arm64, platform:raspberrypi

#4790 Externalize secondary storage capacity threshold
  engine/components-api/src/main/java/com/cloud/capacity/CapacityManager.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/StorageOrchestrator.java
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
Labels: Severity:Minor, component:agent, status:needs-testing, type:enhancement

#4640 Added disk provisioning type support for VMWare
  api/src/main/java/com/cloud/storage/Storage.java
  api/src/main/java/com/cloud/storage/StorageService.java
  api/src/main/java/org/apache/cloudstack/api/BaseListCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/storage/ListStoragePoolsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/storage/UpdateStorageCapabilitiesCmd.java
  core/src/main/java/com/cloud/agent/api/GetStoragePoolCapabilitiesAnswer.java
  core/src/main/java/com/cloud/agent/api/GetStoragePoolCapabilitiesCommand.java
  core/src/main/java/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StoragePoolAllocator.java
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/StoragePoolDetailVO.java
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
  engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategyTest.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageSubsystemCommandHandler.java
  plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  test/integration/smoke/test_disk_offerings.py
  test/integration/smoke/test_disk_provisioning_types.py
  tools/apidoc/gen_toc.py
  tools/marvin/marvin/lib/base.py
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualStorageObjectManagerMO.java
Labels: component:primary-storage, component:vmware, type:new-feature

#4585 Externalize kvm agent storage timeout configuration
  agent/conf/agent.properties
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  agent/src/main/java/com/cloud/agent/properties/AgentPropertiesFileHandler.java
  agent/src/test/java/com/cloud/agent/properties/AgentPropertiesFileHandlerTest.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
Labels: component:kvm, type:enhancement

#5218 Revert "Externalize kvm agent storage timeout configuration"
  agent/conf/agent.properties
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  agent/src/main/java/com/cloud/agent/properties/AgentPropertiesFileHandler.java
  agent/src/test/java/com/cloud/agent/properties/AgentPropertiesFileHandlerTest.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
Labels: Severity:Critical, type:regression

#5210 api: Add 'created' field to API response
  api/src/main/java/com/cloud/network/Network.java
  api/src/main/java/com/cloud/network/NetworkProfile.java
  api/src/main/java/com/cloud/network/vpc/Vpc.java
  api/src/main/java/com/cloud/offering/NetworkOffering.java
  api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/ProjectResponse.java
  engine/schema/src/main/java/com/cloud/network/vpc/VpcVO.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/NetworkOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/ProjectJoinDaoImpl.java
Labels: Severity:Minor, component:UI

#5222 ui: Replace bulk delete icons
  ui/src/views/image/IsoZones.vue
  ui/src/views/image/TemplateZones.vue
  ui/src/views/network/EgressRulesTab.vue
  ui/src/views/network/FirewallRules.vue
  ui/src/views/network/IpAddressesTab.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/network/PortForwarding.vue
Labels: component:UI

#5221 ui: Fix async poll job
  ui/src/views/compute/MigrateVMStorage.vue
  ui/src/views/network/EgressRulesTab.vue
  ui/src/views/network/FirewallRules.vue
  ui/src/views/network/IpAddressesTab.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/network/PortForwarding.vue
Labels: component:UI

#5163 add entity-type to message when no UUID is found for a DB ID
  server/src/main/java/com/cloud/uuididentity/UUIDManagerImpl.java
Labels: Severity:Trivial, complexity:trivial, type:enhancement

#5149 Refactor and improvements for method com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.createVMFromSpec()
  api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: status:needs-testing, type:cleanup

#5186 Remove condition that are prevent resizing for root volumes (vmware)
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  test/integration/component/test_rootvolume_resize.py
  test/integration/smoke/test_volumes.py
Labels: component:vmware, type:new-feature

#5206 UI: only display host information, if they are relevant
  ui/src/views/infra/HostInfo.vue
Labels: component:UI

#5233 ui bug fix: scalevm is disabled when vm is Stopped
  ui/src/config/section/compute.js
Labels: component:UI

#5225 Fix of shrinking volumes with QCOW2 format
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:managed-storage, type:bug

#5075 ui: vmware vm import-unmanage
  api/src/main/java/org/apache/cloudstack/api/response/UnmanagedInstanceResponse.java
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
  ui/public/locales/en.json
  ui/src/components/CheckBoxInputPair.vue
  ui/src/components/CheckBoxSelectPair.vue
  ui/src/components/view/InfoCard.vue
  ui/src/components/view/SearchView.vue
  ui/src/components/widgets/Status.vue
  ui/src/config/router.js
  ui/src/config/section/tools.js
  ui/src/views/AutogenView.vue
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/ScaleVM.vue
  ui/src/views/compute/wizard/ComputeSelection.vue
  ui/src/views/compute/wizard/MultiDiskSelection.vue
  ui/src/views/compute/wizard/MultiNetworkSelection.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/tools/ImportUnmanagedInstance.vue
  ui/src/views/tools/ManageInstances.vue
Labels: component:UI, status:needs-testing, type:enhancement

#5237 [UI] Add Shift key for noVNC consoles
  systemvm/agent/noVNC/app/images/shift.png
  systemvm/agent/noVNC/app/ui.js
  systemvm/agent/noVNC/vnc.html
Labels: component:UI

#5205 ui: fix create shared network with multi-zone
  ui/src/views/network/CreateSharedNetworkForm.vue
Labels: component:UI

#5224 ui: submit form with false boolean params
  ui/src/views/AutogenView.vue
Labels: component:UI

#5239 Externalize KVM Agent storage's timeout configuration
  agent/conf/agent.properties
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  agent/src/main/java/com/cloud/agent/properties/AgentPropertiesFileHandler.java
  agent/src/test/java/com/cloud/agent/properties/AgentPropertiesFileHandlerTest.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
Labels: component:kvm, type:enhancement

#4768 display nics deviceid and order nics by deviceid on Nics tab of insta…
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  engine/schema/src/main/resources/META-INF/db/schema-41510to41600.sql
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
  ui/src/views/network/NicsTable.vue
Labels: component:UI, component:api, type:enhancement

#4257 remove the unnecessary check for tags when migrating volumes
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:primary-storage, type:bug

#5252 ui: fix import instance form root disk label
  ui/src/views/tools/ImportUnmanagedInstance.vue
Labels: component:UI

#4714 Cleaning up code and enhancing a few IP management logs
  engine/schema/src/main/java/com/cloud/dc/DataCenterVO.java
  engine/schema/src/main/java/com/cloud/offerings/dao/NetworkOfferingServiceMapDaoImpl.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
Labels: type:cleanup
