Repository apache/cloudstack, pull requests merged in 2021-04, with the labels that each got.

#4867 ui: assignVM: Set isrecursive to false when fetching accounts
  ui/src/views/compute/AssignInstance.vue
Labels: component:UI

#4862 ui: Display root disk size in Compute offering details
  ui/public/locales/en.json
  ui/src/components/view/DetailsTab.vue
  ui/src/config/section/offering.js
Labels: component:UI

#4804 server: allow copy cross-zone templates to other zone
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
Labels: type:bug, type:cleanup

#4675 Bug fix in displaying public IP address of shared networks
  .travis.yml
  engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  test/integration/component/test_public_ip.py
  test/integration/smoke/test_network.py
Labels: component:networking, status:needs-testing

#3944 vpc/server: Fix network statistics for vpc
  api/src/main/java/com/cloud/network/VirtualNetworkApplianceService.java
  engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDaoImpl.java
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
  server/src/main/java/com/cloud/network/rules/NicPlugInOutRules.java
  server/src/main/java/com/cloud/network/rules/VirtualNetworkApplianceFactory.java
  server/src/test/java/com/cloud/vpc/MockVpcVirtualNetworkApplianceManager.java
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
Labels: component:vpc, type:bug

#4745 ui: allow docHelp override using config.json
  ui/public/config.json
  ui/src/components/view/ActionButton.vue
  ui/src/config/router.js
  ui/src/main.js
  ui/src/utils/plugins.js
  ui/tests/common/index.js
Labels: component:UI

#4869 VR: fix rsyslog compresses log files but not release disk space in VR
  systemvm/debian/etc/logrotate.d/rsyslog
Labels: Severity:Critical, component:virtual-router

#4870 kvm: remove unnecessary new String
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgTest.java
Labels: Severity:Trivial, complexity:trivial, type:cleanup

#4893 Remove .env.local
  ui/.env.local
Labels: component:UI, type:cleanup

#4676 Display public ip addresses for shared network
  ui/src/config/section/network.js
  ui/src/views/compute/InstanceTab.vue
  ui/src/views/network/IpAddressesTab.vue
Labels: component:UI

#4816 xenserver: retrieve correct name-label for presetup store
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateVolumeCommandWrapper.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageCommandWrapper.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixCreateCommandWrapper.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixDeleteStoragePoolCommandWrapper.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixModifyStoragePoolCommandWrapper.java
  plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java
Labels: component:XenServer

#4769 UI: Save and auto-expand list domain when reloading
  ui/src/components/view/TreeView.vue
  ui/src/store/getters.js
  ui/src/store/modules/user.js
  ui/src/store/mutation-types.js
  ui/src/views/iam/DomainView.vue
Labels: component:UI, type:bug

#4666 Fix bug in creating shared network
  ui/src/views/network/CreateSharedNetworkForm.vue
Labels: Severity:Critical, component:UI, component:networking, component:primate

#4473 test cleanup
  test/integration/smoke/test_accounts.py
  test/integration/smoke/test_affinity_groups_projects.py
  test/integration/smoke/test_async_job.py
  test/integration/smoke/test_hostha_simulator.py
Labels: component:integration-test, type:cleanup

#4802 wiremock version 2.11 is incompatible with java 11
  pom.xml
Labels: component:unit-test, type:bug

#4851 [Vmware] Fix worker VMs hardware version small bug
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
  vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMOTest.java
Labels: component:vmware, type:bug

#4892 UI: Physical Network Setup in Zone Wizard
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
  ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
Labels: component:UI

#4099 using forked version of trilead-ssh2 (from org.jenkins-ci)
  pom.xml
  test/pom.xml
  utils/pom.xml
  utils/src/main/java/com/cloud/utils/ssh/SshHelper.java
Labels: component:security, type:enhancement

#4679 Disable shrinking QCOW2 volumes
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: type:bug

#4672 hypervisor: XCP-ng 8.2 support
  engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java
Labels: component:XenServer, type:enhancement

#4801 skip livemigration for centos
  test/integration/smoke/test_vm_life_cycle.py
Labels: component:integration-test

#4717 Added recursive fetch of child domains for listUsageRecords API call
  api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java
  server/src/main/java/com/cloud/usage/UsageServiceImpl.java
Labels: component:api, type:enhancement

#4847 Restricting http access on VR to internal network
  systemvm/debian/etc/iptables/iptables-dhcpsrvr
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
  systemvm/debian/opt/cloud/bin/cs/CsApp.py
Labels: Severity:Minor, component:security, component:virtual-router, type:enhancement

#4899 Fix orphan entry on ldap trust map after account removal
  plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java
Labels: component:LDAP, type:bug

#4910 UI: fix login on UI
  ui/src/api/index.js
Labels: component:UI

#4706 Improve logs on KVMHostActivityChecker
  engine/schema/src/main/java/com/cloud/host/HostVO.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/kvm/ha/KVMHostActivityChecker.java
Labels: component:kvm, status:ready-for-merge, type:enhancement

#4573 Add support to StartTLS on Quota's mailing
  framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java
  framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaConfig.java
  plugins/database/quota/src/main/java/org/apache/cloudstack/quota/QuotaServiceImpl.java
Labels: Severity:Trivial, complexity:trivial, type:enhancement

#4493 Recover VM not able to attach the data disks which were attached before destroy
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: Severity:Critical

#4300 engine: add support for VMware 7.0 dependency and hypervisor capability
  core/src/main/java/com/cloud/agent/api/GetVmVncTicketAnswer.java
  core/src/main/java/com/cloud/agent/api/GetVmVncTicketCommand.java
  engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  pom.xml
  server/src/main/java/com/cloud/servlet/ConsoleProxyClientParam.java
  server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java
  services/console-proxy/server/pom.xml
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyClientParam.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyHttpHandlerHelper.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVNCHandler.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/websocket/WebSocketReverseProxy.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware

#4212 Migrate/Stop VMs with local storage when preparing host for maintenance
  engine/components-api/src/main/java/com/cloud/resource/ResourceManager.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManager.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:local-storage, status:ready-for-merge, type:enhancement

#4933 UI: Disabled root disk size customization if Service Offering has a fixed size
  ui/src/views/compute/DeployVM.vue
Labels: component:UI, status:ready-for-merge

#4926 Add UnavailableCommandException at ExceptionErrorCodeMap
  utils/src/main/java/com/cloud/utils/exception/CSExceptionErrorCode.java
Labels: component:api, component:logging

#4938 cloudian: Set cloudian.connector.enabled as not dynamic
  plugins/integrations/cloudian/src/main/java/org/apache/cloudstack/cloudian/CloudianConnector.java
Labels: component:plugin, type:bug

#4702 Improve logs on IpmitoolOutOfBandManagementDriver
  plugins/outofbandmanagement-drivers/ipmitool/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolOutOfBandManagementDriver.java
Labels: Severity:Minor, complexity:simpel, component:logging, type:improvement

#4758 vmware: fix stopped VM volume migration
  core/src/main/java/com/cloud/agent/api/storage/MigrateVolumeCommand.java
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java
  plugins/hypervisors/vmware/src/test/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategyTest.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:vmware

#4944 Fix NPE on template garbage collection on primary storage
  engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java
Labels: component:templates, type:cleanup

#4949 ui: Show domain path instead of name
  ui/src/components/view/DedicateDomain.vue
  ui/src/views/compute/AssignInstance.vue
  ui/src/views/compute/CreateSSHKeyPair.vue
  ui/src/views/iam/AddAccount.vue
  ui/src/views/iam/AddUser.vue
  ui/src/views/infra/network/DedicatedVLANTab.vue
  ui/src/views/infra/network/IpRangesTabPublic.vue
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
Labels: component:UI

#4946 api: fix disk/service offering volume response keys
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
Labels: component:api

#4907 vmware: Add force parameter to iso attach/detach operations
  api/src/main/java/com/cloud/template/TemplateApiService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/iso/AttachIsoCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/iso/DetachIsoCmd.java
  core/src/main/java/org/apache/cloudstack/storage/command/AttachCommand.java
  core/src/main/java/org/apache/cloudstack/storage/command/DettachCommand.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/src/config/section/compute.js
  ui/src/views/compute/AttachIso.vue
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware

#4971 ui: Display 'Add LDAP Account' button when LDAP configuration is added
  ui/src/store/modules/user.js
  ui/src/views/AutogenView.vue
Labels: component:UI

#4957 vmware cks: Guard k8s cluster root disk resize if no root disk size passed
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  test/integration/smoke/test_scale_vm.py
Labels: component:cks, component:vmware, type:regression

#4901 [Vmware] Make deploy-as-is optional
  api/src/main/java/org/apache/cloudstack/api/command/user/template/RegisterTemplateCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/user/template/RegisterTemplateCmdTest.java
  server/src/main/java/com/cloud/template/TemplateAdapterBase.java
  test/integration/smoke/test_kubernetes_clusters.py
  test/integration/smoke/test_storage_policy.py
  test/integration/smoke/test_templates.py
  test/integration/smoke/test_volumes.py
  tools/marvin/marvin/lib/base.py
  tools/marvin/marvin/lib/common.py
  ui/public/locales/en.json
  ui/src/views/image/RegisterOrUploadTemplate.vue
Labels: component:vmware

#4964 ui: Fix Settings Tab view
  ui/src/components/view/SettingsTab.vue
Labels: component:UI

#4915 Allow to upgrade service offerings from local <> shared storage pools
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: type:bug

#4979 ui: show domain paths for offering domain selection
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/offering/UpdateOfferingAccess.vue
Labels: component:UI
