Repository apache/cloudstack, pull requests merged in 2021-05, with the labels that each got.

#4987 ui: Adding success message for DomainActionForm
  ui/src/views/iam/DomainActionForm.vue
Labels: component:UI

#4976 Fixed error when passing shell reserved characters to setup databases
  setup/bindir/cloud-setup-databases.in
Labels: component:management-server

#5001 server: NPE may cause management server to not start
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug

#4842 ui: add tooltips for actions in tab
  ui/src/components/view/DetailSettings.vue
  ui/src/components/view/InfoCard.vue
  ui/src/components/view/ListView.vue
  ui/src/components/view/SearchView.vue
  ui/src/components/view/SettingsTab.vue
  ui/src/components/view/TooltipButton.vue
  ui/src/views/compute/InstanceTab.vue
  ui/src/views/compute/backup/BackupSchedule.vue
  ui/src/views/iam/RolePermissionTab.vue
  ui/src/views/iam/RuleDelete.vue
  ui/src/views/iam/SSLCertificateTab.vue
  ui/src/views/image/IsoZones.vue
  ui/src/views/image/TemplateZones.vue
  ui/src/views/infra/network/DedicatedVLANTab.vue
  ui/src/views/infra/network/IpRangesTabManagement.vue
  ui/src/views/infra/network/IpRangesTabPublic.vue
  ui/src/views/infra/network/IpRangesTabStorage.vue
  ui/src/views/infra/network/providers/ProviderListView.vue
  ui/src/views/infra/zone/IpAddressRangeForm.vue
  ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
  ui/src/views/network/AclListRulesTab.vue
  ui/src/views/network/EgressRulesTab.vue
  ui/src/views/network/FirewallRules.vue
  ui/src/views/network/GuestIpRanges.vue
  ui/src/views/network/IngressEgressRuleConfigure.vue
  ui/src/views/network/InternalLBAssignedVmTab.vue
  ui/src/views/network/IpAddressesTab.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/network/PortForwarding.vue
  ui/src/views/network/StaticRoutesTab.vue
  ui/src/views/project/AccountsTab.vue
  ui/src/views/project/InvitationsTemplate.vue
  ui/src/views/project/iam/ProjectRolePermissionTab.vue
  ui/src/views/project/iam/ProjectRoleTab.vue
  ui/src/views/storage/FormSchedule.vue
  ui/src/views/storage/ScheduledSnapshots.vue
  ui/src/views/storage/TakeSnapshot.vue
Labels: component:UI

#4955 Improve logs on SecondaryStorageManagerImpl and few refactors
  engine/schema/src/main/java/com/cloud/dc/DataCenterVO.java
  engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
  services/secondary-storage/controller/src/test/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerTest.java
Labels: type:improvement

#4704 Improve logs on kvmvmactivity.sh
  scripts/vm/hypervisor/kvm/kvmvmactivity.sh
Labels: component:agent, component:kvm, type:improvement

#4705 Improve logs on KVMHAVMActivityChecker
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHABase.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAChecker.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAVMActivityChecker.java
Labels: component:logging, status:ready-for-merge, type:improvement

#4644 server: destroy ssvm, cpvm on last host maintenance
  api/src/main/java/com/cloud/agent/api/Command.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentAttache.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
  server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
  server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/test/java/com/cloud/ha/HighAvailabilityManagerImplTest.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
Labels: Severity:Minor

#5033 Fixed invalid ostypeid when not using deployasis
  api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
Labels: component:api, component:templates, type:bug

#5003 UI: Make 'ACL' field as mandatory and add warning message for default_allow and default_deny
  ui/public/locales/en.json
  ui/src/views/network/VpcTab.vue
  ui/src/views/network/VpcTiersTab.vue
Labels: component:UI

#5026 Add startdate formate to documents.
  api/src/main/java/org/apache/cloudstack/api/command/user/job/ListAsyncJobsCmd.java
Labels: component:api, component:documentation

#4881 Externalize OOBM background task's interval
  api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementService.java
  server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
Labels: complexity:trivial, status:ready-for-merge, type:enhancement

#4631 fix: create template with Marvin
  tools/marvin/marvin/lib/base.py
Labels: Severity:Minor, component:marvin, type:bug

#5032 [Vmware] Fix worker VM invalid numeric value
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Labels: component:vmware, type:bug

#5049 FIX Network with SG Disabled still has security group script adding rules on KVM
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Labels: Severity:BLOCKER, component:advanced-networking, component:kvm, component:security-group

#5028 Removed download icon when ISO is not extractable for users
  ui/src/config/section/image.js
Labels: component:UI, type:bug

#5017 Usage: usage generated for destroyed VMs with no backups
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  ui/public/locales/en.json
  ui/src/config/section/compute.js
  ui/src/views/compute/DestroyVM.vue
Labels: component:backup, type:bug
