Repository apache/cloudstack, pull requests merged in 2022-06, with the labels that each got.

#6441 Fix deploy from ISO with custom disk offering
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug

#6443 UI: Fixes error when creating volume from the snapshot
  ui/src/config/section/storage.js
  ui/src/views/storage/CreateVolume.vue
Labels: type:bug, component:UI

#6445 UI: fix create vpc private gw by regular users
  ui/src/views/network/VpcTab.vue
Labels: type:bug, component:UI

#6436 UI: Fix hypervisor not selected by default when deploying VM from ISO
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:UI

#6449 Specify vm snapshot uuid in response over db id in the async job response
  api/src/main/java/org/apache/cloudstack/api/command/user/vmsnapshot/CreateVMSnapshotCmd.java
Labels: type:bug, component:api

#6307 fix pseudo random behaviour in pool selection
  api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
  engine/components-api/src/main/java/com/cloud/storage/StorageUtil.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
  engine/storage/src/test/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocatorTest.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
  test/integration/smoke/test_attach_multiple_volumes.py
Labels: type:bug, component:api, component:networking, Python, component:orchestration, component:integration-test, component:storage

#5442 some component tests fixes
  test/integration/broken/test_vpc_vm_life_cycle.py
  test/integration/component/test_host_ha.py
  test/integration/component/test_rootvolume_resize.py
Labels: Python, component:integration-test

#6461 api: Add vpc name and uuid to VMs list response (nics) and nics response
  api/src/main/java/org/apache/cloudstack/api/response/NicResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
Labels: type:enhancement, component:api

#6462 UI: Fixes UI break with SAML authentication
  ui/src/store/modules/user.js
Labels: component:api, component:UI, component:database, component:agent, component:build, component:orchestration, distro:ubuntu, component:storage

#6468 UI: Fixes ui error when upgrade virtual routers from virtual router list
  ui/src/config/section/infra/routers.js
Labels: type:bug, component:UI

#6429 UI: add a provider for primary storage when adding zone wizard
  ui/src/views/infra/zone/StaticInputsForm.vue
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: component:UI

#6472 kvm: upgrade libvirt-java to v0.5.3
  pom.xml
Labels: component:build

#6481 UI primarystorage linstor fixes
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: component:api, component:UI, component:database, component:agent, component:build, component:orchestration, distro:ubuntu, component:storage

#6484 ui: fix ui hang on offering creation with no zone
  ui/src/views/compute/CreateKubernetesCluster.vue
  ui/src/views/image/AddKubernetesSupportedVersion.vue
  ui/src/views/image/RegisterOrUploadIso.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
Labels: component:UI

#6477 Fix rpfilter config values from integer to boolean on upgrade path
  engine/schema/src/main/resources/META-INF/db/schema-41700to41710.sql
Labels: type:bug, type:config

#6326 Removed unused labels
  ui/public/locales/ar.json
  ui/public/locales/ca.json
  ui/public/locales/de_DE.json
  ui/public/locales/el_GR.json
  ui/public/locales/en.json
  ui/public/locales/es.json
  ui/public/locales/fr_FR.json
  ui/public/locales/hi.json
  ui/public/locales/hu.json
  ui/public/locales/it_IT.json
  ui/public/locales/ko_KR.json
  ui/public/locales/nb_NO.json
  ui/public/locales/nl_NL.json
  ui/public/locales/pl.json
  ui/public/locales/pt_BR.json
  ui/public/locales/ru_RU.json
  ui/public/locales/zh_CN.json
Labels: component:UI

#6420 Enable CPU cap for SSVMs and CPVMs
  engine/schema/src/main/resources/META-INF/db/schema-41710to41800.sql
  server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
Labels: component:secondary-storage, component:ssvm

#6367 Updated PowerFlex/ScaleIO storage plugin to support separate (storage) network for Hosts(KVM)/Storage connection.
  core/src/main/java/com/cloud/agent/api/ModifyStoragePoolAnswer.java
  core/src/main/java/com/cloud/agent/api/ModifyStoragePoolCommand.java
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtModifyStoragePoolCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ManagedNfsStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePoolTest.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClient.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImpl.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/provider/ScaleIOHostListener.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/util/ScaleIOUtil.java
  plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycleTest.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStoragePool.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/test/java/com/cloud/storage/listener/StoragePoolMonitorTest.java
Labels: component:kvm, component:primary-storage, component:iscsi, component:api, component:managed-storage, component:agent, component:build, component:orchestration, distro:ubuntu, component:storage

#6410 Add check for update only name and/or description of disk offering
  ui/src/views/AutogenView.vue
Labels: component:UI

#6475 UI: fix create tags for LB rules
  ui/src/views/network/LoadBalancing.vue
Labels: type:bug, component:UI

#6502 UI: Change notification title when resizing volume
  ui/public/locales/en.json
  ui/src/views/storage/ResizeVolume.vue
Labels: component:UI

#6493 UI fix message.add.vpn.customer.gateway.failed when catched error
  ui/src/views/network/CreateVpnCustomerGateway.vue
  ui/src/views/network/VpcTab.vue
Labels: component:UI

#6474 Allow for arbitrary disk offering details to be saved/displayed
  api/src/main/java/org/apache/cloudstack/api/response/DiskOfferingResponse.java
  server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Labels: type:enhancement, component:api

#6331 [KVM improve logs in migrate VM process
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
Labels: component:kvm

#6154 Updating and adding missing labels on pt_BR locale
  ui/public/locales/pt_BR.json
Labels: type:enhancement, component:UI, Severity:Minor

#6496 Fix global setting reference for max secondary storage
  api/src/main/java/com/cloud/user/ResourceLimitService.java
  core/src/main/java/org/apache/cloudstack/storage/command/TemplateOrVolumePostUploadCommand.java
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Labels: component:secondary-storage, component:ssvm, component:api, component:storage

#6476 server: update lb rule with new protocol
  server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
Labels: type:bug, component:networking

#6446 CKS: add created to k8s cluster and k8s version
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesSupportedVersion.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesSupportedVersionVO.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesSupportedVersionResponse.java
  ui/src/config/section/compute.js
  ui/src/config/section/image.js
Labels: component:UI, component:kubernetes

#6274 Enable flake8 rule W292 No newline at end of file
  .github/linters/.flake8
  api/test/integration/api/__init__.py
  api/test/integration/api/test/__init__.py
  api/test/integration/api/test/account/__init__.py
  plugins/hypervisors/baremetal/src/main/resources/security_group_agent/security_group_agent/xmlobject.py
  plugins/hypervisors/ovm/src/main/scripts/vm/hypervisor/ovm/OvmLoggerModule.py
  plugins/hypervisors/ovm/src/main/scripts/vm/hypervisor/ovm/OvmObjectModule.py
  test/integration/broken/test_vpc_vm_life_cycle.py
  test/integration/smoke/test_annotations.py
  test/integration/smoke/test_network.py
  test/integration/smoke/test_persistent_network.py
  test/integration/smoke/test_scale_vm.py
  test/selenium/lib/initialize.py
Labels: component:api, Python, component:integration-test

#6142 UI: Remove unused dependencies and fix travis build
  ui/package-lock.json
  ui/package.json
Labels: type:bug, component:UI

#6518 Added information about device id 0 for root volume while attaching to VM
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/AttachVolumeCmd.java
Labels: component:api
