Repository apache/cloudstack, pull requests merged in 2022-08, with the labels that each got.

#6592 ui: fix vpc loadbalancer listing for admins
  ui/src/views/network/VpcTiersTab.vue
Labels: component:UI

#6506 externalizes used protocol to upload isos, volumes and templates
  api/src/main/java/com/cloud/storage/VolumeApiService.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
  systemvm/debian/etc/apache2/vhost.template
  systemvm/debian/opt/cloud/bin/setup/common.sh
  systemvm/debian/opt/cloud/bin/setup/secstorage.sh
  utils/src/main/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtil.java
  utils/src/test/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtilTest.java
Labels: component:secondary-storage, component:virtual-router, component:ssvm, component:api, component:networking, component:storage

#6582 [Veeam] Find VBRViDatastore and VBRServer by name
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  server/src/test/java/org/apache/cloudstack/backup/BackupManagerTest.java
Labels: component:backup

#6600 ui: fix icon for vr migrate storage
  ui/src/config/section/infra/routers.js
Labels: component:UI

#6607 UI: Fixes notification error can't close when exit config limit tab
  ui/src/components/view/ResourceLimitTab.vue
Labels: component:UI

#6597 Fix spelling
  api/src/main/java/org/apache/cloudstack/api/BaseCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/UpdateSnapshotPolicyCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/RestoreVMCmd.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade2214to30.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade305to306.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade410to420.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
  plugins/deployment-planners/user-concentrated-pod/src/main/java/com/cloud/deploy/UserConcentratedPodPlanner.java
  plugins/hypervisors/hyperv/DotNet/ServerResource/HypervResource/Utils.cs
  plugins/hypervisors/hyperv/DotNet/ServerResource/HypervResource/WmiCallsV2.cs
  plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockStorageManagerImpl.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetscalerResource.java
  plugins/user-authenticators/ldap/src/test/groovy/org/apache/cloudstack/ldap/LdapManagerImplSpec.groovy
  plugins/user-authenticators/ldap/src/test/groovy/org/apache/cloudstack/ldap/LinkDomainToLdapCmdSpec.groovy
  plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LinkAccountToLdapCmdTest.java
  plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LinkDomainToLdapCmdTest.java
  plugins/user-authenticators/saml2/src/test/java/org/apache/cloudstack/saml/SAML2AuthManagerImplTest.java
  scripts/storage/secondary/cloud-install-sys-tmplt
  scripts/storage/secondary/setup-sysvm-tmplt
  scripts/vm/network/ovs-pvlan-kvm-vm.sh
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
  server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
  server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/storage/StoragePoolAutomationImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
  server/src/main/java/org/apache/cloudstack/affinity/AffinityGroupServiceImpl.java
  server/src/test/java/com/cloud/vm/FirstFitPlannerTest.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadManagerImpl.java
  test/integration/broken/test_ps_resource_limits_volume.py
  test/integration/component/test_public_ip.py
  test/integration/smoke/test_create_network.py
  test/integration/smoke/test_update_security_group.py
  test/integration/testpaths/testpath_volumelifecycle.py
  test/metadata/func/regression_new.xml
  test/metadata/func/vmapi.xml
  tools/ngui/static/js/lib/jquery-1.7.2.js
Labels: component:XenServer, component:api, component:networking, component:saml, component:LDAP, component:simulator, component:kubernetes, component:hyperv, component:storage

#6605 Shows quotaSummary in API documentation
  tools/apidoc/gen_toc.py
Labels: Python

#6603 Close restore and attach form right after receiving the job id
  ui/src/views/storage/RestoreAttachBackupVolume.vue
Labels: component:UI

#6598 UI: Fix delete ISO navigation after job is finished
  ui/src/views/image/IsoZones.vue
Labels: type:bug, component:UI, Severity:Minor

#6612 ui: fix hypervisortrafficlabel for phy nw traffic
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: component:UI

#6460 Add new parameter to createLoadBalancerRule API
  api/src/main/java/com/cloud/agent/api/to/LoadBalancerTO.java
  api/src/main/java/com/cloud/network/lb/LoadBalancingRule.java
  api/src/main/java/com/cloud/network/lb/LoadBalancingRulesService.java
  api/src/main/java/com/cloud/network/rules/LoadBalancer.java
  api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/CreateLoadBalancerRuleCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/LoadBalancerResponse.java
  core/src/main/java/com/cloud/network/HAProxyConfigurator.java
  core/src/test/java/com/cloud/network/HAProxyConfiguratorTest.java
  engine/components-api/src/main/java/com/cloud/network/lb/LoadBalancingRulesManager.java
  engine/schema/src/main/java/com/cloud/network/dao/LoadBalancerVO.java
  engine/schema/src/main/java/org/apache/cloudstack/lb/ApplicationLoadBalancerRuleVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41710to41800.sql
  plugins/network-elements/elastic-loadbalancer/src/main/java/com/cloud/network/lb/LoadBalanceRuleHandler.java
  plugins/network-elements/internal-loadbalancer/src/main/java/org/apache/cloudstack/network/lb/InternalLoadBalancerVMManagerImpl.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
  server/src/test/java/com/cloud/network/lb/AssignLoadBalancerTest.java
  server/src/test/java/com/cloud/network/lb/LoadBalancingRulesManagerImplTest.java
  server/src/test/java/com/cloud/network/lb/UpdateLoadBalancerTest.java
Labels: component:api, component:networking

#6341 Enable system VM volume migration for KVM
  engine/schema/src/main/resources/META-INF/db/schema-41700to41710.sql
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/src/config/section/infra/routers.js
  ui/src/config/section/infra/systemVms.js
Labels: component:api, component:networking, component:UI, Python, component:agent, component:build, component:orchestration, distro:ubuntu, component:storage

#6549 test,xcp-ng: fix tests for VM PV driver issue
  test/integration/smoke/test_attach_multiple_volumes.py
  test/integration/smoke/test_network_permissions.py
  test/integration/smoke/test_volumes.py
Labels: Python, component:integration-test

#6616 ui: use ssh keypair uuid for listing
  ui/src/components/view/ListView.vue
  ui/src/main.js
  ui/src/utils/plugins.js
  ui/src/views/AutogenView.vue
  ui/tests/common/index.js
Labels: component:UI

#6591 vpc,network: fix createLoadBalancer access on user network
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
  server/src/main/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerManagerImpl.java
  server/src/test/java/com/cloud/network/NetworkModelTest.java
Labels: component:networking

#6552 removed the use of SharedMountPoint storage type for the StorPool plugin
  api/src/main/java/com/cloud/storage/Storage.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/StorPoolPrimaryDataStoreLifeCycle.java
Labels: component:kvm, component:primary-storage, component:api, component:storage

#6555 Fixed Veeam listing restore points
  plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
Labels: component:ipv6, component:api, component:UI, Python, component:marvin, component:integration-test, component:backup

#6408 Improve log messages on VolumeOrchestrator class
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/SnapshotInfo.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VolumeInfo.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/PrimaryDataStoreImpl.java
Labels: component:compute, component:orchestration, component:storage

#6622 Fixes #6621 - Update host memory stats
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: component:kvm

#6080 Increase size of column 'value' at table 'account_details'
  api/src/main/java/org/apache/cloudstack/api/command/admin/config/UpdateCfgCmd.java
  engine/schema/src/main/java/com/cloud/user/AccountDetailVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41700to41710.sql
Labels: type:bug, component:api, component:networking, Python, component:agent, component:build

#6636 ui: reset disksize param on offering change in scale vm
  ui/src/views/compute/ScaleVM.vue
Labels: component:UI

#6587 Updated resource counter to include correct size after volume creation/resize and other improvements
  api/src/main/java/com/cloud/configuration/Resource.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
  server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/DomainJoinDaoImpl.java
  server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:api, component:storage

#6625 vmware,cks: fix attachiso failure with vmware drs
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Labels: component:vmware

#6645 UI - Fixes the warning in detail tab
  ui/src/components/view/DetailsTab.vue
Labels: component:UI

#6646 ui: fix gputype in add compute offering
  ui/src/views/offering/AddComputeOffering.vue
Labels: component:UI

#6650 ui: fix resource tags visibility in infocard
  ui/src/components/view/InfoCard.vue
Labels: component:UI

#6588 server: fix ipv6 network deployment with separate guest nw
  engine/schema/src/main/java/com/cloud/dc/dao/VlanDao.java
  engine/schema/src/main/java/com/cloud/dc/dao/VlanDaoImpl.java
  server/src/main/java/com/cloud/network/Ipv6ServiceImpl.java
  server/src/test/java/com/cloud/network/Ipv6ServiceImplTest.java
Labels: component:ipv6, component:networking

#6640 Add usermode interface option to Libvirt Domain XML builder
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
Labels: component:kvm

#6654 Fix SQL query for uuid wrong format
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41610to41700.java
Labels: type:bug, component:upgrade, Severity:Major

#6642 server: remove resource tags for disassociated public ip
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: component:networking

#6276 api, vmware: Allow VM setting/detail for disk controller (root/data) to override template details
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:vmware, component:api

#6658 cks: fix k8s cluster deployment with host tagged offering
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
Labels: component:kubernetes

#6653 Chinese language pack
  ui/public/locales/zh_CN.json
Labels: component:UI

#6664 vpc: prevent sourcenat ip disassociation for an active vpc
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: component:networking

#6671 UI: Fixes suffix icon on project selector not work
  ui/src/components/header/ProjectMenu.vue
  ui/src/components/header/SamlDomainSwitcher.vue
  ui/src/style/ant-overwrite/ant-form.less
  ui/src/views/AutogenView.vue
Labels: component:UI

#6655 server: fix error when dedicatingguestvlanrange for physical nw without vlan range
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/test/java/com/cloud/network/DedicateGuestVlanRangesTest.java
Labels: component:networking

#6675 ui: fix update network updateinsequence param
  ui/src/views/network/UpdateNetwork.vue
Labels: component:UI

#6401 VM stats history visualization
  ui/package.json
  ui/public/locales/en.json
  ui/public/locales/pt_BR.json
  ui/src/components/view/StatsTab.vue
  ui/src/components/view/chart/LineChart.vue
  ui/src/components/view/stats/FilterStats.vue
  ui/src/components/view/stats/ResourceStatsInfo.vue
  ui/src/style/components/dashboard.less
  ui/src/style/components/view/StatsTab.scss
  ui/src/utils/plugins.js
  ui/src/views/compute/InstanceTab.vue
Labels: component:UI, type:new-feature

#6687 UI: Remove incorrect API calls when initializing the deploy VM page
  ui/src/views/compute/DeployVM.vue
Labels: component:UI

#6409 Validate host tags on VM live scale
  engine/schema/src/main/java/com/cloud/host/HostVO.java
  engine/schema/src/main/java/com/cloud/service/ServiceOfferingVO.java
  engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: status:needs-testing

#6643 vmware: fix vm snapshot with datastore cluster, drs
  core/src/main/java/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStore.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategyTest.java
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/VMSnapshotStrategyTest.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/PrimaryDataStoreImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareHostService.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareSecondaryStorageResourceHandler.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
Labels: component:vmware, component:storage

#6686 Remove unsupported params from API calls on the UI
  ui/src/components/header/SamlDomainSwitcher.vue
  ui/src/components/view/SearchView.vue
  ui/src/components/view/SettingsTab.vue
  ui/src/config/section/offering.js
  ui/src/store/modules/user.js
  ui/src/views/AutogenView.vue
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/EditVM.vue
  ui/src/views/iam/SSLCertificateTab.vue
  ui/src/views/image/AddKubernetesSupportedVersion.vue
  ui/src/views/image/IsoZones.vue
  ui/src/views/image/RegisterOrUploadIso.vue
  ui/src/views/image/RegisterOrUploadTemplate.vue
  ui/src/views/image/TemplateZones.vue
  ui/src/views/infra/zone/ZoneWizardZoneDetailsStep.vue
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateNetwork.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
  ui/src/views/network/CreateVpc.vue
  ui/src/views/network/GuestIpRanges.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/offering/UpdateOfferingAccess.vue
  ui/src/views/tools/ManageInstances.vue
Labels: component:UI
