Repository apache/cloudstack, pull requests merged in 2022-05, with the labels that each got.

#6345 UI: Fix navigation after delete template job is finished
  ui/src/views/image/TemplateZones.vue
Labels: type:bug, component:UI

#6343 systemvm: setup radvd correctly
  systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
  systemvm/debian/opt/cloud/bin/setup/common.sh
  systemvm/debian/opt/cloud/bin/setup/init.sh
  test/integration/smoke/test_network_ipv6.py
Labels: component:virtual-router, component:networking, Python, component:integration-test

#6353 ui: Fix live patch of routers
  ui/public/locales/en.json
  ui/src/config/section/infra/routers.js
Labels: type:bug, component:UI

#6347 Move apache DS dependencies to test scope
  plugins/user-authenticators/ldap/pom.xml
Labels: component:build, component:LDAP

#6354 ui: Network offerings not listed if listVPCs not available in the account Role
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
Labels: type:bug, component:UI

#6355 Gateways after Nic update on Shared Network tests
  test/integration/smoke/test_gateway_on_shared_networks.py
  tools/marvin/marvin/lib/base.py
Labels: Python, component:marvin, component:integration-test

#6362 Bugfix: no support for XCPng 8.2.1
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
Labels: type:bug, component:XenServer, compatibilty

#6361 test_network_ipv6.py : remove wrong icmp type
  test/integration/smoke/test_network_ipv6.py
Labels: Python, component:integration-test

#6364 ipv6: set default_egress_policy for ingress rules
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
Labels: component:networking

#6370 UI: Fix refresh button on Metrics
  ui/src/views/infra/Metrics.vue
Labels: type:bug, component:UI

#6368 CKS: fix error with pulling weaveworks images when create k8s ISO
  scripts/util/create-kubernetes-binaries-iso.sh
Labels: type:bug, component:kubernetes

#6375 ui: Allow editing host and storage tags in updateHost & updatStoragePool forms
  ui/src/views/AutogenView.vue
Labels: type:bug, component:UI

#6371 agent: enable ssl only for kvm agent (not in system vms)
  agent/src/main/java/com/cloud/agent/AgentShell.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: type:bug, component:kvm, component:agent

#6379 Update VM name, when the new name provided in updateVirtualMachine API is in different case.
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:enhancement, component:api

#6382 UI: Fix hypervisor list after zone validation when registering a template
  ui/src/views/image/RegisterOrUploadTemplate.vue
Labels: type:bug, component:UI

#6376 UI: Add missing tooltips on service offering creation
  ui/public/locales/en.json
  ui/src/views/offering/AddComputeOffering.vue
Labels: type:bug, component:UI

#6383 remove unused UI field
  ui/src/config/section/infra/managementServers.js
Labels: component:UI

#6378 Editing two labels for the Portuguese translation
  ui/public/locales/en.json
  ui/public/locales/pt_BR.json
  ui/src/config/section/plugin/quota.js
Labels: component:UI

#6384 Fix: Cannot import Vmware instances
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug, component:vmware, Severity:BLOCKER

#6387 Reword KVM VM snapshot without memory error message
  api/src/main/java/org/apache/cloudstack/api/command/user/vmsnapshot/CreateVMSnapshotCmd.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
Labels: type:enhancement, component:api

#6377 Fix changeOfferingForVolume API to consider storage type in the disk offering
  api/src/main/java/com/cloud/server/ManagementService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/ChangeOfferingForVolumeCmd.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
Labels: type:bug, component:management-server, component:api, component:storage

#6389 server: publish ip6 assign event with route, always for vpc
  api/src/main/java/com/cloud/network/Ipv6Service.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/main/java/com/cloud/network/Ipv6ServiceImpl.java
Labels: component:ipv6, component:api, component:networking, component:orchestration

#6385 test: add test for importUnmanagedInstance
  test/integration/smoke/test_vm_life_cycle.py
  test/integration/smoke/test_vm_lifecycle_unmanage_import.py
  tools/marvin/marvin/lib/base.py
  tools/marvin/marvin/lib/vcenter.py
Labels: Python, component:marvin, component:integration-test

#6388 cks: upgrade k8s to 1.23.3/1.24.0 in smoke test
  test/integration/smoke/test_kubernetes_clusters.py
  test/integration/smoke/test_kubernetes_supported_versions.py
  tools/marvin/marvin/config/test_data.py
Labels: Python, component:marvin, component:integration-test

#6332 [UI] update ja locale translation
  ui/public/locales/ja_JP.json
Labels: component:UI

#6392 cks: Get caller user keys if cluster belongs to project
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
Labels: component:kubernetes

#6356 Log load bean exception
  utils/src/main/java/com/cloud/utils/component/ComponentContext.java
Labels: type:enhancement

#6397 Prevent NPE on reboot stopped VM and startVM output with null displayname
  engine/schema/src/main/java/com/cloud/vm/UserVmVO.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug, component:UI

#6402 Backport: kvm: truncate vnc password to 8 chars (#6244)
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: type:bug, component:kvm

#6407 [UI] Zone Wizard - fix secret property when setting RBD primary storage
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: type:bug, component:UI

#6400 UI: fix create vpc private gateway for regular user
  ui/src/config/section/network.js
  ui/src/views/network/VpcTab.vue
Labels: type:bug, component:UI

#6399 [KVM] Enable IOURING only when it is available on the host
  agent/conf/agent.properties
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: component:kvm, Severity:BLOCKER, component:agent

#6404 [KVM] Fix VM migration error due to VNC password on libvirt limiting versions
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
Labels: type:bug, component:kvm, component:migration

#6393 remove request listener to prevent untimely session invalidation
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/ListIdpsCmd.java
  server/src/main/java/com/cloud/api/ApiServlet.java
  server/src/main/java/com/cloud/api/ApiSessionListener.java
  server/src/main/java/com/cloud/api/auth/DefaultLoginAPIAuthenticatorCmd.java
  server/src/main/java/com/cloud/api/auth/DefaultLogoutAPIAuthenticatorCmd.java
Labels: type:bug, component:api, Severity:BLOCKER, component:saml

#6405 Fix logic check error for update GPU groupDetails
  server/src/main/java/com/cloud/server/StatsCollector.java
Labels: component:management-server

#6417 UI: Fix Upgrade kubernetes form
  ui/src/views/compute/UpgradeKubernetesCluster.vue
Labels: type:bug, component:UI, type:regression

#6416 ui: Fix create kubernetes cluster with ha enabled
  ui/src/views/compute/CreateKubernetesCluster.vue
Labels: type:bug, component:UI, type:regression

#6421 ui: Display associated VPC network name against vpc tiers - deploy VM form
  ui/src/views/compute/wizard/NetworkSelection.vue
Labels: type:bug, component:UI, type:regression

#6423 Fix UEFI detection on KVM and prevent deployments on non UEFI enabled hosts
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
  server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
Labels: type:bug, component:kvm

#6418 cks: Fix when deployed on a nw without internet access
  plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml
  plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
  plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml
  plugins/integrations/kubernetes-service/src/main/resources/script/upgrade-kubernetes.sh
Labels: type:bug, component:kubernetes
