Repository apache/cloudstack, pull requests merged in 2022-03, with the labels that each got.

#5965 Multiple SSH Keys support
  api/src/main/java/com/cloud/vm/UserVmService.java
  api/src/main/java/com/cloud/vm/VmDetailConstants.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/ResetVMSSHKeyCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  engine/schema/src/main/java/com/cloud/user/dao/SSHKeyPairDao.java
  engine/schema/src/main/java/com/cloud/user/dao/SSHKeyPairDaoImpl.java
  engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/locales/en.json
  ui/src/components/view/InfoCard.vue
  ui/src/config/section/compute.js
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/ResetSshKeyPair.vue
  ui/src/views/compute/wizard/SshKeyPairSelection.vue
Labels: type:new-feature, Severity:Major

#6019 Use default timeout and retransmission values for the NFS mount.
  scripts/vm/hypervisor/kvm/kvmheartbeat.sh
Labels: type:enhancement, component:kvm, component:primary-storage

#6041 Fix spelling
  core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/SetNetworkAclConfigItem.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/ClusteredAgentManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java
  plugins/hypervisors/hyperv/DotNet/ServerResource/AgentShell/Program.cs
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtKvmAgentHook.java
  plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/objects/Connection.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetscalerResource.java
  scripts/vm/hypervisor/xenserver/cloudstack_pluginlib.py
  scripts/vm/network/vnet/ovstunnel.py
  systemvm/debian/root/health_checks/haproxy_check.py
  test/integration/broken/test_ss_project_limits.py
  test/integration/component/test_brocade_vcs.py
  test/integration/component/test_concurrent_snapshots_limit.py
  test/integration/component/test_dynamic_compute_offering.py
  test/integration/component/test_multiple_ips_per_nic.py
  test/integration/component/test_multiple_nic_support.py
  test/integration/component/test_netscaler_lb.py
  test/integration/component/test_persistent_networks.py
  test/integration/component/test_portable_ip.py
  test/integration/component/test_project_resources.py
  test/integration/component/test_ps_max_limits.py
  test/integration/component/test_ps_project_limits.py
  test/integration/component/test_resource_limits.py
  test/integration/component/test_security_groups.py
  test/integration/component/test_snapshot_gc.py
  test/integration/component/test_tags.py
  tools/ngui/static/js/lib/jquery-1.7.2.js
  utils/src/main/java/com/cloud/utils/cisco/n1kv/vsm/NetconfHelper.java
Labels: type:cleanup, Severity:Trivial

#6055 UI: Missing message on VMware VM import for not found networks
  ui/public/locales/en.json
Labels: component:vmware, component:UI, Severity:Trivial

#6028 Upgrade Tomcat embed version
  pom.xml
Labels: component:security

#6054 Fix API parameter description for boottype/bootmode
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:cleanup, Severity:Trivial

#6053 Fix NPE on CIDR list check
  utils/src/main/java/com/cloud/utils/net/NetUtils.java
Labels: type:bug

#6032 api: Fix search by name
  api/src/main/java/org/apache/cloudstack/acl/ProjectRoleService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/ListProjectRolesCmd.java
  engine/schema/src/main/java/org/apache/cloudstack/acl/dao/ProjectRoleDao.java
  engine/schema/src/main/java/org/apache/cloudstack/acl/dao/ProjectRoleDaoImpl.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/org/apache/cloudstack/acl/ProjectRoleManagerImpl.java
Labels: type:enhancement, component:api

#6018 Allow specifying disk size, min/max iops for offering linked with custom disk offering
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/ChangeOfferingForVolumeCmd.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/src/views/compute/ScaleVM.vue
  ui/src/views/compute/wizard/DiskSizeSelection.vue
Labels: type:bug

#6050 Check the network access when deploying VM in Advanced Security Group.
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: component:networking

#6056 Fix osx build
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/MemStat.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
Labels: type:bug, component:build, compatibilty

#6061 Fix spelling. Change `Occured` to `Occurred`
  server/src/main/java/com/cloud/network/ExternalLoadBalancerDeviceManagerImpl.java
  test/integration/component/test_concurrent_snapshots_limit.py
  test/integration/component/test_ip_reservation.py
  test/integration/component/test_lb_secondary_ip.py
  test/integration/component/test_persistent_networks.py
  test/integration/component/test_portable_ip.py
  test/integration/component/test_shared_networks.py
  test/integration/component/test_vpc_network.py
  test/integration/smoke/test_persistent_network.py
  test/integration/testpaths/testpath_stopped_vm.py
  tools/marvin/marvin/lib/common.py
  tools/marvin/marvin/lib/ncc.py
Labels: type:cleanup, Severity:Trivial

#6051 UI: update vm with userdata
  ui/src/views/compute/EditVM.vue
Labels: type:enhancement, component:UI

#5993 no axis
  client/pom.xml
  plugins/hypervisors/vmware/pom.xml
  plugins/network-elements/f5/pom.xml
  plugins/network-elements/juniper-srx/pom.xml
  plugins/pom.xml
  pom.xml
  vmware-base/pom.xml
Labels: component:security

#6066 UI: Fix issue on volume snapshots wizard
  ui/src/views/AutogenView.vue
Labels: type:bug, component:UI

#6059 Upgrade netty version
  services/secondary-storage/server/pom.xml
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
Labels: component:security

#6065 ui: Add link to account role in listview
  ui/src/components/view/ListView.vue
Labels: type:enhancement, component:UI

#6070 ui: Add user initials as avatar if no icon present
  ui/src/components/header/UserMenu.vue
Labels: type:bug, component:UI

#5009 api: Warn if query parameters have multiple values
  server/src/main/java/com/cloud/api/ApiServer.java
  server/src/main/java/com/cloud/api/ApiServlet.java
Labels: component:api

#6069 Adapt script to bash version 3
  engine/schema/templateConfig.sh
Labels: component:build, compatibilty

#6072 UI: Fix navigation to domains
  ui/src/components/view/DedicateData.vue
  ui/src/components/view/ListView.vue
Labels: type:bug, component:UI

#6077 UI: Reload page on closing Bulk Action modal
  ui/src/components/view/BulkActionProgress.vue
Labels: type:bug, component:UI

#6085 UI: Fix Dedicating resource to a domain
  ui/src/components/view/DedicateData.vue
Labels: type:bug, component:UI

#6086 UI: Fix route to domain details
  ui/src/components/view/DedicateData.vue
  ui/src/components/view/InfoCard.vue
Labels: component:UI, Severity:Trivial

#6057 server: mark volume snapshots as Destroyed if it does not exist on primary and secondary storage when delete a volume
  api/src/main/java/com/cloud/storage/snapshot/SnapshotApiService.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
Labels: type:bug

#6079 Fix get upload params NPE
  api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
Labels: type:bug, component:api

#6089 UI: Fix storage pool label for protocol
  ui/src/views/infra/AddPrimaryStorage.vue
Labels: type:bug, component:UI

#6045 Honour isrecursive above listall
  api/src/main/java/org/apache/cloudstack/api/BaseListDomainResourcesCmd.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
  server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java
  server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
  server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java
  server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/user/AccountManager.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  server/src/main/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerManagerImpl.java
  server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
Labels: type:bug, component:api

#6099 ui: fix deploy vm stay on page
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, Severity:BLOCKER, component:UI

#6098 ui: fix bulk destroy vm with expunge
  ui/src/views/compute/DestroyVM.vue
Labels: type:bug, component:UI

#6093 UI: Fixes domain navigation to back
  ui/src/views/iam/DomainView.vue
Labels: type:bug, component:UI

#6081 [UI] Dont show project view menu when user doesn't have permission
  ui/src/components/header/ProjectMenu.vue
Labels: type:enhancement, component:UI

#6095 ui: fix mac learning warning visibility in add network offering
  ui/src/views/offering/AddNetworkOffering.vue
Labels: type:bug, component:UI

#6096 ui: fix physical network guest traffic type tab
  ui/src/views/infra/network/IpRangesTabGuest.vue
Labels: type:bug, component:UI

#6113 travis: run nosetests-3.4
  tools/travis/script.sh
Labels: Severity:BLOCKER, component:travis

#6109 UI: Fix alignment of message
  ui/public/locales/en.json
  ui/src/views/network/EgressRulesTab.vue
Labels: type:bug, component:UI

#6106 ui: Fix CreateKubernetesCluster for ha
  ui/src/views/compute/CreateKubernetesCluster.vue
Labels: type:bug, component:UI

#6110 UI - Fixes error form.getFieldValue is not a function in change user password form
  ui/src/views/iam/ChangeUserPassword.vue
Labels: type:bug, component:UI

#6118 api: Fix issue observed with message publish on creation of domain
  server/src/main/java/com/cloud/user/DomainManagerImpl.java
Labels: type:bug, component:api

#6119 Travis - fix test failures observed
  tools/marvin/marvin/cloudstackException.py
Labels: type:bug, component:travis

#6126 Revert "Honour isrecursive above listall"
  api/src/main/java/org/apache/cloudstack/api/BaseListDomainResourcesCmd.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
  server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java
  server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
  server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java
  server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/user/AccountManager.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  server/src/main/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerManagerImpl.java
  server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
Labels: type:regression

#5664 alert: Send alert for ha'ed vm's
  server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
Labels: type:enhancement

#5602 Create profiles to download systemvm-templates
  engine/schema/pom.xml
  packaging/centos7/cloud.spec
  packaging/centos8/cloud.spec
  packaging/package.sh
  packaging/suse15/cloud.spec
Labels: type:enhancement, component:build

#6046 New feature: Reserve and release Public IPs
  api/src/main/java/com/cloud/event/EventTypes.java
  api/src/main/java/com/cloud/network/IpAddress.java
  api/src/main/java/com/cloud/network/NetworkService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/address/ReleaseIPAddrCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/address/ReserveIPAddrCmd.java
  engine/schema/src/main/java/com/cloud/network/dao/IPAddressDao.java
  engine/schema/src/main/java/com/cloud/network/dao/IPAddressDaoImpl.java
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
  ui/public/locales/en.json
  ui/src/components/widgets/Status.vue
  ui/src/config/section/network.js
  ui/src/views/AutogenView.vue
  ui/src/views/network/IpAddressesTab.vue
  ui/src/views/network/PublicIpResource.vue
  ui/src/views/network/ReservePublicIP.vue
  ui/tests/mockData/Status.mock.json
Labels: type:enhancement, type:new-feature, Severity:Major

#6136 api: Allow updating VM settings when custom constrained offering is used
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:bug

#6116 Fix migration of VM with volume on Ubuntu
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
Labels: type:bug, Severity:Critical

#6137 ui: Fix icon on Load Balancing view tab
  ui/src/views/network/LoadBalancing.vue
Labels: type:bug, component:UI

#6120 server: fix NPE when router.service.offering is set due to service/disk offering refactoring
  server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
  server/src/main/java/com/cloud/network/element/VpcVirtualRouterElement.java
  server/src/main/java/com/cloud/network/router/NetworkHelper.java
  server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
  server/src/main/java/com/cloud/network/router/NicProfileHelper.java
  server/src/main/java/com/cloud/network/router/NicProfileHelperImpl.java
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
  server/src/main/java/com/cloud/network/router/VpcNetworkHelperImpl.java
  server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinition.java
  server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionBuilder.java
  server/src/main/java/org/apache/cloudstack/network/router/deployment/VpcRouterDeploymentDefinition.java
  server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
  server/src/test/java/com/cloud/network/element/VirtualRouterElementTest.java
  server/src/test/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionTest.java
  server/src/test/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionTestBase.java
  server/src/test/java/org/apache/cloudstack/network/router/deployment/VpcRouterDeploymentDefinitionTest.java
Labels: type:bug

#6122 account check made explicit - cleanup
  server/src/main/java/com/cloud/projects/ProjectManagerImpl.java
Labels: type:cleanup, Severity:Minor

#6130 Router health check notification mail to show router name next to UUID
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Labels: type:enhancement, component:virtual-router

#6151 UI: Prevent passing boottype/bootmode when template is deploy-as-is
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:vmware, component:UI

#6158 ui: Fix router link access
  ui/src/components/view/InfoCard.vue
  ui/src/components/view/ListView.vue
Labels: type:bug, component:UI

#6152 travis: Fix failing travis tests on main
  test/integration/component/test_project_limits.py
  test/integration/component/test_resource_limits.py
Labels: type:bug, component:travis

#6157 ui: Fix wrong label entity.type
  ui/src/components/view/SearchView.vue
Labels: type:bug, component:UI

#6159 ui: Remove misleading anchor tags for users
  ui/src/components/view/ListView.vue
Labels: type:bug, component:UI

#6147 kvm: support multiple local storage pools
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: type:enhancement, component:kvm

#4636 Prevent vm's from stopping while enabling maintenance mode
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
Labels: type:bug, status:needs-reproducing

#6143 api: Remove redundant API parameters
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: component:api, type:cleanup

#6170 ui, Adv zone + SG: Fix invocation of create/revoke APIs for ingress/egress security group rules
  ui/src/components/view/ResourceView.vue
  ui/src/views/network/IngressEgressRuleConfigure.vue
Labels: type:bug, component:UI

#6174 UI: fix create l2 network offering with userdata
  ui/src/views/offering/AddNetworkOffering.vue
Labels: type:bug, component:UI

#6161 Fix spelling
  agent/bindir/cloud-setup-agent.in
  agent/conf/agent.properties
  agent/src/main/java/com/cloud/agent/Agent.java
  agent/src/main/java/com/cloud/agent/direct/download/DirectTemplateDownloaderImpl.java
  api/src/main/java/com/cloud/network/NetworkMigrationResponder.java
  api/src/main/java/com/cloud/network/guru/NetworkGuru.java
  api/src/main/java/com/cloud/server/ManagementService.java
  api/src/main/java/org/apache/cloudstack/api/BaseUpdateTemplateOrIsoCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/template/CreateTemplateCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/test/UpdateRoleCmdTest.java
  server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java
  test/integration/component/test_netscaler_nw_off.py
  test/integration/component/test_persistent_networks.py
  test/integration/smoke/test_accounts.py
  tools/ngui/precache.py
  ui/public/locales/ar.json
  ui/public/locales/ca.json
  ui/public/locales/de_DE.json
  ui/public/locales/el_GR.json
  ui/public/locales/en.json
  ui/public/locales/es.json
  ui/public/locales/fr_FR.json
  ui/public/locales/hu.json
  ui/public/locales/it_IT.json
  ui/public/locales/ja_JP.json
  ui/public/locales/ko_KR.json
  ui/public/locales/nb_NO.json
  ui/public/locales/nl_NL.json
  ui/public/locales/pl.json
  ui/public/locales/pt_BR.json
  ui/public/locales/ru_RU.json
  ui/public/locales/zh_CN.json
  ui/src/views/network/AclListRulesTab.vue
  ui/src/views/network/FirewallRules.vue
  ui/src/views/network/IngressEgressRuleConfigure.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/network/PortForwarding.vue
  ui/src/views/network/StaticRoutesTab.vue
Labels: type:cleanup, Severity:Trivial

#6171 Avoid multiple if else
  api/src/main/java/com/cloud/hypervisor/Hypervisor.java
Labels: type:cleanup, Severity:Trivial

#6168 api: Fix reset configuration
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Labels: type:bug

#6146 configDrive: Fix failure to delete (unstarted) VM
  server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
Labels: type:bug

#6165 SAML: replace first number with random alphabet if request ID starts with a number
  plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
  plugins/user-authenticators/saml2/src/test/java/org/apache/cloudstack/SAMLUtilsTest.java
Labels: type:bug, component:saml

#6162 UI - Fixes UI bugs
  ui/src/components/header/HeaderNotice.vue
  ui/src/components/menu/SMenu.vue
  ui/src/components/page/GlobalLayout.vue
  ui/src/components/page/PageHeader.vue
  ui/src/components/page/PageLayout.vue
  ui/src/components/view/ActionButton.vue
  ui/src/components/view/InfoCard.vue
  ui/src/components/view/ListView.vue
  ui/src/components/widgets/Breadcrumb.vue
  ui/src/components/widgets/TooltipButton.vue
  ui/src/core/lazy_lib/icons_use.js
  ui/src/layouts/UserLayout.vue
  ui/src/style/vars.less
  ui/src/views/AutogenView.vue
  ui/src/views/auth/Login.vue
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/DestroyVM.vue
  ui/src/views/dashboard/UsageDashboard.vue
  ui/src/views/dashboard/UsageDashboardChart.vue
  ui/src/views/infra/InfraSummary.vue
  ui/src/views/project/AccountsTab.vue
  ui/src/views/project/InvitationsTemplate.vue
Labels: type:bug, component:UI
