Repository apache/cloudstack, pull requests merged in 2022-04, with the labels that each got.

#6181 ui,refactor: fix missing label in update network form
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkCmd.java
  ui/public/locales/en.json
Labels: type:bug, component:UI

#6132 CKS: Support deployment of CKS clusters on Advanced zones with security groups
  api/src/main/java/com/cloud/network/security/SecurityGroupService.java
  api/src/main/java/com/cloud/vm/UserVmService.java
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesCluster.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterVO.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
  server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: type:enhancement, component:kubernetes

#6164 Mount disabled storage pool on host reboot
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/main/java/com/cloud/storage/listener/StoragePoolMonitor.java
Labels: type:enhancement, component:primary-storage

#6182 UI: Fix minor UI issues
  ui/src/config/section/infra/phynetworks.js
  ui/src/views/compute/ScaleVM.vue
  ui/src/views/dashboard/CapacityDashboard.vue
  ui/src/views/infra/MigrateData.vue
  ui/src/views/infra/network/IpRangesTabPublic.vue
  ui/src/views/network/AclListRulesTab.vue
  ui/src/views/network/CreateVpnCustomerGateway.vue
  ui/src/views/network/VpcTab.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
Labels: type:bug, component:UI

#6192 Remove duplicate entry from `.gitignore`
  .gitignore
Labels: type:cleanup, Severity:Trivial

#6139 agent: Detect existing hosts with UEFI support
  core/src/main/java/com/cloud/agent/api/ReadyAnswer.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/VmwareServerDiscoverer.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixReadyCommandWrapper.java
  server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Labels: type:enhancement

#6183 test: update test_kubernetes_clusters.py to support advanced zone with security groups
  test/integration/smoke/test_kubernetes_clusters.py
Labels: type:enhancement, component:marvin

#6188 VR: add '-m <protocol>' for tcp or udp protocol
  systemvm/debian/opt/cloud/bin/configure.py
Labels: type:bug, component:virtual-router

#6189 VR: Do not add iptables rules for the revoked ip addresses
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
Labels: type:bug, component:virtual-router

#6198 server: fix list reserved/free public ips in project
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: type:bug

#6156 api: Update account type when updating account role
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
Labels: type:bug, component:api

#6207 api: add vpcname to networkacl response
  api/src/main/java/org/apache/cloudstack/api/response/NetworkACLResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: type:enhancement, component:vpc

#6193 UI: Logout before login
  ui/src/api/index.js
Labels: type:enhancement, component:UI

#6190 Added new field to updateBackupOffering API.
  api/src/main/java/org/apache/cloudstack/api/command/admin/backup/UpdateBackupOfferingCmd.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  server/src/test/java/org/apache/cloudstack/backup/BackupManagerTest.java
Labels: type:enhancement, component:api, component:backup

#6218 Allow storage.overprovisioning.factor to be <1
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: type:enhancement, component:ceph, component:primary-storage

#6196 UI: Fixes removing undesired API parameters on form submit
  ui/public/locales/en.json
  ui/src/utils/mixin.js
  ui/src/views/compute/CreateKubernetesCluster.vue
  ui/src/views/compute/CreateSSHKeyPair.vue
  ui/src/views/compute/CreateSnapshotWizard.vue
  ui/src/views/compute/ScaleKubernetesCluster.vue
  ui/src/views/compute/backup/FormSchedule.vue
  ui/src/views/iam/CreateRole.vue
  ui/src/views/iam/RolePermissionTab.vue
  ui/src/views/image/RegisterOrUploadIso.vue
  ui/src/views/image/RegisterOrUploadTemplate.vue
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/infra/AddSecondaryStorage.vue
  ui/src/views/infra/HostAdd.vue
  ui/src/views/network/AclListRulesTab.vue
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
  ui/src/views/network/CreateVpnCustomerGateway.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/network/UpdateNetwork.vue
  ui/src/views/network/VpcTiersTab.vue
  ui/src/views/offering/AddComputeOffering.vue
  ui/src/views/offering/AddDiskOffering.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
  ui/src/views/offering/UpdateOfferingAccess.vue
  ui/src/views/project/AddAccountOrUserToProject.vue
  ui/src/views/storage/ChangeOfferingForVolume.vue
  ui/src/views/storage/CreateVolume.vue
  ui/src/views/storage/FormSchedule.vue
  ui/src/views/storage/ResizeVolume.vue
  ui/src/views/storage/TakeSnapshot.vue
  ui/src/views/storage/UploadLocalVolume.vue
  ui/src/views/storage/UploadVolume.vue
Labels: type:bug, component:UI

#6228 Support JaCoCo and other quality checks
  .github/workflows/pull-request-checks.yml
  client/pom.xml
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
  pom.xml
Labels: component:kvm, component:build

#6227 upgrade: update minreq.sysvmtemplate.version to the latest template version
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41610to41700.java
Labels: type:bug, component:upgrade

#6187 api: Prevent modifying acl rules order for default ACLs
  server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
Labels: type:bug, component:vpc, component:api, component:networking

#3724 Storage-based Snapshots for KVM VMs
  api/src/main/java/com/cloud/storage/Snapshot.java
  core/src/main/java/com/cloud/agent/api/FreezeThawVMAnswer.java
  core/src/main/java/com/cloud/agent/api/FreezeThawVMCommand.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StorageStrategyFactory.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VMSnapshotStrategy.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/ScaleIOVMSnapshotStrategy.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java
  engine/storage/snapshot/src/main/resources/META-INF/cloudstack/storage/spring-engine-storage-snapshot-storage-context.xml
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/VMSnapshotStrategyKVMTest.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/helper/StorageStrategyFactoryImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtFreezeThawVMCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuCommand.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  test/integration/smoke/test_vm_snapshot_kvm.py
Labels: component:kvm, component:primary-storage, status:needs-love, component:managed-storage, type:new-feature, status:needs-testing, age:2years_plus

#6123 server: increment deviceid while importing vm data volumes
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
Labels: type:bug, component:vmware

#6226 Display proper gateway length in health check result
  systemvm/debian/root/health_checks/gateways_check.py
Labels: type:bug, component:virtual-router, Python

#6233 ui: Project owner (normal user) unable to perform any operations in the project
  ui/src/views/project/ProjectDetailsTab.vue
Labels: component:UI

#6241 UI: Fix Add secondary storage
  ui/src/views/infra/AddSecondaryStorage.vue
Labels: type:bug, component:UI, Severity:Critical

#6237 potential null pointer in condition; AYAI9l8k5Irk9_td-cXb
  api/src/main/java/com/cloud/agent/api/storage/OVFParser.java
Labels: type:bug, component:api

#5984 Persistence of VM stats
  api/src/main/java/org/apache/cloudstack/api/ApiArgValidator.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/StatsResponse.java
  api/src/test/java/org/apache/cloudstack/api/response/StatsResponseTest.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntry.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntryBase.java
  engine/schema/src/main/java/com/cloud/vm/VmStatsVO.java
  engine/schema/src/main/java/com/cloud/vm/dao/VmStatsDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/VmStatsDaoImpl.java
  engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockVmManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsUsageHistoryCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsService.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/VmMetricsStatsResponse.java
  plugins/metrics/src/test/java/org/apache/cloudstack/metrics/MetricsServiceImplTest.java
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDao.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/test/java/com/cloud/server/StatsCollectorTest.java
  server/src/test/java/com/cloud/user/AccountManagerImplVolumeDeleteEventTest.java
  ui/src/config/section/compute.js
Labels: type:enhancement, component:management-server, status:needs-testing

#6197 UI: fixes login button not work and Single Sign-On tab disabled after logout
  ui/src/api/index.js
  ui/src/store/getters.js
  ui/src/store/modules/user.js
  ui/src/utils/request.js
  ui/src/views/auth/Login.vue
Labels: type:bug, component:UI

#6234 Allow expunging a VM on a deleted host when using host cache and ConfigDrive userdata service
  server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
Labels: type:bug, component:networking

#6235 ui: use different icon label for releaseIpAddress action
  ui/public/locales/en.json
  ui/src/components/view/ActionButton.vue
  ui/src/config/section/network.js
  ui/src/core/lazy_lib/icons_use.js
Labels: type:enhancement, component:UI

#6243 UI: Fix protocol reset after changing provider on Add Primary Storage
  ui/src/views/infra/AddPrimaryStorage.vue
Labels: type:bug, component:UI

#5297 KVM disk-only based snapshot of volumes instead of taking VM's full snapshot and extracting disks
  core/src/main/java/org/apache/cloudstack/storage/command/RevertSnapshotCommand.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/SnapshotDataFactory.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
  engine/schema/src/main/java/com/cloud/storage/SnapshotVO.java
  engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDao.java
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java
  engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategyTest.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImpl.java
  engine/storage/src/test/java/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImplTest.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUtilitiesHelper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ManagedNfsStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapperTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUtilitiesHelperTest.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessorTest.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
  scripts/storage/qcow2/managesnapshot.sh
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/snapshot/SnapshotHelper.java
  server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
  server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java
  server/src/test/java/com/cloud/template/TemplateManagerImplTest.java
  server/src/test/java/org/apache/cloudstack/snapshot/SnapshotHelperTest.java
Labels: type:enhancement, component:kvm, component:iscsi, component:orchestration, status:needs-testing, component:storage

#6248 ui: Fix uploadCustomCertificate form in infraSummary view
  ui/src/views/infra/InfraSummary.vue
Labels: type:bug, component:UI

#6153 VR: add rules for traffic between static nat and private gateway static routes
  systemvm/debian/opt/cloud/bin/configure.py
Labels: type:bug, component:virtual-router

#6160 server: honor global setting system.vm.default.hypervisor as first option when deploy VRs
  server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
Labels: type:bug, component:virtual-router

#6253 Extract the IO_URING configuration into the agent.properties
  agent/conf/agent.properties
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: type:bug, component:kvm, component:agent

#6256 local versions of .env ignored
  ui/.gitignore
Labels: component:UI, type:cleanup, Severity:Trivial

#6254 Fix: Allow disabling the login attempts mechanism for disabling users
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/test/java/com/cloud/user/AccountManagerImplTest.java
Labels: type:bug

#4739 Allow creating snapshot from VM snapshot
  api/src/main/java/com/cloud/storage/snapshot/SnapshotApiService.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
Labels: type:enhancement, component:api, Severity:Minor, component:storage

#6258 UI: fix dedicate public ip range to domain
  ui/src/views/infra/network/IpRangesTabPublic.vue
Labels: type:bug, component:UI

#6257 ui: Display action buttons in Project Accounts Tab view if project Admin
  ui/src/views/project/AccountsTab.vue
Labels: type:bug, component:UI

#6260 ui: Add project switch to the Kubernetes tab
  ui/src/views/AutogenView.vue
Labels: component:UI, Severity:Trivial

#6262 ui: Allow editing VM and template settings
  ui/src/components/view/DetailSettings.vue
Labels: component:UI

#6238 .github: improve coverage run
  .github/workflows/coverage-check.yml
  .github/workflows/merge-conflict-checker.yml
Labels: component:api, component:UI, component:agent

#6007 StorPool storage plugin
  client/pom.xml
  core/src/main/java/org/apache/cloudstack/storage/command/CopyCmdAnswer.java
  debian/rules
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStoreDriver.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StorageStrategyFactory.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VMSnapshotStrategy.java
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
  packaging/centos7/cloud.spec
  packaging/centos8/cloud.spec
  packaging/suse15/cloud.spec
  plugins/pom.xml
  plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/driver/DateraPrimaryDataStoreDriver.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
  plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
  plugins/storage/volume/nexenta/src/main/java/org/apache/cloudstack/storage/datastore/driver/NexentaPrimaryDataStoreDriver.java
  plugins/storage/volume/sample/src/main/java/org/apache/cloudstack/storage/datastore/driver/SamplePrimaryDataStoreDriverImpl.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
  plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
  plugins/storage/volume/storpool/README.md
  plugins/storage/volume/storpool/pom.xml
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolBackupSnapshotCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolBackupTemplateFromSnapshotCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolCopyCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolCopyVolumeToSecondaryCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolDownloadTemplateCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolDownloadVolumeCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolMigrateWithVolumesCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolModifyStoragePoolAnswer.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolModifyStoragePoolCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolResizeVolumeCommand.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolBackupSnapshotCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolBackupTemplateFromSnapshotCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolCopyVolumeToSecondaryCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolDownloadTemplateCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolDownloadVolumeCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolModifyStorageCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolResizeVolumeCommandWrapper.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
  plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStoragePool.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/collector/StorPoolAbandonObjectsCollector.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/StorPoolPrimaryDataStoreLifeCycle.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/provider/StorPoolHostListener.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/provider/StorPoolPrimaryDataStoreProvider.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolFeaturesAndFixes.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolHelper.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/motion/StorPoolDataMotionStrategy.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolConfigurationManager.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolSnapshotStrategy.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolVMSnapshotStrategy.java
  plugins/storage/volume/storpool/src/main/resources/META-INF/cloudstack/storage-volume-storpool/module.properties
  plugins/storage/volume/storpool/src/main/resources/META-INF/cloudstack/storage-volume-storpool/spring-storage-volume-storpool-context.xml
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java
  test/integration/plugins/storpool/MigrateVolumeToStorPool.py
  test/integration/plugins/storpool/TestStorPoolVolumes.py
  test/integration/plugins/storpool/TestTagsOnStorPool.py
  test/integration/plugins/storpool/TestVmSnapshots.py
  test/integration/plugins/storpool/sp_util.py
Labels: component:primary-storage, component:packaging, component:managed-storage, type:new-feature, component:build, distro:ubuntu, distro:centos, component:solidfire, component:storage

#6244 kvm: truncate vnc password to 8 chars
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Labels: component:kvm

#6261 UI: Fixes UI bug
  ui/src/components/header/ProjectMenu.vue
  ui/src/style/dark-mode.less
  ui/src/views/dashboard/CapacityDashboard.vue
  ui/src/views/dashboard/UsageDashboard.vue
Labels: type:bug, component:UI

#6267 Fix #6263 Cannot scale VM with custom offering
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
Labels: type:bug, Severity:Critical, component:storage

#6268 Enable flake8 W293 blank line contains whitespace
  .github/linters/.flake8
  test/integration/plugins/storpool/MigrateVolumeToStorPool.py
  test/integration/plugins/storpool/TestStorPoolVolumes.py
  test/integration/plugins/storpool/TestTagsOnStorPool.py
  test/integration/plugins/storpool/sp_util.py
  test/integration/smoke/test_vm_snapshot_kvm.py
Labels: Python, component:integration-test

#6265 .github: run coverage on pull request
  .github/workflows/coverage-check.yml
Labels: component:UI, component:backup

#6185 Fix spelling
  engine/orchestration/src/main/java/com/cloud/agent/manager/ClusteredAgentManagerImpl.java
  engine/schema/src/main/resources/META-INF/db/schema-2214to30.sql
  engine/schema/src/main/resources/META-INF/db/schema-227to228.sql
  engine/schema/src/main/resources/META-INF/db/schema-302to40.sql
  engine/schema/src/main/resources/META-INF/db/schema-307to410.sql
  engine/schema/src/main/resources/META-INF/db/schema-40to410.sql
  engine/schema/src/main/resources/META-INF/db/schema-410to420.sql
  engine/schema/src/main/resources/META-INF/db/schema-442to450.sql
  engine/schema/src/main/resources/META-INF/db/schema-452to460.sql
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetScalerControlCenterResource.java
  plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetscalerResource.java
  scripts/storage/qcow2/get_domr_kernel.sh
  services/console-proxy/rdpconsole/pom.xml
  services/console-proxy/rdpconsole/src/main/java/common/adapter/AwtBellAdapter.java
  services/console-proxy/rdpconsole/src/main/java/common/asn1/Sequence.java
  services/console-proxy/rdpconsole/src/main/java/rdpclient/ntlmssp/ClientNtlmsspPubKeyAuth.java
  services/console-proxy/rdpconsole/src/main/java/rdpclient/rdp/ServerDemandActivePDU.java
  services/console-proxy/rdpconsole/src/main/java/rdpclient/rdp/ServerMCSAttachUserConfirmPDU.java
  services/console-proxy/rdpconsole/src/main/java/rdpclient/rdp/ServerX224DataPdu.java
  services/console-proxy/rdpconsole/src/main/java/streamer/BaseElement.java
  services/console-proxy/rdpconsole/src/main/java/streamer/DataSource.java
  services/console-proxy/rdpconsole/src/main/java/streamer/InputStreamSource.java
  services/console-proxy/rdpconsole/src/main/java/streamer/OutputStreamSink.java
  services/console-proxy/rdpconsole/src/main/java/streamer/PipelineImpl.java
  services/console-proxy/rdpconsole/src/main/java/streamer/Queue.java
  services/console-proxy/rdpconsole/src/main/java/streamer/SyncLink.java
  services/console-proxy/rdpconsole/src/main/java/streamer/apr/AprSocketSink.java
  services/console-proxy/rdpconsole/src/main/java/streamer/apr/AprSocketSource.java
  services/console-proxy/rdpconsole/src/main/java/streamer/debug/FakeSource.java
  services/console-proxy/rdpconsole/src/main/java/streamer/debug/MockServer.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyHttpHandlerHelper.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/PremiumSecondaryStorageManagerImpl.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
  setup/db/create-schema.sql
  systemvm/agent/noVNC/core/rfb.js
  systemvm/debian/opt/cloud/bin/setup/common.sh
  test/integration/component/maint/test_redundant_router.py
Labels: component:vmware, component:console-proxy, component:networking, type:cleanup, component:agent, component:build, Severity:Trivial, component:orchestration, component:storage

#6275 ui: Incorrect column key specified in secondary store column filter
  ui/src/components/view/ListView.vue
  ui/src/views/AutogenView.vue
Labels: component:UI

#6149 Update SAML2 auth sessionkey cookie path
  plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
Labels: component:saml

#6279 ui: remove mandatory rule on root disk controller field while registering / updating a template
  ui/src/views/image/RegisterOrUploadTemplate.vue
  ui/src/views/image/UpdateTemplate.vue
Labels: type:bug, component:UI

#6285 UI: Fix custom unconstrained for a zone does not show CPU speed
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:UI

#6284 Fixed reset configuration response, to return the updated config value.
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Labels: type:bug, component:api

#5902 Allow users to view reserved System VM IPs, if they're already allocated to user
  server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/test/java/com/cloud/server/ManagementServerImplTest.java
Labels: type:bug, component:management-server, component:networking, Severity:Minor, status:needs-testing

#6286 ui: Fix bulk deletion of ssh key pairs
  ui/src/config/section/compute.js
  ui/src/views/AutogenView.vue
Labels: type:bug, component:UI

#5848 Feat/add vdisk UUID to list volume
  api/src/main/java/com/cloud/storage/Volume.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
  engine/schema/src/main/java/com/cloud/storage/VolumeVO.java
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware, component:api, component:storage

#6290 UI: checksum field is optional for direct-download templates on kvm
  ui/src/views/image/RegisterOrUploadTemplate.vue
Labels: component:UI

#6288 ui: Fix Internal LB LB rule column and missing translation
  ui/public/locales/en.json
  ui/src/components/view/ListView.vue
Labels: type:bug, component:UI

#6287 Fix: Prevent NPE on disk offering search while listing VMs
  server/src/main/java/com/cloud/api/ApiDBUtils.java
Labels: type:bug, component:api, component:UI

#4774 Added configuration and Integration test to restrict public template …
  api/src/main/java/org/apache/cloudstack/query/QueryService.java
  server/src/main/java/com/cloud/acl/DomainChecker.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  test/integration/component/test_template_access_across_domains.py
Labels: component:api, component:security, Python, component:templates, status:needs-testing, component:integration-test

#6201 [UI] Added attach and detach features to UI for ROOT disks
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/AttachVolumeCmd.java
  ui/src/config/section/storage.js
  ui/src/views/storage/AttachVolume.vue
Labels: type:enhancement, component:api, component:UI

#6299 ui: Toggle Theme to default(light) on login
  ui/src/permission.js
Labels: type:bug, component:UI

#6300 UI: fix netmask is not passed to api when create share network
  ui/src/views/network/CreateSharedNetworkForm.vue
Labels: type:bug, component:UI

#5588 Mshost stats
  api/src/main/java/com/cloud/server/ManagementServerHostStats.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/ManagementServerResponse.java
  api/src/main/java/org/apache/cloudstack/management/ManagementServerStatus.java
  client/src/main/webapp/WEB-INF/web.xml
  engine/orchestration/src/main/java/com/cloud/agent/manager/ConnectedAgentAttache.java
  engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
  engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
  engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  framework/cluster/src/main/java/com/cloud/cluster/ClusterManager.java
  framework/cluster/src/main/java/com/cloud/cluster/ClusterManagerImpl.java
  framework/cluster/src/main/java/com/cloud/cluster/ClusterServicePdu.java
  framework/cluster/src/main/java/com/cloud/cluster/ManagementServerStatusVO.java
  framework/cluster/src/main/java/com/cloud/cluster/dao/ManagementServerHostDao.java
  framework/cluster/src/main/java/com/cloud/cluster/dao/ManagementServerStatusDao.java
  framework/cluster/src/main/java/com/cloud/cluster/dao/ManagementServerStatusDaoImpl.java
  framework/db/src/main/java/com/cloud/utils/db/DbUtil.java
  framework/spring/module/src/main/java/org/apache/cloudstack/spring/module/web/CloudStackContextLoaderListener.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListDbMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListMgmtsMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/ListUsageServerMetricsCmd.java
  plugins/metrics/src/main/java/org/apache/cloudstack/api/MetricConstants.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsService.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/ClusterMetricsResponse.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/DbMetricsResponse.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsSummary.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/ManagementServerMetricsResponse.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/UsageServerMetricsResponse.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/ZoneMetricsResponse.java
  plugins/metrics/src/test/java/org/apache/cloudstack/metrics/MetricsServiceImplTest.java
  server/pom.xml
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/ApiSessionListener.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/dao/ManagementServerJoinDao.java
  server/src/main/java/com/cloud/api/query/dao/ManagementServerJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/ManagementServerJoinVO.java
  server/src/main/java/com/cloud/server/DbStatsCollection.java
  server/src/main/java/com/cloud/server/ManagementServerHostStatsEntry.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/test/async-job-component.xml
  server/src/test/java/com/cloud/server/StatsCollectorTest.java
  test/integration/smoke/test_metrics_api.py
  ui/package-lock.json
  ui/public/locales/el_GR.json
  ui/public/locales/en.json
  ui/src/components/view/DetailsTab.vue
  ui/src/config/section/infra.js
  ui/src/config/section/infra/managementServers.js
  ui/src/core/lazy_lib/icons_use.js
  ui/src/views/AutogenView.vue
  ui/src/views/infra/InfraSummary.vue
  ui/src/views/infra/Metrics.vue
  utils/src/main/java/com/cloud/utils/LogUtils.java
Labels: component:management-server, component:api, component:UI, component:database, component:agent, type:new-feature, Severity:Minor, component:orchestration, complexity:normal, component:storage

#6245 Fix VM stats inconsistencies
  api/src/main/java/org/apache/cloudstack/api/response/StatsResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
  api/src/test/java/org/apache/cloudstack/api/response/StatsResponseTest.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntry.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntryBase.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/VmMetricsResponse.java
  plugins/metrics/src/main/java/org/apache/cloudstack/response/VolumeMetricsResponse.java
  ui/public/locales/ar.json
  ui/public/locales/ca.json
  ui/public/locales/de_DE.json
  ui/public/locales/el_GR.json
  ui/public/locales/en.json
  ui/public/locales/es.json
  ui/public/locales/fr_FR.json
  ui/public/locales/hu.json
  ui/public/locales/it_IT.json
  ui/public/locales/ko_KR.json
  ui/public/locales/nb_NO.json
  ui/public/locales/nl_NL.json
  ui/public/locales/pl.json
  ui/public/locales/pt_BR.json
  ui/src/config/section/compute.js
Labels: component:kvm, component:api, component:UI

#6306 DB: fix duplicated changes in schema-41610to41700.sql
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
Labels: Severity:BLOCKER, type:regression

#6200 KVM: Enable SSL if keystore exists
  agent/src/main/java/com/cloud/agent/AgentShell.java
Labels: type:bug, component:agent

#6303 server: fix NPE in travis and merge #6305
  server/src/main/java/com/cloud/api/ApiServer.java
  server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
Labels: type:bug, component:networking, component:travis, type:regression

#6296 xen: Fix volume snapshot deletion when it has child snapshots
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotObject.java
  test/integration/smoke/test_list_ids_parameter.py
Labels: Python, component:integration-test, component:storage

#6297 Fix upload volume format
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: type:bug, component:storage

#6301 server: do not display 'Default Egress Policy' for vpc tiers
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
Labels: type:bug, component:vpc

#6308 UI: Fix Usage Server stats date display
  ui/src/views/infra/Metrics.vue
Labels: type:bug, component:UI

#6309 UI: Fix upload resource icon button
  ui/src/components/view/UploadResourceIcon.vue
Labels: type:bug, component:UI

#6312 UI: Fixes InfraMammary screen not display
  ui/src/views/infra/InfraSummary.vue
Labels: type:bug, component:UI

#6311 UI: Fixes the warning display when building UI
  ui/src/views/infra/Metrics.vue
Labels: type:bug, component:UI

#6313 remove superfluent counter and fix log message
  server/src/main/java/com/cloud/api/ApiSessionListener.java
Labels: type:enhancement, type:cleanup

#6283 [VMWare] error when detaching volume
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageLayoutHelper.java
Labels: type:bug, component:vmware

#6314 network: fix event, acl, firewall for ipv6 nw
  api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/CreateIpv6FirewallRuleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/DeleteIpv6FirewallRuleCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/UpdateIpv6FirewallRuleCmd.java
  core/src/main/java/com/cloud/agent/api/routing/SetIpv6FirewallRulesCommand.java
  core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/SetIpv6FirewallRulesConfigItem.java
  core/src/main/java/com/cloud/agent/resource/virtualnetwork/model/FirewallRule.java
  engine/schema/src/main/java/com/cloud/offerings/dao/NetworkOfferingDao.java
  engine/schema/src/main/java/com/cloud/offerings/dao/NetworkOfferingDaoImpl.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/NetworkOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/VpcOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
  systemvm/debian/opt/cloud/bin/configure.py
  systemvm/debian/opt/cloud/bin/cs/CsNetfilter.py
  systemvm/debian/opt/cloud/bin/setup/bootstrap.sh
  systemvm/debian/opt/cloud/bin/setup/common.sh
  systemvm/debian/opt/cloud/bin/setup/router.sh
Labels: type:bug, component:ipv6, component:virtual-router, component:api, component:networking, Python

#6315 ui,api: fix api resourcename and user/project event resource
  server/src/main/java/com/cloud/event/dao/EventJoinDaoImpl.java
  ui/src/views/dashboard/UsageDashboard.vue
Labels: type:bug, component:UI

#6317 Disable creating StorPool logs when there isn't StorPool primary storage
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/collector/StorPoolAbandonObjectsCollector.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolSnapshotStrategy.java
Labels: type:bug, component:primary-storage, component:storage

#6319 Move user shared networks tests to component tests
  .travis.yml
  test/integration/component/test_network_permissions.py
  test/integration/component/test_user_private_gateway.py
  test/integration/component/test_user_shared_network.py
Labels: type:bug, component:travis, Python, component:integration-test

#6322 ui: add route for network acl event resource
  ui/src/utils/plugins.js
Labels: type:bug, component:UI

#6281 Fix grammatical errors on en.json
  ui/public/locales/ar.json
  ui/public/locales/ca.json
  ui/public/locales/de_DE.json
  ui/public/locales/el_GR.json
  ui/public/locales/en.json
  ui/public/locales/es.json
  ui/public/locales/fr_FR.json
  ui/public/locales/hu.json
  ui/public/locales/it_IT.json
  ui/public/locales/ja_JP.json
  ui/public/locales/ko_KR.json
  ui/public/locales/nb_NO.json
  ui/public/locales/nl_NL.json
  ui/public/locales/pl.json
  ui/public/locales/pt_BR.json
  ui/public/locales/ru_RU.json
  ui/public/locales/zh_CN.json
  ui/src/views/compute/InstanceTab.vue
Labels: type:bug, component:UI

#6325 UI: Fix filter width to display options
  ui/src/views/AutogenView.vue
Labels: type:bug, component:UI

#6333 ui: Fix groupaction for nw cleanup and Notify when groupaction fails
  ui/src/config/section/network.js
  ui/src/utils/plugins.js
Labels: type:bug, component:UI

#6324 Improve log when live patching fails
  utils/src/main/java/com/cloud/utils/FileUtil.java
Labels: type:bug

#6329 test: fix ipv6 network test for xenserver
  test/integration/smoke/test_network_ipv6.py
Labels: type:bug, Python, component:integration-test

#6335 UI: Fix detail settings
  ui/src/components/view/DetailSettings.vue
  ui/src/components/widgets/TooltipButton.vue
Labels: type:bug, component:UI

#6337 ui: Fix migrate systemVM icon when stopped
  ui/src/config/section/infra/systemVms.js
Labels: type:bug, component:UI

#6336 UI: show startip and endip if network offering support specified ip ranges
  ui/src/views/network/CreateIsolatedNetworkForm.vue
Labels: type:bug, component:UI

#6340 ui: Fix template delete issue
  ui/src/views/image/TemplateZones.vue
Labels: type:bug, component:UI
