Repository apache/cloudstack, pull requests merged in 2022-02, with the labels that each got.

#5892 [XenServer/XCP-ng] Sync the 'platform' setting according to the 'cpu.corespersocket' setting
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java
Labels: component:XenServer

#5852 server: find suitable disk offering for volume upload
  engine/schema/src/main/java/com/cloud/storage/dao/DiskOfferingDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/DiskOfferingDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  ui/src/views/storage/UploadLocalVolume.vue
Labels: status:needs-testing

#5473 api,server: add params for updatehypervisorcapabilities API
  api/src/main/java/com/cloud/hypervisor/HypervisorCapabilities.java
  api/src/main/java/com/cloud/server/ManagementService.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/config/UpdateHypervisorCapabilitiesCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/HypervisorCapabilitiesResponse.java
  engine/schema/src/main/java/com/cloud/hypervisor/HypervisorCapabilitiesVO.java
  engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  test/integration/component/test_hypervisor_capabilities.py
  tools/marvin/marvin/lib/base.py
Labels: component:api

#5920 server: allow normal users to create isolated network without source nat
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: component:networking, status:needs-testing

#5929 ui: fix related key for section
  ui/src/config/router.js
Labels: component:UI

#5506 kvm: Use lscpu to get cpu max speed
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
Labels: component:kvm

#5870 VMware7 support: Add schema changes for update2 and update3
  engine/schema/src/main/resources/META-INF/db/schema-41600to41610.sql
Labels: component:vmware, status:needs-testing

#5912 Added hot plugging of vifs in case of VMware isolated networks
  api/src/main/java/com/cloud/agent/api/to/IpAddressTO.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VmwareVmImplementer.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManager.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
  server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Labels: component:vmware, component:virtual-router, component:advanced-networking, status:needs-testing

#5931 ui: fix ssh keypair navigation
  ui/src/components/view/ListView.vue
  ui/src/views/AutogenView.vue
Labels: component:UI

#5859 add logging to deployment planners
  api/src/main/java/org/apache/cloudstack/api/BaseCmd.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManagerImpl.java
  plugins/affinity-group-processors/explicit-dedication/src/main/java/org/apache/cloudstack/affinity/ExplicitDedicationProcessor.java
  plugins/deployment-planners/implicit-dedication/src/main/java/com/cloud/deploy/ImplicitDedicationPlanner.java
  server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
  ui/public/locales/en.json
  ui/src/views/offering/AddComputeOffering.vue
Labels: status:needs-functional-definition, status:needs-investigation

#5630 simplify code using optional chaining in multiple views
  ui/src/views/infra/network/IpRangesTabPublic.vue
  ui/src/views/infra/network/IpRangesTabStorage.vue
  ui/src/views/infra/network/providers/ProviderItem.vue
Labels: component:UI, type:cleanup

#5832 Fix 'endpointe.url' global settings configuration typo
  api/src/main/java/org/apache/cloudstack/config/ApiServiceConfiguration.java
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
  server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
  test/integration/smoke/test_kubernetes_clusters.py
Labels: type:enhancement, type:config

#5947 [issue-5946] upgrade to xstream 1.4.19
  pom.xml
Labels: component:security

#5933 ui: fix select networks for template nic
  ui/public/locales/en.json
  ui/src/components/view/InstanceNicsNetworkSelectListView.vue
  ui/src/components/view/NicNetworkSelectForm.vue
  ui/src/views/compute/DeployVM.vue
Labels: component:UI, status:needs-testing

#5517 Fix #3448 quota calculation for monthly tariffs
  framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
  framework/quota/src/test/java/org/apache/cloudstack/quota/QuotaManagerImplTest.java
Labels: component:quota

#5942 [issue-5939] upgrade commons-compress to 1.21
  pom.xml
Labels: component:security

#5878 maven: migrate short-term to reload4j v1.2.18
  framework/managed-context/pom.xml
  plugins/alert-handlers/snmp-alerts/pom.xml
  plugins/alert-handlers/syslog-alerts/pom.xml
  plugins/hypervisors/ovm3/pom.xml
  plugins/integrations/kubernetes-service/pom.xml
  plugins/network-elements/juniper-contrail/pom.xml
  plugins/user-authenticators/ldap/pom.xml
  pom.xml
  services/console-proxy/server/pom.xml
  services/secondary-storage/server/pom.xml
  test/pom.xml
  utils/pom.xml
Labels: Severity:Critical, component:logging

#5851 packaging: display First Install and Onboarding Message
  debian/cloudstack-agent.postinst
  debian/cloudstack-management.postinst
  debian/cloudstack-usage.postinst
  packaging/centos7/cloud.spec
  packaging/centos8/cloud.spec
  packaging/suse15/cloud.spec
  scripts/installer/cloudstack-help-text
  ui/public/locales/en.json
  ui/src/views/dashboard/OnboardingDashboard.vue
Labels: component:packaging, status:needs-testing

#5954 Skip systemVM template registration for Simulator
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Labels: simulator

#5949 [issue-5948] upgrade bouncycastle due to cve
  client/pom.xml
  plugins/integrations/kubernetes-service/pom.xml
  pom.xml
  services/console-proxy/rdpconsole/pom.xml
  services/console-proxy/rdpconsole/src/main/java/streamer/bco/BcoSocketWrapperImpl.java
  utils/pom.xml
Labels: component:security, status:needs-testing

#5904 UI - Add Network: shows "Offering for Isolated networks with no Source Nat service" on Network Offering for normal users
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateNetwork.vue
Labels: component:UI

#5953 [issue-5952] upgrade to jetty 9.4.44.v20210927
  pom.xml
Labels: component:security

#5968 [issue-5943] xerces 2.12.2
  pom.xml
Labels: component:security

#5956 Add disk space in systemVM template registration script
  scripts/storage/secondary/setup-sysvm-tmplt
Labels: systemvm-template-change

#5961 Optional chaining used to enhance readability
  ui/src/components/header/ProjectMenu.vue
  ui/src/components/view/BulkActionProgress.vue
  ui/src/components/view/DedicateData.vue
Labels: component:UI, type:cleanup

#5850 api, server: fix add-remove vpn user without vpn owner
  api/src/main/java/com/cloud/network/vpn/RemoteAccessVpnService.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vpn/RemoveVpnUserCmd.java
  server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
Labels: component:networking, status:needs-testing

#5879 Role escalation prevention
  api/src/main/java/com/cloud/user/AccountService.java
  api/src/main/java/org/apache/cloudstack/acl/APIChecker.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmdTest.java
  plugins/acl/dynamic-role-based/src/main/java/org/apache/cloudstack/acl/DynamicRoleBasedAPIAccessChecker.java
  plugins/acl/project-role-based/src/main/java/org/apache/cloudstack/acl/ProjectRoleBasedApiAccessChecker.java
  plugins/acl/static-role-based/src/main/java/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java
  plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryService.java
  plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
  plugins/api/rate-limit/src/main/java/org/apache/cloudstack/ratelimit/ApiRateLimitServiceImpl.java
  plugins/hypervisors/baremetal/src/main/java/org/apache/cloudstack/api/BaremetalProvisionDoneNotificationCmd.java
  plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
  server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
Labels: Severity:Critical, status:needs-testing

#5978 ui: Allow domain admin to configure subdomain limits
  ui/src/config/section/domain.js
Labels: type:bug, component:UI

#5910 [VMware] Update SCSI controllers for VMs
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: type:bug, component:vmware

#5980 [Vmware] Prevent NPE on template registration if guest OS is removed
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java
Labels: type:bug, component:vmware, component:templates

#5867 Source and destination CIDR trimming
  api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateEgressFirewallRuleCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/user/firewall/CreateEgressFirewallRuleCmdTest.java
Labels: type:bug, component:networking

#5974 Add option to infer boot type and mode from template
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:UI, component:templates

#5937 [UI] Added customization options for menu and dashboard elements
  ui/docs/customize.md
  ui/src/style/vars.less
  ui/src/views/dashboard/CapacityDashboard.vue
  ui/src/views/dashboard/UsageDashboard.vue
  ui/theme.config.js
Labels: type:enhancement, component:UI

#5923 [UI] Addressing Dynamically Scale of KVM VMs
  ui/public/locales/en.json
  ui/public/locales/pt_BR.json
  ui/src/views/compute/ScaleVM.vue
  ui/src/views/compute/wizard/ComputeSelection.vue
Labels: type:enhancement, component:kvm, component:UI

#5882 [UI] fix delete domain
  ui/src/views/iam/DomainActionForm.vue
  ui/src/views/iam/DomainView.vue
Labels: component:UI

#5955 [Simulator] Fix NPE in SolidFireHostListener
  plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java
  plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireSharedHostListener.java
Labels: type:bug, simulator

#5982 Fix attach volume error for VM - different scope for VM volume and volume disk offering
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: type:bug

#5960 Fix: allow executing CopyCommand operations in parallel when it is set
  engine/components-api/src/main/java/com/cloud/hypervisor/HypervisorGuruManager.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruManagerImpl.java
Labels: type:enhancement, component:vmware

#5995 ui: Pass rootdisksize only if template is not deployasis
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:vmware, component:UI

#5863 CKS Enhancements and SystemVM template upgrade improvements
  .gitignore
  agent/src/main/java/com/cloud/agent/AgentShell.java
  api/src/main/java/com/cloud/vm/VmDetailConstants.java
  engine/schema/pom.xml
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
  engine/schema/src/main/resources/META-INF/db/schema-41600to41610.sql
  engine/schema/templateConfig.sh
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java
  plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/CreateKubernetesClusterCmd.java
  plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml
  plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
  plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml
  plugins/integrations/kubernetes-service/src/main/resources/script/upgrade-kubernetes.sh
  pom.xml
  scripts/util/create-kubernetes-binaries-iso.sh
  systemvm/debian/opt/cloud/bin/setup/cksnode.sh
  test/integration/smoke/test_kubernetes_clusters.py
  tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
  tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh
  tools/appliance/systemvmtemplate/template.json
  ui/public/locales/en.json
  ui/src/config/section/image.js
  ui/src/views/compute/CreateKubernetesCluster.vue
  ui/src/views/compute/KubernetesServiceTab.vue
  utils/src/main/java/com/cloud/utils/EncryptionUtil.java
  utils/src/main/java/com/cloud/utils/script/Script.java
  utils/src/main/java/com/cloud/utils/ssh/SSHCmdHelper.java
  utils/src/main/java/org/apache/cloudstack/utils/security/DigestHelper.java
Labels: systemvm-template-change, status:needs-testing

#5983 Added a log line to HttpUploadServerHandler
  services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
Labels: type:enhancement, complexity:trivial

#5986 [Simulator] Add zone wide storage
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  ui/src/views/infra/AddPrimaryStorage.vue
Labels: type:enhancement, simulator

#6000 server: reapply checkVmProfileAndHost to check guest os preference
  server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
Labels: type:regression

#6003 ui: minor change with help text on dashboard
  ui/public/locales/en.json
Labels: type:bug, component:UI

#5988 Improve messages on adding hosts errors
  server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Labels: component:management-server, type:improvement

#5985 [VMware] Support for removal of NIC on IP disassociation on the VR
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Labels: type:bug, component:vmware, status:needs-testing

#6006 UI: Fix issue while listing projects in the Project Menu - DashBoard
  ui/src/components/header/ProjectMenu.vue
Labels: component:UI, type:regression

#5996 Allow scaling VM to a service offering having different storage tags
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:api

#6010 UI: Fix move VM out of a project
  ui/src/utils/request.js
Labels: type:bug, component:UI

#6009 UI: fix network list when assign vm to other accounts in project view
  ui/src/utils/request.js
  ui/src/views/compute/AssignInstance.vue
Labels: type:bug, component:UI

#6002 server: fix host anti-affinity when start batch vms
  plugins/affinity-group-processors/host-anti-affinity/src/main/java/org/apache/cloudstack/affinity/HostAntiAffinityProcessor.java
Labels: type:bug

#5901 Fix Usage event when a volume in allocated state is deleted
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: type:bug, component:usage-server, status:needs-testing

#4339 Allow domain admin to change domain and account settings
  engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  ui/src/config/section/account.js
  ui/src/config/section/config.js
  ui/src/config/section/domain.js
Labels: type:enhancement, type:improvement, status:needs-testing

#6001 ui: Adding option to select columns to display
  ui/public/locales/en.json
  ui/src/store/getters.js
  ui/src/store/modules/app.js
  ui/src/store/modules/user.js
  ui/src/store/mutation-types.js
  ui/src/views/AutogenView.vue
Labels: type:enhancement, component:UI

#5970 Improve default network offering setting for egress policy
  api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  ui/public/locales/en.json
  ui/src/components/view/DetailsTab.vue
  ui/src/config/section/network.js
  ui/src/views/network/EgressRulesTab.vue
  ui/src/views/offering/AddNetworkOffering.vue
Labels: component:api, component:UI, type:improvement

#6015 system_use column is not part of disk offering
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Labels: type:bug, Severity:BLOCKER

#6023 ui : Fix linting issue
  ui/src/views/network/EgressRulesTab.vue
Labels: type:bug, component:UI, Severity:Trivial

#6024 ui: Display yes / no for vm requiring upgrade
  ui/src/components/view/ListView.vue
  ui/src/components/widgets/Status.vue
Labels: type:bug, component:UI

#6025 ui: Fix column names translation issue
  ui/public/locales/en.json
  ui/src/components/view/AnnotationsTab.vue
  ui/src/components/view/SearchView.vue
  ui/src/views/AutogenView.vue
Labels: type:bug, component:UI

#6020 UI: Reword the setting panel warning
  ui/public/locales/en.json
Labels: component:UI, Severity:Trivial

#6027 prevent <ctrl>-<enter> handler from <space> from toggling checkboxes
  ui/src/views/image/RegisterOrUploadIso.vue
  ui/src/views/image/RegisterOrUploadTemplate.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/offering/AddNetworkOffering.vue
  ui/src/views/offering/AddVpcOffering.vue
Labels: component:UI, status:needs-testing

#6029 [KVM] Disconnect the volumes with the proper storage adaptor.
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
Labels: type:bug, component:kvm, component:managed-storage

#6042 [vmware, ssvm] Scale down of ssvm
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/PremiumSecondaryStorageManagerImpl.java
Labels: type:bug, component:ssvm, Severity:Critical, status:needs-testing
