Repository apache/cloudstack, pull requests merged in 2022-09, with the labels that each got.

#6693 Ignore opensaml's slf4j dependencies
  pom.xml
Labels: component:api, Python, component:agent, component:build

#6707 ui: fix set reservation toggle in add public ip range
  ui/src/views/infra/network/IpRangesTabPublic.vue
Labels: component:UI

#6705 server: fix check for ipv6 range overlap
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Labels: Severity:Critical

#6696 kvm: add libvirt host capabilities method for cpu speed retrieval
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
  plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
Labels: component:kvm

#6708 UI: fix bulk delete project with cleanup
  ui/src/config/section/project.js
Labels: component:UI

#6706 systemvm,vr: disable radvd for non-applicable VRs
  systemvm/debian/opt/cloud/bin/setup/dhcpsrvr.sh
Labels: component:virtual-router, component:networking

#6730 Jacoco: fix no coverage result in server and some other modules
  plugins/api/discovery/pom.xml
  plugins/api/rate-limit/pom.xml
  plugins/api/solidfire-intg-test/pom.xml
  plugins/api/vmware-sioc/pom.xml
  plugins/metrics/pom.xml
  plugins/network-elements/juniper-contrail/pom.xml
  server/pom.xml
Labels: component:vmware, component:networking, component:build

#6728 upgrade a backported patch
  engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
Labels: type:bug, Severity:Major

#6729 server: fix network upgrade for IPv6
  server/src/main/java/com/cloud/network/Ipv6ServiceImpl.java
  server/src/test/java/com/cloud/network/Ipv6ServiceImplTest.java
Labels: component:ipv6, component:networking, Severity:BLOCKER

#6725 Reset unusable db connections
  framework/db/src/main/java/com/cloud/utils/db/ConnectionConcierge.java
Labels: component:database, Severity:Critical

#6269 Improve error message on storage tags update
  engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/test/java/com/cloud/configuration/ConfigurationManagerTest.java
Labels: component:storage

#6712 UI: Build Dockerfile with Node v14
  ui/Dockerfile
Labels: component:UI, docker

#6691 Fix min balance for API quotaCredits to be optional
  plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaCreditsCmd.java
Labels: component:quota

#6721 UI fix Theme text color not bind navTextColorPick and reset button
  ui/src/components/view/Setting.vue
Labels: component:UI

#6741 UI: fixes errors in the Console.vue
  ui/src/components/widgets/Console.vue
Labels: component:UI

#6710 Allow option of exposing VM domain info via instance metadata
  api/src/main/java/com/cloud/network/NetworkModel.java
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkModelImpl.java
  server/src/main/java/com/cloud/network/element/CloudZonesNetworkElement.java
  server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
  server/src/test/java/com/cloud/network/element/ConfigDriveNetworkElementTest.java
  systemvm/debian/var/www/html/latest/.htaccess
  test/integration/component/test_configdrive.py
Labels: component:virtual-router, component:api, component:networking, Python, component:compute, component:orchestration, component:integration-test

#6759 DatabaseUpgradeChecker: add upgrade path from 4.17.0.1 to 4.17.1.0
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
Labels: Severity:BLOCKER

#6689 Added new logs to volume creation
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/GarbageCollectingStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/LocalStoragePoolAllocator.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/ClusterMO.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Labels: component:vmware, component:local-storage, component:orchestration, component:storage

#6683 Return vm userdata
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDao.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  ui/src/utils/util.js
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/EditVM.vue
Labels: component:api, component:UI

#6224 Fix migrate volume permissions
  engine/schema/src/main/resources/META-INF/db/schema-41710to41800.sql
  ui/src/config/section/storage.js
Labels: component:UI

#6767 mvn: bump version ahead of next major release
  pom.xml
Labels: component:build

#6779 api: fix event type and description for createTag
  api/src/main/java/org/apache/cloudstack/api/command/user/tag/CreateTagsCmd.java
Labels: component:api

#6737 fix usage charging for deleted/resized volumes
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
Labels: component:usage-server, status:needs-testing

#6782 README: update and refactor project README page
  README.md
  ui/docs/screenshot-dashboard.png
Labels: component:UI

#6656 vr: fix packet interface mismatch
  systemvm/debian/opt/cloud/bin/configure.py
  systemvm/debian/opt/cloud/bin/cs/CsAddress.py
Labels: component:virtual-router, component:networking, Python

#6768 Allow template names upto 255 chars
  api/src/main/java/com/cloud/template/VirtualMachineTemplate.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
Labels: component:api

#4438 Prometheus exporter enhancement
  engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDao.java
  engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDaoImpl.java
  engine/schema/src/main/java/com/cloud/user/dao/AccountDao.java
  engine/schema/src/main/java/com/cloud/user/dao/AccountDaoImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/UserVmDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
  plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
  plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServer.java
  plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServerImpl.java
Labels: component:api, component:travis, component:agent, type:new-feature, component:build
