Repository apache/cloudstack, pull requests merged in 2023-02, with the labels that each got.

#7151 UI: fix missing networkid and zoneid when add instance from vpc network
  ui/src/views/network/VpcTiersTab.vue
Labels: component:UI

#7145 server: add/update user vm details for new root disk size (issue 7139)
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: component:storage

#7147 cks: Fix provider deployment when cluster is in a project
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
  plugins/integrations/kubernetes-service/src/main/resources/script/deploy-cloudstack-secret
Labels: component:kubernetes

#7156 Fix UI not loading after merge conflict issue
  ui/public/locales/en.json
Labels: component:UI

#7158 Removed duplicate labels
  ui/public/locales/en.json
Labels: component:UI

#7146 Adjusts/fixes in quota tariff APIs
  plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffCreateCmd.java
  plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffDeleteCmd.java
  plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffListCmd.java
  plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffUpdateCmd.java
Labels: component:quota

#7132 Add console session cleanup task
  api/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManager.java
  engine/schema/src/main/java/com/cloud/vm/ConsoleSessionVO.java
  engine/schema/src/main/java/com/cloud/vm/dao/ConsoleSessionDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/ConsoleSessionDaoImpl.java
  engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
  server/src/main/java/com/cloud/consoleproxy/AgentHookBase.java
  server/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManagerImpl.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyClientStatsCollector.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyGCThread.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
Labels: component:console-proxy, component:api

#7157 ui: fix build issue on arm/Mac
  ui/package-lock.json
  ui/package.json
Labels: component:UI

#7003 utils,framework/db: Introduce new database encryption cipher based on AesGcmJce
  client/conf/db.properties.in
  debian/rules
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade450to451.java
  engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
  framework/db/src/main/java/com/cloud/utils/crypt/DBEncryptionFinderCLI.java
  framework/db/src/main/java/com/cloud/utils/crypt/EncryptionSecretKeyChanger.java
  framework/db/src/main/java/com/cloud/utils/crypt/OVFPropertyTO.java
  framework/db/src/test/java/com/cloud/utils/crypt/EncryptionSecretKeyChangerTest.java
  packaging/centos7/cloud.spec
  packaging/centos8/cloud.spec
  pom.xml
  scripts/storage/secondary/cloud-install-sys-tmplt
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
  setup/bindir/cloud-migrate-databases.in
  setup/bindir/cloud-setup-databases.in
  setup/bindir/cloud-setup-encryption.in
  test/integration/smoke/test_primary_storage.py
  tools/devcloud4/common/development-installation/files/default/cloud-install-sys-tmplt
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
  utils/pom.xml
  utils/src/main/java/com/cloud/utils/EncryptionUtil.java
  utils/src/main/java/com/cloud/utils/SerialVersionUID.java
  utils/src/main/java/com/cloud/utils/crypt/AeadBase64Encryptor.java
  utils/src/main/java/com/cloud/utils/crypt/Base64Encryptor.java
  utils/src/main/java/com/cloud/utils/crypt/CloudStackEncryptor.java
  utils/src/main/java/com/cloud/utils/crypt/DBEncryptionUtil.java
  utils/src/main/java/com/cloud/utils/crypt/EncryptionCLI.java
  utils/src/main/java/com/cloud/utils/crypt/EncryptionException.java
  utils/src/main/java/com/cloud/utils/crypt/EncryptionSecretKeyChecker.java
  utils/src/main/java/com/cloud/utils/crypt/LegacyBase64Encryptor.java
  utils/src/main/java/com/cloud/utils/db/DbProperties.java
  utils/src/main/java/com/cloud/utils/server/ServerProperties.java
  utils/src/test/java/com/cloud/utils/crypt/EncryptionSecretKeyCheckerTest.java
Labels: component:management-server, component:packaging, component:usage-server, Python, component:database, component:build, distro:ubuntu, distro:centos, component:integration-test, component:storage

#7152 Quota VM_DISK tariff calculation
  api/src/main/java/org/apache/cloudstack/usage/UsageUnitTypes.java
  engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
  framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
  framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaTypes.java
  framework/quota/src/test/java/org/apache/cloudstack/quota/QuotaManagerImplTest.java
Labels: component:api, component:quota

#7059 guestos: add el9 distros
  engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
Labels: status:ready-for-merge

#7122 Github Action: Build docker image for cloudstack-simulator
  .github/workflows/docker-cloudstack-simulator.yml
Labels: component:integration

#7176 .github: set docker repository to apache
  .github/workflows/docker-cloudstack-simulator.yml
Labels: component:integration

#7063 server: do not deploy or upgrade vm with inactive service offering
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinition.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
Labels: component:networking, component:compute, component:orchestration

#7112 Make displayText in createNetwork optional
  api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
  api/src/test/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmdTest.java
  test/integration/smoke/test_create_network.py
  ui/src/views/network/CreateIsolatedNetworkForm.vue
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
Labels: component:api, component:networking, component:UI, Python, component:integration-test

#7164 UI: fix security group lists in project view
  ui/src/views/compute/wizard/SecurityGroupSelection.vue
Labels: component:UI

#7166 UI: Integrate Tungsten Fabric
  tools/apidoc/gen_toc.py
  ui/public/locales/en.json
  ui/src/assets/icons/tungsten.svg
  ui/src/components/view/ListView.vue
  ui/src/components/view/NicNetworkSelectForm.vue
  ui/src/components/view/StoragePoolSelectView.vue
  ui/src/components/widgets/Breadcrumb.vue
  ui/src/config/section/network.js
  ui/src/core/lazy_lib/icons_use.js
  ui/src/style/vars.less
  ui/src/views/AutogenView.vue
  ui/src/views/compute/AttachIso.vue
  ui/src/views/compute/KubernetesServiceTab.vue
  ui/src/views/compute/ResetSshKeyPair.vue
  ui/src/views/image/UpdateTemplate.vue
  ui/src/views/infra/HostAdd.vue
  ui/src/views/infra/network/ServiceProvidersTab.vue
  ui/src/views/infra/zone/ZoneWizard.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
  ui/src/views/infra/zone/ZoneWizardNetworkSetupStep.vue
  ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
  ui/src/views/network/LoadBalancing.vue
  ui/src/views/network/UpdateNetwork.vue
  ui/src/views/network/tungsten/FirewallPolicyTab.vue
  ui/src/views/network/tungsten/FirewallRuleTab.vue
  ui/src/views/network/tungsten/FirewallTagTab.vue
  ui/src/views/network/tungsten/LogicalRouterTab.vue
  ui/src/views/network/tungsten/NetworkPolicyTab.vue
  ui/src/views/network/tungsten/TungstenFabric.vue
  ui/src/views/network/tungsten/TungstenFabricPolicyRule.vue
  ui/src/views/network/tungsten/TungstenFabricPolicyTag.vue
  ui/src/views/network/tungsten/TungstenFabricTableView.vue
  ui/src/views/network/tungsten/TungstenNetworkAction.vue
  ui/src/views/network/tungsten/TungstenNetworkTable.vue
  ui/src/views/storage/UploadVolume.vue
Labels: component:UI, Python

#7192 Added steps to get the offical docker image for cloudstack simulator
  tools/docker/README.md
Labels: docker

#7197 Fix login issue after logout from Configuration page
  ui/src/views/setting/ConfigurationTab.vue
Labels: component:UI

#7173 Tungsten: fix functional issues
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VRouterVifDriver.java
  plugins/network-elements/tungsten/src/main/java/org/apache/cloudstack/network/tungsten/service/TungstenService.java
  plugins/network-elements/tungsten/src/main/java/org/apache/cloudstack/network/tungsten/service/TungstenServiceImpl.java
  scripts/vm/network/tungsten/create_tap_device.sh
  scripts/vm/network/tungsten/delete_tap_device.sh
  scripts/vm/network/tungsten/setup_tungsten_vrouter.sh
  scripts/vm/network/tungsten/update_tungsten_loadbalancer_ssl.sh
  scripts/vm/network/tungsten/update_tungsten_loadbalancer_stats.sh
Labels: component:kvm, component:networking, component:agent, component:orchestration

#7177 Skip Coverage Check when forks are updated
  .github/workflows/codecov.yml
Labels: component:integration

#7199 .github: disable Sonar check on forks as it requires crendential
  .github/workflows/sonar-check.yml
Labels: component:integration

#7201 ui: fix add zone dialog for fix errors
  ui/src/views/infra/zone/ZoneWizard.vue
Labels: component:UI

#7198 UI: fix 'Next' button is stuck if no public ip range
  ui/public/locales/en.json
  ui/src/views/infra/zone/IpAddressRangeForm.vue
Labels: component:UI

#7190 integration test fixes for 4.18
  test/integration/smoke/test_deploy_vm_extra_config_data.py
  tools/marvin/marvin/lib/base.py
Labels: Python, component:marvin, component:integration-test

#7243 Fix console access on XCPng/Xen
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/RfbConstants.java
Labels: type:bug, component:console-proxy, Severity:BLOCKER

#7252 engine/schema: fix IDEMPOTENT_ADD_FOREIGN_KEY procedure does not work on mysql8
  engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
Labels: Severity:Critical

#7231 UI missing changes
  ui/public/locales/en.json
  ui/src/config/section/offering.js
Labels: component:UI

#7261 UI: Fix domain admins cannot create service offerings
  ui/src/views/offering/AddComputeOffering.vue
Labels: type:bug, component:UI

#7230 UI: Fix keyboard options regression
  ui/public/locales/ar.json
  ui/public/locales/ca.json
  ui/public/locales/de_DE.json
  ui/public/locales/el_GR.json
  ui/public/locales/en.json
  ui/public/locales/es.json
  ui/public/locales/fr_FR.json
  ui/public/locales/hu.json
  ui/public/locales/it_IT.json
  ui/public/locales/ko_KR.json
  ui/public/locales/nb_NO.json
  ui/public/locales/nl_NL.json
  ui/public/locales/pl.json
  ui/public/locales/pt_BR.json
  ui/public/locales/ru_RU.json
Labels: component:UI, Severity:Trivial

#7233 .github: use ref name as docker image name if ref type is tag
  .github/workflows/docker-cloudstack-simulator.yml
Labels: component:integration

#7256 Fix select default host option on deployment wizard
  ui/src/views/compute/DeployVM.vue
Labels: type:bug, component:UI

#7267 packaging: fix centos8/el8 upgrade
  packaging/centos8/cloud.spec
Labels: component:packaging, distro:centos

#7270 cleanup: remove testing logs
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: component:kvm

#7205 SQL: Remove snapshot references if primary storage pool has been removed
  engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
Labels: Severity:Minor

#7257 Fix Quota plugin state on QuotaSummaryResponse
  plugins/database/quota/src/main/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java
  plugins/database/quota/src/test/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
Labels: component:quota

#7287 Fix VNC SecurityType None on RFB v3.8
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
  services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java
Labels: type:bug, component:console-proxy, Severity:BLOCKER

#7286 UI: fix error message when create load balancer as a normal user
  ui/src/views/network/LoadBalancing.vue
Labels: Severity:BLOCKER, component:UI
